### ISSUE TITLE
Create DB-Iconset

### ISSUE THREAD

**Issue by mstarke** [mstarke/MacPass#10]
Currently there are only a handful of icons created.

**Comment by sickill** [comment]
What about supporting multiple db icon sets, and allowing user to choose one in the preferences? 

MacPass could then ship with:

* original "90s" icon set (for people migrating from keepass(x) who don't want to shake their organization too much),
* a modern one based on Font Awesome, which would have mapping based more on the actual meaning (for people building their new databases, or the ones who favor nice looking set that are willing to update their group/entry settings).
* + ability to load a custom one (for creative people).

**Comment by mstarke** [comment]
Done for now since the merge of @JoannaOlsen pull request
