### ISSUE TITLE
Open multiple databases in one window

### ISSUE THREAD

**Issue by fenderle** [mstarke/MacPass#124]
Just like in KeePass for windows open multiple databases using tabs instead of different windows.

**Comment by yusf** [comment]
Would favor a tabbed style too, though recognizing the hardships.

**Comment by mstarke** [comment]
As stated before I have no intention to do this. What's it with the tabs anyway ;). OS X has a decent window management but maybe I'm more or a John Siracusa windows user. The more the better :)

**Comment by yusf** [comment]
Multiple windows aren't that bad actually, but most OS X users lack good methods to switch between them effectively. Personally I use the __⌘~__ command, "Move focus to next window in application".

**Comment by oscarfroberg** [comment]
Is Macpass supposed to find entries from all open databases (using autotype)? Because for me it only picks from the active one and I have to manually switch to the db window where the entry is located before autotype works.

**Comment by mstarke** [comment]
Currently looks only in the active document. This should be addressed :)

**Comment by oscarfroberg** [comment]
I usually work with three databases so that'd be great indeed. :)

**Comment by bl4ckmesa** [comment]
I would love this feature.

The UI part for me isn't as important as the search function being able to span across all open databases.  That would get me 90% there even if the UI isn't super-slick ;)

**Comment by oscarfroberg** [comment]
Yeah the global search UI sounds a bit tricky. Keepass 2 has open databases in tabs. Personally I don't need searching through all of them, but rather have Auto-Type search from all open ones. Which might practically be the same thing, except that theres no UI needed for that.

**Comment by oscarfroberg** [comment]
This has been implemented recently and works well. A minor complaint is that there's a bug where when there are multiple options and you select one, Macpass gets focus. Auto-typing works normally but Macpass is left in the foreground, on top of the web browser. When there's only one hit, Macpass is left in the background.

I guess this is because of the selection dialog that pops up to the foreground when there are multiple options. If possible, it would be nice to "push it to the background" after a selection has been made.

**Comment by mstarke** [comment]
I just tested MacPass under macOS 10.12 and the tabs feature works like intended. I do not plan to add this as a custom feature so I'll regard this as closed by apple ;)

**Comment by perfusorius** [comment]
Just a quick tip for anyone who doesn't want to change global tab settings just to change MacPass behavior (like me):
Completely close MacPass, open the terminal and enter:
`defaults write com.hicknhacksoftware.macpass AppleWindowTabbingMode always`
From now on in MacPass every file will be opened automatically in a new tab (unless it is already opened).
