### ISSUE TITLE
Feature request: support keepasshttp-like interface

### ISSUE THREAD

**Issue by nelsonmenezes** [mstarke/MacPass#14]
Thanks for the great project; glad to see an open source implementation native to OS X. A fantastic feature to implement (the only reason I'm using Kypass Companion for) is a keepasshttp interface that can be used to integrate with the respective Chrome/Firefox plugins.

Keepasshttp is written in C#; would need rewriting: https://github.com/pfn/keepasshttp

**Comment by mstarke** [comment]
See [MacPassHTTP](https://github.com/MacPass/MacPassHTTP)

**Comment by frdmn** [comment]
@mstarke awesome! :+1:

**Comment by tonycpsu** [comment]
How does one build the plugin?  Simply running xcodebuild at the top level gives me:

    MacPassHTTP/MacPassHTTP/MPHServerDelegate.h:10:9: fatal error: 'KeePassHTTPKit/KeePassHTTPKit.h' file not found
    #import <KeePassHTTPKit/KeePassHTTPKit.h>
            ^
    1 error generated.

and I don't see KeePassHTTPKit anywhere in the source for the plugin or MacPass

**Comment by frdmn** [comment]
@tonycpsu You need to install [Carthage](https://github.com/Carthage/Carthage) and then run `carthage update` to download the dependencies.

If you have Homebrew:

```shell
$ brew install carthage
```

**Comment by mstarke** [comment]
There seems to be an issue with the plugin. It doesn't supply matches it just authorizes access. I need to investigate what I broke. Sorry for the hype :-(

**Comment by mstarke** [comment]
Fixed. Had to fix some other threading issues but the plugin works - not all settings and features but it's usable.

**Comment by existpierre** [comment]
Work it!  Thanks

**Comment by chrisgross** [comment]
I can't get MacPassHTTP to appear in the plugins list. I've built the plugin, and it exists in ~/Library/Application Support/MacPass, but MacPass will not see it. This is true of both the packaged version of MacPass, as well as built from source.

**Comment by mstarke** [comment]
Did you check "load insecure plugins"?
If so, check Console.app and look for output from MacPass

**Comment by chrisgross** [comment]
I did. I see the following in the console: "1/14/16 12:59:48.794 PM MacPass[2285]: Preflight Error The bundle “MacPassHTTP.mpplugin” couldn’t be loaded because its executable couldn’t be located. The bundle’s executable couldn’t be located.
" 
There doesn't appear to be anything in  ~/Library/Application Support/MacPass/MacPassHTTP.mpplugin/Contents/MacOS. I wonder if that's why

**Comment by mstarke** [comment]
Very strange.
Try to archive MacPassHTTP and then move it to MacPass in Application Support manually

**Comment by mstarke** [comment]
Archive via Xcode i mean.

**Comment by chrisgross** [comment]
Ah, it looks like I didn't run xcodebuild from the MacPassHTTP directory. I guess that's possibly implied by the line in the readme "Compile and Install MacPassHTTP", but perhaps make that more explicit. Thanks for your help!

**Comment by ritzmann** [comment]
Would be lovely to get a release so that us Non-Mac-developer guys don't have to struggle with XCode. ;)
