### ISSUE TITLE
make search bar flexible

### ISSUE THREAD

**Issue by DominusExult** [mstarke/MacPass#147]
Search bar is looking good and I liked how it works.
My only "problem" is that I would like it a bit bigger in a bigger window. Preferably like finder which seems to have a minimum size (same as the MacPass size) and a maximum size, when the toolbar has enough space. The search bar size is "flexible" between min and max, depending on the size of the toolbar.

Also it seems the search bar is not yet part of the "customize toolbar" options.

**Comment by mstarke** [comment]
The current version of the search bar in the toolbar is a "system-default" version. So I guess this can be closed.
