### ISSUE TITLE
Support History on Edit

### ISSUE THREAD

**Issue by mrkdev** [mstarke/MacPass#179]
MacPass should store old passwords in the password history if the user changes to a new one.

Usecase:
- The user has a password stored in the database
- He creates a new password using the generator
- The Service for which this password is for may not accept it because of some security or password rules and force the user to reenter the old password
- Currently the user just lost the old password and cannot recover

If the password was stored in the history (like with KeePass), this would not happen.

**Comment by mstarke** [comment]
Current master is supports pushing history. There is however currently no way to revert or browse the history
