### ISSUE TITLE
MacPass website

### ISSUE THREAD

**Issue by travs** [mstarke/MacPass#226]
Hi all,

I've been using MacPass for a while now and I love it.

I think it should have a slick-looking website to go along with its slick interface, and I would be glad to help create one.

Such a site might attract new interest and help make this the biggest solution for password management on the mac (it's already the best, especially when http gets implemented).

I will get a basic site up soon, but if anyone is interested in helping (ex: with photos for the page, ideas, etc.) just comment and we'll be in touch. 

:closed_lock_with_key:

**Comment by mstarke** [comment]
See #700. MacPass organisation has a website that should be used as the source and the current page should state that the page has moved.
