### ISSUE TITLE
[Feature Request] Field References

### ISSUE THREAD

**Issue by mems** [mstarke/MacPass#238]
Actually I use 1Password with login entries that use mutliple URLs. For example my account on Amazon has following URLs: amazon.com, amazon.fr, amazon.co.uk
In KeePass it seems that you could use [FieldReference](http://keepass.info/help/base/fieldrefs.html)

[Can I use multiple URLs in the URL field of KeePass? — Super User](http://superuser.com/questions/434042/can-i-use-multiple-urls-in-the-url-field-of-keepass)

I saw that [references are supported](https://github.com/mstarke/MacPass/issues/146#issuecomment-53316471), but it's hard to create it manually (using UUIDs)

**Comment by lukas-schulze** [comment]
I use the latest version of MacPass 0.5.1 which still has problems copying password references.
Usernames work fine.
How can I fix it?

**Comment by mstarke** [comment]
References are supported but no UI Tool to easily build them is in place. This is something for a future release

**Comment by akcasoy** [comment]
I did not quite get this feature. We cannot add multiple URLs, but instead we can duplicate the entry, and reference the username and password fields of the old one. But how exactly? Could you please write it in an example?
