### ISSUE TITLE
Updating to 10.9 as minimum System

### ISSUE THREAD

**Issue by mstarke** [mstarke/MacPass#248]
Since @jamesrhurst  has added some functionality that requires 10.9 (or 10.8 but with some unpleasant runtime querying) I would like to update the minimum requirements to 10.9. @DominusExult did mention to just release a point version of MacPass and ask the users for their requirements. If you have any objections, please consider adding them in this thread. I've heard about some corporate situations making it rather hard to use 10.9 since some tend to stay on older OS X releases for a bit (too? ;) ) long. Anyway. If nothing get's in the way of updating the minimum requirements the next release will require 10.9.

**Comment by soliva** [comment]
:+1:

**Comment by sknick** [comment]
Given that newer version of Mac OS X are now free, this is a no-brainer. People with hardware that is too old probably have more issues than not being able to use MacPass.

**Comment by mstarke** [comment]
I've started to refresh some of the UI code and there are a ton of enhancements in 10.10 so I'll be aiming for a 10.10 minimum version for 0.7

**Comment by mstarke** [comment]
10.8 support is dropped.
