### ISSUE TITLE
Add simple perform Autotype command

### ISSUE THREAD

**Issue by mstarke** [mstarke/MacPass#288]
Besides the global auto type via a hot key Keepass allows for a simpler form where the user selects the entry and auto type switches back to the previous application. The difference is that a lookup is just in the scope of the selection (entry, window associations of this entry) and not the whole database.

**Comment by miscreanttoucan** [comment]
Sorry to be dense, but I looked above the commit where you said a "sort-of-working version is done." This commit states "Fixed more issue with invalid XML Characters corrupting database." What does this have to do with simple autotype? Did you reference the wrong commit?

**Comment by mstarke** [comment]
Right. I did some who move up two commits. 692ade211079c76c12d0417988bd00aea08c58a2 is the correct one.

**Comment by ravemir** [comment]
Just wanted to say I tested it on the current master version and it filled-in everything properly on my previous Chrome window, so if you're feeling adventurous, try it out!

**Comment by sickill** [comment]
This will be awesome addition. :+1:

**Comment by imcoddy** [comment]
Didn't get autotype working in 0.5.1, looking forward to this new feature and hope it works fine.
