### ISSUE TITLE
Presets for expiration date are greyed out

### ISSUE THREAD

**Issue by yonomitt** [mstarke/MacPass#292]
I just installed on Yosemite 10.10.1. When I click the drop down menu for "Use preset..." to set an expiration date for a password, all options are greyed out and cannot be selected.

I'm running in master, specifically from: ad07ca5036136ab6508798186b6a757bb4ba6bd6

**Comment by coyote4til7** [comment]
On 12/30/2014 6:38 AM, Michael Starke wrote:
>
> Scrap that last comment. I did notice there where some fuck ups after 
> converting the xibs to a higher XCode format. Results where exactly 
> what you describe.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/mstarke/MacPass/issues/292#issuecomment-68356707>.
>

I hope "unsubscribe" in the subject line works because Github doesn't 
include an unsubscribe message in the emails.

**Comment by mstarke** [comment]
You can unsubscribe to this via the "Unsubscribe" button in the notification section in the right hand side menu on the website. No clue if this can be done via email ;)
