### ISSUE TITLE
Size of databases saved with MacPass smaller than KeePass equivalent

### ISSUE THREAD

**Issue by AS-dh** [mstarke/MacPass#294]
I just discovered MacPass (through a hint in the KeePassX forum) and I'm really impressed with the functionality of the latest binary. Good work!  The only thing that bothers me is that the size of the database files saved by MacPass is significantly smaller (50KB instead of 100KB in my test database) than the equivalent KeePass file.  Is it due to that icon lossless compression mentioned in one of the issues or is there any other information being discarded / better compressed?

**Comment by mstarke** [comment]
Icons saving and loading should not have high impacts on the size. This is a common observation in the Keepass community. Files are compressed with gzip on save and the routine is based on system level libraries. Those libraries tend to have different compression levels. I for example use the highest settings so this might be the sole reason. What you can do is try to save the database without any compression. This then should result in comparable file sizes.

And thanks for the praise. Please be cautious with your usage of MacPass as it's still alpha software and there are plenty of bugs left uncovered.

**Comment by harizvi** [comment]
Good to see macpass make so much progress. 

Despite the compression choice, is the .kdbx file still compatible with other versions of keepass software on other platforms?  After editing with macpass, will I be able to take this file and load it in Windows or iPhone software.

**Comment by HomeSen** [comment]
Well, I don't see a reason why it shouldn't. And I also never had any
issues with modifying my .kdbx with MacPass and opening it with KeePass
2.x on Windows or on my iPhone, afterwards. Even sync'ing the modified
(on MacPass) .kdbx with a copy on Windows works (through KeePass 2.x)
like a charm.

Am 31.03.2015 um 02:08 schrieb Haider Rizvi:

**Comment by harizvi** [comment]
Good, thanks for confirming that you have been able to move it back and forth. That's a critical check for me, since I am on multiple platforms every day.

**Comment by HomeSen** [comment]
Any time again ;)

Since I'm in the same situation (mostly OS X and Windows, only, though),
I know that "fear" too well. In the beginning I always copied .kdbx's,
before moving/sync'ing back and forth :D But I know I can say with
certainty: MacPass is an awesome product, and only the lack of ("soon"
to come) features justifies the alpha status. Kudos to @mstarke for
bringing this awesome to us Apple folks.

Am 31.03.2015 um 17:03 schrieb Haider Rizvi:

**Comment by mstarke** [comment]
@harizvi  The main problem one might encounter is that of a missing history on entries edited with MacPass, other than that, everything should work well.

@HomeSen thanks for the praise. Current development hast stalled a bit but I hope to get the time to at least ad those "soon to be done" features ;-)

**Comment by harizvi** [comment]
@mstarke I noticed the missing history entries, not a big deal for me most of the time.

**Comment by HomeSen** [comment]
Hey friend!

 

Important message, please visit <http://iphoneitouch.fr/sad.php?rg0w7>

 

Patrick Walker

**Comment by HomeSen** [comment]
Hello!

 

New message, please read <http://shahelp.net/months.php?hmraw>

 

Patrick Walker

**Comment by HomeSen** [comment]
Hello!

 

Important message, please read <http://rkguptarecords.com/deep.php?b>

 

Patrick Walker

**Comment by HomeSen** [comment]
Hello!

 

Important message, please read <http://cognibyte.com/ashamed.php?7r20p>

 

Patrick Walker

**Comment by KFDCompiled** [comment]
@mstarke I've noticed that, when saving, macpass will strip auto-type target windows saved from keepass2

**Comment by mstarke** [comment]
@KFDCompiled nice catch, if you'd like, file the issue separately, even better if you put it on KeePassKit as this is probably the cause of the error!
