### ISSUE TITLE
[Feature Request] Inherit icon on New Entries

### ISSUE THREAD

**Issue by miscreanttoucan** [mstarke/MacPass#298]
When creating a new entry inside of a group, the new entry should default to use the icon of the parent group instead of the default icon (a key). To explain further, if I have a group (aka a folder) called "Internet" and it uses the globe icon, then new entries upon being created inside the "Internet" folder should also use the globe icon. This is consistent with how KeePass works.

**Comment by mstarke** [comment]
Nice find. Never noticed that.
