### ISSUE TITLE
Entries deleted from search results not removed from current view

### ISSUE THREAD

**Issue by miscreanttoucan** [mstarke/MacPass#299]
Found a bug.

If you navigate to an entry and delete it, the entry disappears. It's been put in the trash. So far, so good.

But if you do a search and delete an entry from there, the entry is still visible on the screen. If you navigate to where the entry was, it's gone. You can find it in the trash.

So the entry is getting deleted, but it looks to the end user as if nothing has happened after deleting the entry.

**Comment by mstarke** [comment]
And might I add - nice discovery :)

**Comment by timbru31** [comment]
Seems like the search is still affected.
I've had a duplicate entry (searched for the URL in MacPass), deleted one. The Group was set to Trash. So far so good. But when I deleted the trashed item again it was still visible.

After re-doing the search it was not listed anymore.
