### ISSUE TITLE
Reload DB onChange

### ISSUE THREAD

**Issue by miscreanttoucan** [mstarke/MacPass#300]
I've discovered a critical problem (for me at least) in the way MacPass works...

**What MacPass does:**

When locked, if the DB file changes, then MacPass is apparently opening a cached(?) or some other version of the DB file, not the actual file.

**What I want MacPass to do:**

When locked, if the DB file changes, I want MacPass to ensure that it's always opening the latest version of the DB file.

**Why?**

I use Dropbox to sync keepass files between a Mac, Windows, and Android phone. For years this has worked great (using KeePassX on the Mac).

I lock MacPass after a period of inactivity. If the DB file changes, I just want to unlock MacPass and have the latest version. However, MacPass is not getting the latest version. I lost some records before I understood what was happening.

If you add the ability to save the database whenever records are changed, then I could freely use MacPass without worrying about data loss.

It appears that my best workaround now is to always close out of MacPass after I'm done (cmd+W), but this is not ideal, especially since I have a less tech savvy wife also using MacPass with this configuration.

Thoughts?

**Comment by mstarke** [comment]
Thoughts!

Your observation on how MacPass holds data is correct. If you open a file, MacPass loads the data and shows you the lock screen. This has the side effect that no file system changes will be propagated.

There is a issue for the auto-reload as well so auto-save and auto-reload are more or less something that should be done. Watching the file for changes is rather easy, what makes this currently a cumbersome experience is the missing synchronisation feature. Keepass can synchronise two databases and therefor just import changes from the file to the open database. Another difference between Keepass an MacPass is the locking behaviour. KeePass saves the database when locked. I might move to that workflow as. Currently MacPass just encrypts and stores the encrypted data in memory. This has the nice benefit, that you will not overwrite a file unless you explicitly save it. It's debatable whether there should be a forced save before locking.

Until synchronisation is implemented, the only way to get this to work is:
a) reload the file if the database has no unsaved changes in MacPass - easy case (and probably yours)
b) show a dialog and ask the user what to do.

If synchronisation is there, the b) should be changed to
b) try to synchronise the databases. If the synchronisation is conflict free, just use this database. If conflicts arise, ask the user what to do. Basically this is bringing up the UI for database synchronisation.

**Comment by miscreanttoucan** [comment]
I *hate* to ask here, as I'm not sure whining for a status update is an appropriate use of the issue tracker. Any chance this could get implemented sooner rather than later? It's the *one* thing that really makes using MacPass problematic for me. It seems to me that two things are needed:

1.) Save the database onChange.

2.) When locking the DB, close out of it, so that when you sign back in, it's the same as opening the DB. (This way, if the DB file has changed, you'll be opening the latest version.)

I realize how much time and effort it takes to provide software for free, so I don't want to act like you owe me anything. I'm just really hoping for this one little feature...

Thanks for considering it.

**Comment by jongibbins** [comment]
Hi there.
This would also be beneficial here too as I have started using multiple platforms with KeePass 2. Other than this issue, MacPass seems to be the best on OS X.

Thanks

**Comment by ungeruehrt** [comment]
Would it be possible to implement at least a manual reload with `cmd + r`? This would be a great improvement in relation to having to close and reopen the database every time.

**Comment by mstarke** [comment]
I'd got as far as implement a file watcher and ask the user what to do.

**Comment by mstarke** [comment]
As of dd1322e224e0a44cbec20b32ac15b69f96bda86c MacPass now complains when the database is changed behind it's back. It's for sure buggy since there are edge cases that I might not have thought about.

I did change the behaviour on locking to work the same way as Keepass, that is, store the file. This then makes reaction to changes simple, I i just reload the data silently.

If the user did not lock the database, a dialog informs about an external change. The user than can choose to keep his version or reload the file from disk. This then toggles the default "revert to saved" mechanism from NSDocument resulting in an awkward dialog for the user if there are unsaved changes as it states "Do you want to revert" which is a bit odd in this context but I did not want to reimplement all the already existing behaviour. When syncing is woking, there are other options already discussed here.

@miscreanttoucan 
> 1. Save the database onChange
Worth a setting (default to off), Keepass triggers might allow for something like this as well, but I have no plan to implement triggers. Might be useful as an plugin extension point
> 2. When locking the DB, close out of it, so that when you sign back in, it's the same as opening the DB. (This way, if the DB file has changed, you'll be opening the latest version.)
Done in dd1322e224e0a44cbec20b32ac15b69f96bda86c

**Comment by mstarke** [comment]
I'm closing this since the feature is present. Bugs and enhancements should be reported in separate issues.

**Comment by ungeruehrt** [comment]
That’s a nice feature, how can I get it? MacPass doesn’t offer any updates to me and in the download section 0.5.1 is still the most recent version of MacPass as far as I can see.

**Comment by mstarke** [comment]
Only present in current master, so you have to build your own version.
