### ISSUE TITLE
keyboard shortcuts enhancement

### ISSUE THREAD

**Issue by kevinn** [mstarke/MacPass#301]
Enchancement request.

KeepassX uses cmd-b and cmd-c keyboard shortcuts to copy username or password attributes, can we allow to assign these as well?

**Comment by mstarke** [comment]
If you think about opening an issue, please take the time to look for duplicates. I get that you do not know the project like I do, but this one was a bit too ease since a search for shortcuts comes up with a nice list all pointing to #171

Duplicate, hence closed.
