### ISSUE TITLE
KepassHTTP Support disabled?

### ISSUE THREAD

**Issue by chuenniger** [mstarke/MacPass#307]
Hi,

First: nice work :)

I've a question for the KepassHTTP support. How can I activate this feature? The setting is disabled in settings menu (see screen).

![bildschirmfoto 2015-01-21 um 12 41 09](https://cloud.githubusercontent.com/assets/188438/5835590/cd53e980-a16a-11e4-9490-78332512ea0c.png)

My Macpass Version: Version 0.5.1 (2556)

Regards,
Christian

**Comment by mstarke** [comment]
If you take a look at the [0.5 release notes](https://github.com/mstarke/MacPass/releases/tag/0.5-alpha), you'll see that Keepass HTTP is not enabled. You can use @jamesrhurst  branch to try it.

**Comment by chuenniger** [comment]
I'm wating for version0.6
Thank you.
