### ISSUE TITLE
Global Autotype by URL

### ISSUE THREAD

**Issue by chuenniger** [mstarke/MacPass#308]
Hi,

I think that the global AutoType feature use the site name to auto complete but Keepass uses the URL. Thins makes more sense.

What do you think? Can I change this in some settings?

Regards,
Christian

**Comment by mstarke** [comment]
Keepass does not use the URL as main lookup, but can be configured to do so. Currently only the title is used, but there's been work done to change this to the way Keepass does it. Will be included in an upcoming release. Might even be in a 0.5.x release.

**Comment by kumters** [comment]
Original windows Keepass use "WINDOW NAME" not URL:) And MacPas is doing
the same... It's critical for me, I use it for many application, which
doesn't have URL at all:)

On Wed, Jan 21, 2015 at 12:44 PM, Christian Hünniger <
notifications@github.com> wrote:

> Hi,
>
> I think that the global AutoType feature use the site name to auto
> complete but Keepass uses the URL. Thins makes more sense.
>
> What do you think? Can I change this in some settings?
>
> Regards,
> Christian
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mstarke/MacPass/issues/308>.
>



-- 

Peter Jankovsky

+420-724-952661@phone
347696680@icq
tifay78@skype
social: about.me/kumters

**Comment by chuenniger** [comment]
Okay,

you're right. I mistook that with the KeeHTTP feature, sorry :)

Thank you for your fast reply.

![image](https://cloud.githubusercontent.com/assets/188438/5836505/077ec75e-a177-11e4-96c5-8a135574c38d.png)
