### ISSUE TITLE
2 Screens - but no MacPass

### ISSUE THREAD

**Issue by ochorocho** [mstarke/MacPass#311]
Hey,

I'm running MacOS Yosemite (10.10). All in all MacPass works just fine. :-)
After a Shutdown 10.10 tries to open all Programms run on the last Session. MacPass opens as well but is not show its window.

Things i try to get around this:
- Open the kdb File from Menu: File -> Recent documents DIDN'T WORK
- Close MacPass and reopen it (multiple times) WORKED

Thanks for creating MacPass!

Cheers,
ochorocho

**Comment by benniv** [comment]
Hi, I'm experiencing the same issue (also running Mac OS 10.10).

The main MacPass window isn't visible. I tried closing and opening the application several times, deleting preference files and restarting to no avail.

I use MacPass every day, thanks a lot!

**Comment by ochorocho** [comment]
is your database on a network mount?

**Comment by bvehse** [comment]
No, it's on my local drive - but synced via Dropbox.

**Comment by ochorocho** [comment]
my guess was, that sometimes the connection to the mount could cause issues. But that seems not to be the case here. ...

**Comment by mstarke** [comment]
Since I'm still on the dark side (read 10.9) and should be upgrading soon to 10.10 I'll take the time to investigate once my system is running on the bleeding edge.

**Comment by ozzi-** [comment]
Im using 10.12.6 (16G1036), MacPass Version 0.7 (20171024171012-continuous) and two screens.  Rebooting shows MacPass fine. I think this can be closed.

**Comment by mstarke** [comment]
I've never encountered the issue neither on 10.10 nor on 10.11 or 10.12 so I think it's save to close the issue.
