### ISSUE TITLE
[Feature Request] Allow for customising sidebar font-size

### ISSUE THREAD

**Issue by teddypickerfromul** [mstarke/MacPass#315]
Some text labels (entries) maybe be bigger than sidebar width 

![image](https://cloud.githubusercontent.com/assets/750463/6223662/cfc1877a-b67f-11e4-83ec-953ae8a098b2.png)

**Comment by mstarke** [comment]
How about resizing the sidebar to fit the labels? As I said on other occasions, I'm a real fan of let the app look like the system wants it to, hence I'd like to keep all visuals as close to the OS as possible. What might be nice is a setting to hide the icons, but changing the font, not gonna happen (at least not for a long time)
