### ISSUE TITLE
[Feature Request] Merge/compare save conflicts of password database

### ISSUE THREAD

**Issue by rfilmyer** [mstarke/MacPass#317]
Not sure if this is possible cryptographically, but I'd like a way to resolve conflicts of a password database when saving- I have my database on Google Drive and accidentally made a change from another device without having MacPass save first, and I'd like a way to evaluate those changes.

**Comment by mstarke** [comment]
That's the currently missing synch feature. It's on the todo list. But don't ask me when it's done ;).

**Comment by mstarke** [comment]
Duplicate of #83
