### ISSUE TITLE
Shortcuts for copying password and username

### ISSUE THREAD

**Issue by gjuric** [mstarke/MacPass#323]
Is there a chance to make this configurable or at least change them to two (instead of three) key combination?

The current solution is IMHO clumsy...

**Comment by DominusExult** [comment]
This can be changed via OS X' shortcut settings.

**Comment by gjuric** [comment]
Could you elaborate on that?

**Comment by gjuric** [comment]
I saw that, but have you tried it?

This doesn't work for me and I am guessing that is because those two options are not available in the main apps menu, only in the contextual menu.

**Comment by DominusExult** [comment]
Did you follow step 6 of the instructions? Quit and restart the app...
I think I had this working once. There is an older, closed issue about this.
Please read closed issues as well.

Dom

**Comment by gjuric** [comment]
You are right!

Sorry for wasting your time..

**Comment by gjuric** [comment]
Just an update if anybody is trying to do the same, the original page on apple.com is now gone, but it can be viewed here: https://web.archive.org/web/20180105044227/https://support.apple.com/kb/PH13916?locale=en_US
