### ISSUE TITLE
Remember and populate the last key used to unlock

### ISSUE THREAD

**Issue by gr8tushar** [mstarke/MacPass#328]
The software locks up frequently. When using a key file, once has to select the file again and again. Ideally it should show the file pre populated on the unlock screen as it does in KeyPass for Windows.

**Comment by DominusExult** [comment]
There is a setting for that AFAIK

**Comment by DominusExult** [comment]
Also I think it would be very useful for mstarke if you can lay out some steps to reproduce your frequent lockups.

**Comment by mstarke** [comment]
@gr8tushar Just a guess, but do you mean the database gets locked or the software crashes?
If you do not want the database to lock automatically, you can disable all those in the settings. But I highly discourage this - at least leave the "lock on sleep" option on.

Propopluation for keys is, as @DominusExult pointed out already there, you need to enable the feature but be aware of the consequences. You then have a mapping of kdb file to keyfile in your settings. Anyone able to look those files can get those mappings.

**Comment by gr8tushar** [comment]
Hi,
I tried that but it doesn't work. 
Steps to reproduce.
1. Open MacPass and use a key file to unlock the database. 
2. Go to preferences and choose to remember the key file.
3. Lock the database from the File Menu.
4. The key file is not pre-selected in the lock screen.

Please let me know in case you need more information or correct me if I am missing out something.

**Comment by mstarke** [comment]
If you swap 1. and 2. it should work. You have to unlock the database to store the keyfile. MacPass does not keep the keyfile and password it just loads the data and generates the key internally and has no record where the created data came from (neither the plain password nor the keyfile contents is remembered)

A side note: The keyfile will not be stored if you do not have a password set, that is, if the keyfile is enough to unlock the database!

**Comment by gr8tushar** [comment]
@mstarke hmmm... May be I didn't explain it well. My bad ;).
Basically I have a database and a key file to unlock it. Both of them reside in the same folder. 
When I open the kbdx file, it asks me for pwd or a file. I choose a file to unlock it. 
Now when the database gets locked (due to inactivity or any other event), it again asks me for a pwd or a key file. That time I have to choose the file again. 
What I wanted is that the key file which I used to open the database, should come as pre-populated and I just have to press the unlock button.

P.S. In the preferences, I have checked the option to save the key file.

**Comment by mstarke** [comment]
@gr8tushar that's exactly how it came across. If the preferences is set and your database has a password and a keyfile the keyfile should be selected already. If not, then this is a bug.

As a side note - having the key file at the same location the database is at is useless. You do not gain any security with that, as anyone able to obtain the database get the key as well so your database is only as secure as your key file. A better scenario would be to store the key file on a thumb drive and only there.

**Comment by gr8tushar** [comment]
@mstarke I just have a key file and no password for a db. If that is the case, I think it might be a bug.

Thanks for suggestion. I know that I am misusing it ;). For now I am only using it as a repository. I save the database and the key on cloud so that I have all the pwds available on all my systems.
Need to update that. But anyway, thanks a ton for your advise.

**Comment by mstarke** [comment]
I'm not going to add the ability to store key files without a password so I'm regarding this issue as resolved.

**Comment by FrankKooij** [comment]
Thank you all for developing the best open source password manager for OS X. I would like to second gr8tushar comment of Apr 7, 2015. Unfortunately it is not quite clear to me whether this is considered to be an issue that needs to be fixed. In my opinion MacPass should remember the location (not the contents) of the key file and pre-populate the location field when one uses both a password and a key file and is trying to open a database (at least when it is on the recent files list). Having to search for a key file every time one logs in in addition to already having enter a password, will put many people off and may make the key file a somewhat useless feature. Could you please have another look at this issue? Thanks.

**Comment by mstarke** [comment]
@FrankKooij your use case should already work. If you enable "Remember Key Files" MacPass will – as you suggested – remember the location **not** the contents of a key file for a specific database. The mapping uses the file location so if you move the database, the mapping is not correct anymore. The mapping is updated every time you successfully unlock a database with a password and key file.

![screen shot 2016-02-04 at 17 36 19](https://cloud.githubusercontent.com/assets/58428/12822016/3e5c3d5a-cb66-11e5-8a03-68dc8b9aa6b6.png)

You can take a look at your current mappings

````
defaults read com.hicknhacksoftware.MacPass RememeberdKeysForDatabases
{
    "/path/to/database/Untitled.kdbx" = "/path/to/keyfile/Untitled.key";
}
````

This is obviously a security risk. A possible improvement is to hash the file url for the database

**Comment by FrankKooij** [comment]
Dear Michael, thanks for looking into this issue. I tried that checkbox multiple times before submitting my comment, but it did not work for me then. It is now, however. My key file is stored on a NAS. Might that have anything to do with it? (The NAS share was mounted every time that I tried this.)
