### ISSUE TITLE
Hide menu bar icon

### ISSUE THREAD

**Issue by flecmart** [mstarke/MacPass#331]
Hi,

is there a possibility to hide the menu bar icon? I identified an icon in my menu bar as MacPass... I wondered for a couple of weeks where the icon comes from and why it is there (it has no function). Not really a problem, but it is somewhat disturbing. I built the keepasshttp fork of MacPass. Everything is working fine so far - thanks :-)

**Comment by mstarke** [comment]
That's the indicator that the keepassHTTP Plugin is active. There's a settings key but no UI for it. Someone expected such a wish, I guess :P. I've not put any work into it as I wanted to get other stuff done fist, which takes longer than expected :(

Try to run the following in your Terminal:

    defaults write com.hicknhacksoftware.MacPass ShowMenuItem -bool NO

**Comment by flecmart** [comment]
Thank's for the quick response - that did the trick (after a restart of MacPass) :-)
