### ISSUE TITLE
Changes not saved

### ISSUE THREAD

**Issue by mankoff** [mstarke/MacPass#335]
MacPass doesn't save changes in the following scenario:

1) Make a change
2) Wait until timeout auto-lock occurs
3) Try to quit. You are warned that there are unsaved changes.
4) Enter password to access un-locked DB
5) CMD+S to save changes
6) Quit
7) Re-open - changes are not there.

**Comment by fabwa** [comment]
I found a related issue with changes in Notes of existing key are not being saved...
New Key: Add some Notes (Note window on the right) - save - close DB - reopen DB - open key - change/ add notes - save DB - close DB - reopen DB... no changes saved

**Comment by fiery-** [comment]
This bug also occurs when you create/change a Custom field, then click on General panel and Save. When you restart MacPass, no Custom fields exist (changes applied) for this item. It seems that save operation doesn't work when you move the focus from the current item panel. Very serious bug.

**Comment by mstarke** [comment]
I did investigate this and need to convert using object controllers on binding to adhere to the NSEditor protocol since this is respected by the NSDocument save operation (it flushes all changes before a save)

**Comment by mstarke** [comment]
The main edit sheet works now correctly. Also the database is saved once locked so nothing.
