### ISSUE TITLE
Make Window Associations editable

### ISSUE THREAD

**Issue by ibutra** [mstarke/MacPass#336]
I found this #272 Issue which seems to be the same but I still can't find a way to edit window associations in MacPass.
It also seems like the window associations are not considered for autotype.

**Comment by mstarke** [comment]
The current release ignored window associations completely. But it's already working in the current master.

**Comment by thy1985** [comment]
Stupid question probably but: I did clone the current master. When I compile & run it the window associations in the "auto type" tab are still grayed out.  ( 0.5.1 2557)

btw,
That is just cosmetical but the overlay info when it tries to match an entry looks like the Text is just a placeholder. Does that mean the translation is not complete? Same for PERFORM_AUTOTYPE_FOR_ENTRY in the actions menu dropdown.
