### ISSUE TITLE
Redundant sidebar hierarchy

### ISSUE THREAD

**Issue by yusf** [mstarke/MacPass#339]
![skarmavbild 2015-05-10 kl 12 34 43](https://cloud.githubusercontent.com/assets/346211/7553936/11991fec-f711-11e4-825a-30f34d911ab2.png)

Is there a logic reason why root folder "Database" sits in header "Database"?

**Comment by auge** [comment]
You can rename it and give it a different name - e.g. mine is called "Main" (although created with Keepass)

**Comment by yusf** [comment]
I use KeePassX as well. No such option is offered in that app. Which one of the apps would be sidelining the KeePass "standard"?

**Comment by mstarke** [comment]
The group is a mirror of the database name. The root folder is a simple group. KeePass has a single root for the group tree. The kdb format did have an invisible unsaved root group and implicitly created it every time. Kdbx doesn't hide it anymore. So it's by design. You can freely rename them.

**Comment by yusf** [comment]
Right then! Using kdb still.
