### ISSUE TITLE
Multiple Select

### ISSUE THREAD

**Issue by edm00se** [mstarke/MacPass#340]
Feature request: multiple select, for assigning entries to categories, for instance.

**Comment by Nes-si** [comment]
+1.
Also for deleting and other actions.
Please!

**Comment by mstarke** [comment]
I've got multiselction for simple dragging/deleting/etc. working. Since multi-editing is a bit more work I'll might skip this in the first run!

**Comment by mstarke** [comment]
Duplicate of #285
