### ISSUE TITLE
Changing Key encryption rounds breaks database (KeePassX compatibility)

### ISSUE THREAD

**Issue by moogle19** [mstarke/MacPass#341]
Reproduce:
1. Create new database in KeepassX (2.0a6)
2. Open database in Macpass (0.5.1)
3. File -> Database settings -> Security -> Key encryption rounds -> Benchmark = 13859967 rounds
4. Try to open in KeepassX, error:
```
Unable to open the database.
Invalid uuid value
```

**Comment by setumiami** [comment]
I got the same issue. There's a workaround:

1) Reopen database with MacPass
2) Change an existing entry (e.g. I added a white space to the name)
3) Save the database
4) Reopen database with KeepassX and it will work.

**Comment by mstarke** [comment]
I can reproduce the bug but a nice little something is that Keepass2 does not complain and opens the database without any problems. This might even be a KeepassX bug.

**Comment by debfx** [comment]
The KeePassX parser trips over <RecycleBinUUID/> and <EntryTemplatesGroup/> as it expects an actual uuid there.

I'll fix this to allow empty uuids. Strict parsing mode is disabled in current master so this won't be an issue anyway.

So not a MacPass bug, but I'm curious why it adds those elements in this case but not in others.

**Comment by mstarke** [comment]
Since this was a problem on another occasion I did suspect this. I have no setup to debug KeepassX yet so wasn't able to locate the exact spot. Can you point me to the empty uuid filed that KeepassX trips over?

**Comment by debfx** [comment]
RecycleBinUUID and EntryTemplatesGroup.

**Comment by mstarke** [comment]
Fixed in master
