### ISSUE TITLE
After save kdbx, DB korrupted for Linux users.

### ISSUE THREAD

**Issue by ochorocho** [mstarke/MacPass#346]
Hey,

i'm using MacPass Version 0.5.1 (2557).
When i saved the Database today, i wasnt able to open the database on a Ubuntu 12.04 nor on 14.04.

I tried saving kdbx using MacPass again as well as i tried to export the Database.
No dice, the DB was still korrupted.

To fix the issue, i used Windows version of Keepass an saved the DB. Everything works as expected now.

But when MacPass is used to save the DB the file is korrupted for Linux users it seem.

Thanks for creating MacPass ...

**Comment by mstarke** [comment]
That's a hard bug to track down without any specific information. Can you narrow it down by cleaing the database step by step? This way sometimes the affected entry/group can be identified.

**Comment by ochorocho** [comment]
i can't narrow it down (not allowed to do it at work and can't take this DB back home). Sorry. :-(
I will watch out for the next time when i bump into this to provide more specific information.

Thanks!

**Comment by mstarke** [comment]
Thanks!
