### ISSUE TITLE
Plugin system

### ISSUE THREAD

**Issue by nazriel** [mstarke/MacPass#350]
Currently (correct me if I'm wrong) all feature requests etc goes directly to the core of the application.

It has some downsides:
- development must be done around mstarke (see for example PR for HTTP support) 
- at some point in time, code will start to grow and it will be harder to maintain it

Plugin system has advantages:
- it is easier for 3rd party folks to jump in and propose functionality in form of opt-in plugin
- plugins are  flexible. If user enjoys feature introduced in plugin - he uses it, otherwise picks other implementation or just doesn't use it at all.
- it could also help introducing new functionalities as it probably could help in porting existing Keepass plugins to MacPass.
- easier switch to swift? New plugins could be created in swift

What do you think guys?

**Comment by mstarke** [comment]
I'm with you on this. I thought about a plugin system at the beginning but since this is my first real Cocoa/Mac Project I wanted to get it up and running first to see if it's possible.

If plugins should be made possible there needs to be a well defined API. Plugins might make added more key provider (Twofish, etc) easier too so this is a very good approach.

If you're willing to takle some of the task at hand feel free to dig in and make suggestions. As the work of @jameshurst has shown, I'm very happy for every help on the "core" application I can get even more so with the current small amount of time I can shed free to spent on MacPass.

**Comment by nazriel** [comment]
@mstarke sure, I will try to dig into.

Probably will be good occasion to get my hands "dirty" with Objective-C and/or Swift as I had no chance before to program in those 2.

I will try to do some research about plugin systems in other application like this one and see how it is done there.

**Comment by mstarke** [comment]
Regarding Swift - If we get to a plugin system then that's the best spot to use it as I'm not really into trying to convert my exiting codebase to Swift.

A nice start for plugin architecture is [Apple's Guide on Plug-in Architectures](https://developer.apple.com/library/mac/documentation/Cocoa/Conceptual/LoadingCode/Concepts/Plugins.html)

**Comment by mstarke** [comment]
I've just skimmed through the guide. It's actually not that hard.

What I got in mind:
* flesh out Notifications/Protocolls for what MacPass and KeePassKit is doing (e.g. willCreateEntry, didCreateEntry, willAddGroup, didAddGroup, willMoveGroup, didMoveGroup, you name it)
* support custom Settings Tabs
* support custom KeyProvider

The longer I think about it this might actually be quite simple iff we're not too hard on the APIs stability at first. The simple solution is just protocols and notifications all over the place. What concerns me a bit is that a plugin can wreck havoc on the database if it is allowed to have write access on the data.

**Comment by mstarke** [comment]
Another noteworthy thing:

Should there be an easy way for users to find and install plugins? Like a central web-hub? A interface in MacPass that discovers plugins? A plugin settings to add/remove them? Or just use archaic techniques like copying stuff to a specific location in the filesystem?! Drag'n'Drop plugin installation?

**Comment by nazriel** [comment]
@mstarke I think it's ok to experiment with API at the begging - but it has to be stated explicitly that API isn't set in stone yet. So probably no worries on this ground.

About plugin HAVOC...
I think if we go with "Central Hub" route for plugins base, we probably could introduce some review process and accept plugins that seem to be safe.

So in overall:
Users may install whatever plugins they want, but if they want to be sure that they are tested and safe they should only stick to plugins registered at the plugin HUB.

So probably:

Central HUB as web service with WEB frontend that will be browseable + API that could be fetched from GUI form in application itself, providing easy way to install plugins in fast manner without firing up Browser.

What you think?

Thanks for the link, I will look into this today.

**Comment by KFDCompiled** [comment]
Transferring the [conversation from issue #90](https://github.com/mstarke/MacPass/issues/90) to here:

>i think there should be plugins both for MacPass as well as for KeePassKit, as there needs to be support on the data side but also on the GUI front end. That arises the problem of dependencies on plugins. e.g if we need additional inputs on the password screen that's a MacPass plugin but the KeePassKit has to handle the data provided by the additional inputs. Maybe I should just scrap the separation of KeePassKit and integrate it into MacPass but that removes the possibility for others to use the framework just to be able to parse stuff.

Sharing your sentiments, I think the question becomes one of priorities at this point of development. Which of the following two options is more important and/or desireable at this stage: first, sacrifice plugin functionality for the functionality of an Xcode KeePass framework (which is a massive contribution—thank you again); or, second, sacrifice the Xcode framework to facilitate plugin functionality.

I'm of the opinion that the second option, a plugin architecture, is more desireable.

**Comment by mstarke** [comment]
Well. I did start creating a simple plugin system. My current solution is working but rather fragile. There's a base plugin class for MacPass and any bundle using this class inside the application support folder gets loaded. There's a setting to enable code sing checks to only load signed bundles but nothing more. The bundle can link to anything inside of MacPass and hence can potentially break everything 😉. I'm currently trying to port the  KeePassHTTP fork over to work as a plugin.

**Comment by mstarke** [comment]
Pushed to master. It's actually nothing more than a bundle loader. You can cause havoc across MacPass but it's a start.

**Comment by kdoteu** [comment]
Time for a release? Loving to see the new possibilities :+1: :smiley:

**Comment by mstarke** [comment]
With 0.6.x there's a release supporting plugins! But be aware that the current system is highly fragile!
