### ISSUE TITLE
KeePassHTTP and multiple key files

### ISSUE THREAD

**Issue by Floppy** [mstarke/MacPass#351]
This is one for @jameshurst I guess, as KeePassHTTP isn't in the master version yet:

I've found that clients can get a little confused when you're working with multiple keepass files at once; only one of them is available over keepasshttp, and it seems to sometimes swap between them, though I'm not sure why. I wouldn't say it's a blocker though, but some way of selecting which file is active for keepasshttp would be useful, maybe, and might at least make it more predictable. Difficult to explain more without knowing the internals; does that make any sense though?

**Comment by mstarke** [comment]
KeepassHTTP seems a bit strange to me as well. We might try to move this over to the plugin [MacPassHTTP](https://github.com/MacPass/MacPassHTTP)
