### ISSUE TITLE
MacPass not opening when DB is remembered but missing

### ISSUE THREAD

**Issue by sub0ne** [mstarke/MacPass#352]
If the option to remember the last opened DB is set in the settings and the database file is missing (e.g. deleted) no window opens and no message appears.

Anyway you can still enter the settings and uncheck the necessary setting, quit MacPass and restart. But that's not very userfriendly.

@mstarke: I forked the latest master and try to fix this :-) good work in MacPass btw.!

**Comment by mstarke** [comment]
Good catch, waiting for you pull request :)

**Comment by mstarke** [comment]
fixed in a26c7006069c6a9c0967a8b3d2d98a076c3b3423
