### ISSUE TITLE
Password generation allowed character selection improvement

### ISSUE THREAD

**Issue by mariosangiorgio** [mstarke/MacPass#355]
I tried to generate a password for a website that allows alphanumeric characters and only certain symbols.

The current UI allows only to toggle between the preset groups (uppercase characters, lowercase characters, symbols) or to add a custom string.

Unfortunately, setting up the custom string is not very user friendly because from what I can see in the source code `customCharactersTextField` is a simple `NSTextField`.

I can think of two possible improvements:
 * make it possible to add a custom string in addition to the already existing characters set. In my case I would have chosen `A-Z`, `a-z`, `0-9` and added the custom symbols string. I think this would be the best solution;
 * have a smarter custom string which allows some special characters to represent character groups. I'm thinking of something like `[A-Z][a-z][0-9]!@#$`.

Is there any opinion on this?

**Comment by mstarke** [comment]
Solution one is fairly easy, the second one needs custom parsing. If you're up to it, just implement version one and open a pull request, it's definitely an enhancement.

**Comment by mariosangiorgio** [comment]
Right now I'm on holiday, when I get home and I have some time to spend on implementing the new feature I'm going to do it and open a pull request

**Comment by mstarke** [comment]
It's merged, should we close the issue or keep it around if anyone wants to do the parser stuff? ;-)

**Comment by mariosangiorgio** [comment]
I think we can close. Getting the other approach work in an user friendly way could be complex. I think there is the risk of making the user interface confusing

**Comment by mstarke** [comment]
I fully agree with you. Keepass and thus MacPass already have (sometimes I think) too much features and keeping things simpler is a good thing. What I though about while reading your commit is changing the whole password generation to use NSCharacterSet instead of NSString. Something like this:

https://github.com/acoomans/Populate/blob/5afca6ff252a19f6a4144933ac60ae1fd99b88d7/PopulateKit/DataSets/Name/NSString%2BRandomized.m

**Comment by mariosangiorgio** [comment]
That sounds like a good idea. Unfortunately I am not an ObjectiveC expert so all my coding in this language is not too idiomatic and I don't know many useful classes
