### ISSUE TITLE
Missing file

### ISSUE THREAD

**Issue by rdoering** [mstarke/MacPass#360]
I tried to compile commit 77a7b536fdde636650a4f16c03e614d4e1298281 per xcode and got  this error.

Error Msg:
clang: error: no such file or directory: '/Volumes/HD/Downloads/MacPass/HNHUi/HNHTextView.m'
clang: error: no input files

**Comment by mstarke** [comment]
Did you init/update all the submodules?

77a7b53 refers to mstarke/HNHUI@108f4519a573c26610f7b7f69e72e4405ee420bd
and that commit certainly contains the ````HNHTextView.m````:
https://github.com/mstarke/HNHUi/blob/108f4519a573c26610f7b7f69e72e4405ee420bd/HNHTextView.m

**Comment by rdoering** [comment]
My fault.

Thanks
