### ISSUE TITLE
Saving a never saved before document by quitting MacPass results in an error

### ISSUE THREAD

**Issue by tibor** [mstarke/MacPass#361]
If you’ve never saved your file before and want to quit MacPass, it asks you, if you want to save the file, but doesn’t asks for a password or password file. Since a password or password file is required to save a document, this results in an error: “The document "Untitled" could not be saved as "Untitled"”.

**Comment by mstarke** [comment]
Good catch! The MPDocumentWindowController handeles the password settings but if one closes the app, the message gets send directly to the document that just tries to save itself and fails. Need to move this code to the document then.

**Comment by mstarke** [comment]
Fixed in current master since autosave on first change request eh user to enter a password
