### ISSUE TITLE
Reload Database

### ISSUE THREAD

**Issue by ungeruehrt** [mstarke/MacPass#362]
I noticed that you’re working on a sync feature (#83).

However, if this feature will take some time, it would be nice to see a simple manual sync/reload function added to MacPass. At the moment you have to close the database and open it again to get the most recent version with all changes if you use MacPass on different devices.

**Comment by mstarke** [comment]
Working is a bit overstated - it's a item that needs to be done to get a full features app :)
Also this goes right along the lines of #300
