### ISSUE TITLE
Cancelling expiration dialog locks database

### ISSUE THREAD

**Issue by nicdumz** [mstarke/MacPass#367]
Version 0.5.1 (2556)

* Select an entry
* Click the gear next to expiration settings
* Click Cancel
-> Database is now locked

This is a bit surprising :smile: . I would expect cancel to just close the dialog.

Generally speaking, "Use preset" is greyed out / impossible to use, but fixing the "lock me out" part seems more important.

Thanks!

**Comment by mstarke** [comment]
Duplicate of #277.

**Comment by mstarke** [comment]
That reminds me. I wanted to release a binary ;)
