### ISSUE TITLE
Make default copy shortcut copy the password

### ISSUE THREAD

**Issue by Floppy** [mstarke/MacPass#368]
Copying a password is the single most common thing I need to do in the actual MacPass app; can the default cmd-C copy shortcut be used to copy instead of the variant (which in my case conflicts with Alfred's clipboard history commands).

**Comment by mariosangiorgio** [comment]
I second this. It would be a good idea

**Comment by mstarke** [comment]
Please try to search for an already reported issue before opening a new one.

Duplicate of #171, #252 and #301

**Comment by Floppy** [comment]
Apologies; I did search, but didn't hit the right keywords to find those ones somehow. I know how annoying is it, sorry about that :)

**Comment by Floppy** [comment]
Ah, I guess I was searching for open issues rather than ones that were already closed.

**Comment by mstarke** [comment]
No worries. I did get annoyed at some point but that's just stupid. I see all activity others don't and I'm happy for every feedback.
