### ISSUE TITLE
Close the database on sleep

### ISSUE THREAD

**Issue by jjohns63** [mstarke/MacPass#371]
The option to lock after sleep effectively locks the workspace but does not actually reload the file when next unlocked.
I use Dropbox to keep my database in sync across multiple systems. If the database changes, Dropbox downloads the new database, but MacPass never opens the newly updated file. The behavior I'd expect, based on Windows, is that when the workspace is next unlocked, the database is reloaded from disk.

**Comment by mstarke** [comment]
Save on lock and reload on unlock/file change is a valid feature and will - actually has to - be implemented.
