### ISSUE TITLE
no more auto update ?

### ISSUE THREAD

**Issue by gotson** [mstarke/MacPass#373]
The auto-update feature left me with version 0.5.1 from December 2014.
What's the good way to auto-update ?

**Comment by DominusExult** [comment]
The auto update is working fine, there just wasn't a new release ;)
Manually you can grab the latest source and compile it via xcode...

**Comment by mstarke** [comment]
It'll happen. Eventually ;)

**Comment by philipgiuliani** [comment]
Still no new release for more than a year :( Would love to have this improvements. At least as a beta :(
