### ISSUE TITLE
Build failed, OSX 10.11, Xcode 7.0.1

### ISSUE THREAD

**Issue by tcgoetz** [mstarke/MacPass#378]
First attempt at building MacPass.

/Users/tgoetz/Projects/MacPass/KeePassKit/Core/KPKEntry.m:618:21: Property 'key' not found on object of type 'KPKBinary *'

Changing key to name fixed the issue.

**Comment by mstarke** [comment]
Known issue, fixed in KeePassKit but MacPass doesn't use the fixed version. I'm making good progress on MacPass' editing/history support which should compile fine. This is a rather old and nasty bug by the way :)

**Comment by evildragonCD** [comment]
Hi,
i hav show what stand in KeePassKit github.
Change MacPass/KeePassKit/Core/KPKEntry.m line 618

size += [binary.key length];

to

size += [binary.name length];

and i can build ;)

**Comment by EvilDragonSW** [comment]
Hi,
i hav show what stand in KeePassKit github.
Change MacPass/KeePassKit/Core/KPKEntry.m line 618

size += [binary.key length];

to

size += [binary.name length];

and i can build ;)

**Comment by flinz** [comment]
@EvilDragonSW Can confirm, this works as a workaround.

**Comment by EvilDragonSW** [comment]
Please please ;)

**Comment by mstarke** [comment]
Current master works again but it's feature-robbed of undo until it's all sorted out. This is currently in a very unstable state but it compile again - at last! :)
