### ISSUE TITLE
Idle and sleep timeout are broken in the head of the tree

### ISSUE THREAD

**Issue by tcgoetz** [mstarke/MacPass#379]
I'm running a MacPass built from the head of the tree and idle and sleep timeout don't work. Manual locking (hotkey) does work.

**Comment by mkubenka** [comment]
+1

**Comment by mstarke** [comment]
Will take a look, might be due to some refactoring. The UI stuff isn't tested all the time ;)

**Comment by tcgoetz** [comment]
Updated to latest. Works for me.

Thanks for the quick response!

**Comment by mstarke** [comment]
I have to keep the image of actually doing something by fixing those minor bugs 8)
