### ISSUE TITLE
Global Autotype - How Window associations & Window title works ?

### ISSUE THREAD

**Issue by FromBabylon** [mstarke/MacPass#380]
While Global Autotype seems to be working well, I'm having some troubles to understand how window associations & window title works. 
If I select "+" on window association I can only add 'DEFAULT_WINDOW_TITLE'. What is that ? 
There is a drop down menu for window title but I can only write one window title. Is that on purpose ? 

Thanks

**Comment by mstarke** [comment]
You can read about them in the original Keepass documentation. But in 0.5.1 they aren't used and the UI to edit them is broken. The master should be using them correctly.
