### ISSUE TITLE
Linked UID & PWD don't work

### ISSUE THREAD

**Issue by mbrucco** [mstarke/MacPass#383]
If you copy password or useraname from a DB entry that has UserName and/or Passwork as a link to another db entry, app copy link and not linked value

Es. 
DB_ID_Entry:  D3D4F50A78E2DF47986669064FAAD271
Title:                MyTitleTestOrig
Username:     TestUID
Password:      TestPWD

DB_ID_Entry:  Any
Title:                MyTitleTest
Username:      {REF:U@I:D3D4F50A78E2DF47986669064FAAD271}
Password:       {REF:P@I:D3D4F50A78E2DF47986669064FAAD271}

If I copy Username from "MyTitleTestOrig" entry I have in clipboard "TestUID", but if I copy from "MyTitleTest" I expect to have in clipboard "TestUID" but I have "{REF:U@I:D3D4F50A78E2DF47986669064FAAD271}". 

Possible solution: If coping string start with "{REF:" and finish with "}", call a function that retrieve Username if it start with "{REF:U" or retrieve password if it start with "{REF:P".

**Comment by mstarke** [comment]
Resolving works in master but not everything is working in the 0.5.1 release. I'm getting there to release a new built.
