### ISSUE TITLE
Submodules recursive init: DDXMLDocument.h missing

### ISSUE THREAD

**Issue by flinz** [mstarke/MacPass#386]
I just tried to build the recent version, and was running into trouble with missing dependencies, in this case the ``KissXML`` dependency in ``KeePassKit``was not initialized, and thus the header ``DDXMLDocument.h`` was not found.

This can be fixed by calling
```git submodule update --init --recursive```
instead of the simple update.

I'm just archiving this issue in case anybody runs into it. Will open a PR with correction to documentation.

**Comment by mstarke** [comment]
Thx!

**Comment by mstarke** [comment]
Since I had good results using Carhage I'll try to move MacPass over tu use the built Frameworks instead of having to include all the projects as submodules.

**Comment by flinz** [comment]
Yeah, that makes sense - just trying out the MacPassHTTP plugin (using carthage) and it looks good.
