### ISSUE TITLE
fatal error: 'KeePassKit/KeePassKit.h' file not found

### ISSUE THREAD

**Issue by dehnhardt** [mstarke/MacPass#391]
On a fresh git clone, when compiling I always get the error
fatal error: 'KeePassKit/KeePassKit.h' file not found

Looks like there is something reorganised in the source tree?

Thanks Holger

**Comment by mstarke** [comment]
Did you install all dependencies with Carthage?

**Comment by dehnhardt** [comment]
I did, but something was wrong. I reinstalled Carthage and dependencies again and now everything seems to be there.
Thanks for your help!

Holger
