### ISSUE TITLE
Perform autotype (from context menu not global) behaviour?

### ISSUE THREAD

**Issue by rmey** [mstarke/MacPass#396]
Hello,
I build latest version from master. The Autotype from the context menu of an entry works in Keepass versions on Linux/Windows in that way, that Keepass minimizes its the window, so that Username/Passwort is entered in the window behind the Keepass, very practical when global autotype is not feasable. In MacPass the window does not minimize and the input goes nowhere. Only global autotype works. How is this supposed to run in Macpass? I open an editor activate Macpass choose an entry -> context menu autotype and nothing happens. Also the shortcut does not work ctrl + cmd + a. Is there a trick for that functionality? Global autotype is working in my case.

**Comment by mstarke** [comment]
Autotype is performed on the last window activated before you activated switched to MacPass

MacPass then activated the last window that was front-most before you switched to MacPass (no minimise, etc) and performed the Autotype.

Example for a Website:
Go to a website, put cursor in input field for username, got to MacPass, select entry to use, select context menu "Perform Autotype". Should work. If not, it's a bug :)

**Comment by rmey** [comment]
Thanks. I have Yosemite. I open editor or browser set cursor activate MacPass select entry autoytpe nothing happens so its a bug as you said.

**Comment by rmey** [comment]
With the latest version I completely rebuild today it's working, thank you very much.
