### ISSUE TITLE
Build issues (Sparkle 1.12.0b1)

### ISSUE THREAD

**Issue by thy1985** [mstarke/MacPass#398]
Hi 
 Just fyi - it is currently not possible to build master (I skipped the two build phases that link fr_CA to fr and the pt linking for now) due to errors during Sparkle 1.12.0b1 build (carthage bootstrap --platform OSX):
```
[...]
*** Building scheme "KeePassKit" in KeePassKit.xcodeproj
*** Building scheme "Sparkle" in Sparkle.xcodeproj
** BUILD FAILED **


The following build commands failed:
	PhaseScriptExecution Run\ Script:\ Link\ fr_CA\ to\ fr /Users/usernamehere/Library/Developer/Xcode/DerivedData/Sparkle-evazerxxnoxsqmfqcthfdoqhsfhb/Build/Intermediates/Sparkle.build/Release/Sparkle.build/Script-6195D4B40E40505A00D41A50.sh
(1 failure)
A shell task failed with exit code 65:
** BUILD FAILED **


The following build commands failed:
	PhaseScriptExecution Run\ Script:\ Link\ fr_CA\ to\ fr /Users/usernamehere/Library/Developer/Xcode/DerivedData/Sparkle-evazerxxnoxsqmfqcthfdoqhsfhb/Build/Intermediates/Sparkle.build/Release/Sparkle.build/Script-6195D4B40E40505A00D41A50.sh
(1 failure)

usernamehere@hostnamehere [~/Desktop/temp/MacPass]$
[...]
```
Skipping the two Sparkle build phases works for now.

Cheers,

**Comment by thy1985** [comment]
github "sparkle-project/Sparkle" ~> 1.13
is showing the same problem for me:
```
*** Checking out Sparkle at "1.13.0"
*** Fetching KeePassKit
*** Checking out KeePassKit at "1.0.3"
*** xcodebuild output can be found in /var/folders/_8/c9qbsklx4k3fxqmfjcz1s52m0000gn/T/carthage-xcodebuild.dH6Glj.log
*** Building scheme "HNHUi" in HNHUi.xcodeproj
*** Building scheme "KeePassKit" in KeePassKit.xcodeproj
*** Building scheme "Sparkle" in Sparkle.xcodeproj
** BUILD FAILED **


The following build commands failed:
	PhaseScriptExecution Run\ Script:\ Link\ fr_CA\ to\ fr /Users/usernamehere/Library/Developer/Xcode/DerivedData/Sparkle-evazerxxnoxsqmfqcthfdoqhsfhb/Build/Intermediates/Sparkle.build/Release/Sparkle.build/Script-6195D4B40E40505A00D41A50.sh
(1 failure)
A shell task failed with exit code 65:
** BUILD FAILED **
```

**Comment by mstarke** [comment]
that's odd I can use the setup for two machines without any problems

**Comment by mstarke** [comment]
Even odder is, the sparkle build is distributed as binary so there shouldn't be any building involved. Carthage favors pre build binaries if they are present.

**Comment by mstarke** [comment]
Just tried it again with your exact arguments (I use Mac as platform but that shouldn't have any effects) and it ran through.

````bash
user$ carthage bootstrap --platform OSX
*** Checking out HNHUi at "1.0.1"
*** Downloading Sparkle.framework binary at "More reliable migration from old Sparkle versions"
*** Checking out KeePassKit at "1.0.3"
*** Checking out Sparkle at "1.13.0"
*** xcodebuild output can be found in /var/folders/76/863tlp8c8xl3lt008k8cx6g80000gn/T/carthage-xcodebuild.zFDZqV.log
*** Building scheme "HNHUi" in HNHUi.xcodeproj
*** Building scheme "KeePassKit" in KeePassKit.xcodeproj
*** Building scheme "Sparkle" in Sparkle.xcodeproj
user$ 
````

**Comment by thy1985** [comment]
very strange. yes, mac vs osx should be neutral according to the manual. 

```
Even odder is, the sparkle build is distributed as binary so there shouldn't be any building involved. Carthage favors pre build binaries if they are present.
```
Well, the "offending part" (in my specific situation) is a shell script execution and is not directly related to any source compilation. 

Writing that I comes to my mind that this is maybe already part of the answer of what is wrong on my end. I have lots of custom build binaries in my users environment PATH variable (including the "ln" binary that is called for the symlink creation.... from the script which is what fails with non-zero return code. Also my bash is not Apple's default version so built-ins might be different, too. Maybe there is a side effect...

**Comment by thy1985** [comment]
Ah, yes. that is it!

Posting that confirmation here just in case s/o has the same or similar issue (ln -sfh is used in the failing script):
```
usernamehere@hostnamehere [~]$ ln -sfh test test2
ln: die Option -- „h“ist ungültig
„ln --help“ liefert weitere Informationen.
usernamehere@hostnamehere [~]$ /bin/ln -sfh test tes2
usernamehere@hostnamehere [~]$ ll test*
-rw-r--r-- 1 usernamehere staff 0 26. Dez 22:16 test
usernamehere@hostnamehere [~]$ ll tes*
lrwxr-xr-x 1 usernamehere staff 4 26. Dez 22:16 tes2 -> test
-rw-r--r-- 1 usernamehere staff 0 26. Dez 22:16 test
usernamehere@hostnamehere [~]$ rm -f tes2 test
usernamehere@hostnamehere [~]$
```
@mstarke Sorry for the fuss. My bad. My son was born a few days back. Probably I am bit too tired to think through things entirely before opening an issue. :)

**Comment by mstarke** [comment]
Nice. I was thinking about asking, whether you have custom builds. Glad it's sorted out! And congratulations for having a son! Seems to be a perfect Christmas gift.

**Comment by ParadiseDS** [comment]
Oh this post just saved me! I use the GNU version of ln as well and found the same strange error. It was quite unlovely that GNU and osx version of ln are not compatible with each other.

**Comment by 9point6** [comment]
I do the same, would it be possible to change the script to detect the type of `ln` in the path? (Or maybe use an absolute path to the OSX one)
