### ISSUE TITLE
kdb file ends up corrupted when "Windows Associations" are used (current master)

### ISSUE THREAD

**Issue by thy1985** [mstarke/MacPass#399]
hi

I have a KDBX database which works fine across Android (KeepShare, Keepass2Android Offline), Windows (KeePass 2x) and Mac OS (MacPass, build yesterday from current master).
Whenever I add an Windows Association to improve auto type on my Mac the DB is synced over to the other systems where the DB cannot be opened anymore. To use the DB I have to revert the DB file from backup (removing the offending Windows Association is not enough).

KeepShare says:
com.hanhuy.keepassj.KdbxFileFormatException
IllegalArgumentException: strSeq

Keepass2Android:
IllegalArgumentException: strSeq

That's a pity because without associations the auto type on Mac is a bit limited.

Let me know if you need more information.

Thanks and cheers,

**Comment by mathos77** [comment]
Wow, I was just going to report the same "bug".
There must be some special character maybe in the kdbx that is causing this (maybe it can not be read).

Perhaps it would be a good idea to put all the Auto-Type entries inside a separate database somewhere. This since the Auto-Type entries will never be 100% compatible to the Windows KP2 anyway.

I was thinking something in line of an ID or key within that little database like:   kdbx-name_UID-of-Entry

Kind regards, Mathos.

**Comment by mstarke** [comment]
The keystroke sequence gets escaped and any non Xml valid characters get stripped. There where no changes to this behavior in the recent past that I can think of would break this. It would be helpful to know the actual sequence or maybe create a test database?

**Comment by mathos77** [comment]
Hi,

I have a test DB, just with a password.


Password is:   ri4visje

This file opens perfectly in MacPass (built from source/git).
Once I will open it in KeePass2 on Windows or Android KeePass2Android for instance, it fails.

If I remove the AutoType window assignment from with MacPass, and save it, I can perfectly open it in both Windows and Android.


kind regards, Tom.

**Comment by mstarke** [comment]
I've found the culprit. I do not know why all the parsers are so "hard ass" on the format. I leave the keystroke sequence element out if empty and KeePassX actually complains about not finding the element but rather than assuming it's empty and get on with it, well. I'll fix it asap!

**Comment by thy1985** [comment]
@mstarke Great, thanks a lot! I did do a new build (working around the weirdness of #398 which seems to be specific to my setup) and can confirm that it works just fine now. :)
That helps a lot to make MacPass even more useful for my daily live? BTW, isn't there a donate button missing? ;) Or am I just blind...?

**Comment by mathos77** [comment]
Thanks Michael, 

Wow that was fast !

Silly indeed, if you can not find something, you could assume it is simply not there :)

I will

**Comment by mstarke** [comment]
@mathos77 No problem, this was a easy one. There are plenty of bugs around that require more effort and thus tend to stick around a bit longer ;-)

@thy1985 Thanks for the though about throwing money at the problem (me ;-) ) but the only thing for now is flattr  - there's a small button at the bottom of the Readme - and I said this before, it's nice for people to want to donate but it creates a sort of pressure on my part to actually spent more time on MacPass. Don't get me wrong, I love putting time into it, but with it already being a password manager it's kind of freaky to think what a wrong line of code on my side could do to someone using the app. Just looking at the stars in GitHub is scary enough for me :).

**Comment by thy1985** [comment]
@mstarke hehe, okay.  I love using MacPass  "as-is" with no warranty at all and I am well aware that there is always the risk of bugs that might impact security aspects. However I think I somewhat understand your concerns (even though I do not mix a donation with a VIP support pass). :) I have no intention to sign-up with flattr so far. Well, so keep up the good work and when you feel the need for a beer crate or some bottles of ur favorite non-alcoholic beverage (better for code quality ;)) just let me know. :D
