### ISSUE TITLE
Crashing of MacPass

### ISSUE THREAD

**Issue by maku** [mstarke/MacPass#403]
MacPass crashes really often on my machine. My question: I see rather busy work on MacPass but no new releases. 
Is something planned ?

**Comment by mstarke** [comment]
Firstly, if MacPass crashes it's very helpful if you can supply a crash log (via console.app) or at least try to reproduce the crash. Secondly I plan on setting up a CI system to create nightly builds to better vent out new binaries as this is a current hold up. MacPass did change a lot, so new releases tend to be unstable sometimes.

**Comment by maku** [comment]
O.k. will try it next time. Thank you for your effort

**Comment by mboelke** [comment]
Same here. Since I built a new binary (as described) yesterday, MacPass crashed two times.
Please find crash log attached.
[MacPass_crash.txt](https://github.com/mstarke/MacPass/files/79775/MacPass_crash.txt)

**Comment by mstarke** [comment]
:) you're using address santiizer that means your running a debug build, archive the app and use it or disable address sanitiser in the scheme for debugging. This should fix the problem. Are you using plugins? If so, this might be a problem too since there are some instabilities

**Comment by maku** [comment]
@mstarke I use MacPass with KeePassHttp (Version 0.4.1 (2535) -> don't know from where this version of MacPass is) 
For me KeePassHttp is a must have and I would like to use MacPass further because I really like it (thx for your great effort building it). But this version is really unstable (I know it is some alpha version ...)
Is there a stable(r) version of MacPass (with KeePassHttp) available / planned?

**Comment by mstarke** [comment]
KeePassHTTP has been pushed to be a plugin since a plugin interface was introduced but no stable release was built. My guess is that KeePassHTTP crashes since there were some threading issues that were fixed.

For the "new" plugin see [MacPassHTTP](https://github.com/MacPass/MacPassHTTP)

But there is no "easy" way to get things working for now.

**Comment by mboelke** [comment]
@mstarke Ok, I have no idea what you mean. For building MacPass I follwed your "How to Build" steps.
The only (are there more?) plugin I am using is MacPassHTTP. Therfore I built the app because the releases aren't able to use plugins (right?).

**Comment by mstarke** [comment]
@mboelke I did answer to @maku. Sorry for the confusion.

@mboelke Correct, only the current master is able to use plugins. If you build via the supplied method then you should have a release build of MacPass as well as MacPassHTTP. About the Adress Sanitizer: This is a debugging option and that's the lib that's crashing in your crash report (which it does if it detects an error) but normally this should not be present in any release build, only in debug versions.

**Comment by maku** [comment]
@mstarke when I compile MacPassHttp I get an error "fatal error: 'HNHUi/HNHUi.h' file not found" (after the steps described in https://github.com/MacPass/MacPassHTTP

**Comment by mstarke** [comment]
Since MacPass has adopted Carthage the instructions did change, I just updated them for MacPassHTTP

**Comment by maku** [comment]
@mstarke o.k. compilation worked. when i restart (the also new compiled MacPass) I am able to activate MacPassHttp (after restart and enabling unsecure ...) .  

But it seems it does not work. I checked the port (19455). This seems fine. But no contact... Any ideas? (tried it with IChromePass which alread worked for me)

**Comment by maku** [comment]
The new compiled version seems stable. Thx for helping...

**Comment by mstarke** [comment]
Did you get MacPassHTTP to work?

**Comment by maku** [comment]
Yeah, it seems you have to do a new "connect" with the chrome extension (chromeIpass) because of security reasons...

**Comment by mr-jingles** [comment]
I got to work too! For me everything is now just as I want it. Perfekt - Thank you so much for your effort!
