### ISSUE TITLE
MacPass custom fields

### ISSUE THREAD

**Issue by cedricpim** [mstarke/MacPass#412]
First of all, excellent work on MacPass.

This is not so much of an issue as it is more a question: Are the custom fields also encrypted or putting information there is a liability?

Thanks.

**Comment by mstarke** [comment]
#385 has some explanations on the file format.

tl;dr; everything is encrypted

**Comment by kud** [comment]
Thanks I wanted to know the same thing.

Are custom fields a "normal" thing in keepass or is it only available in MacPass?

**Comment by mstarke** [comment]
MacPass has nothing custom regarding KDBX databases. Only KDB has some custom extensions that aren’t necessary but make KDB get more in line with all KDBX features.

Custom fields are a default KDBX feature.

**Comment by kud** [comment]
That's amazing! Thank you for your answers, I'll use more custom fields so, where I previously created another key for services (like "apple password", "apple answer 1", "apple answer 2", etc)

**Comment by mstarke** [comment]
MacPass’ UI tries to put custom fields more in par with the default ones. Other clients (except e.g. KeeShare) tend to burry them in sub views.
