### ISSUE TITLE
How to enable keepasshttp? I have got mono and .plgx file

### ISSUE THREAD

**Issue by ezeeyahoo** [mstarke/MacPass#413]
I am on mac and installed KeePass Desktop from App Store.

**Comment by DominusExult** [comment]
This is the support for MacPass. Nothing to do with mono or any plugin for the original Keepass.
For support of Keepass Desktop contact the seller of that software.

**Comment by ezeeyahoo** [comment]
Well I asked because :- 
![screen shot 2016-01-23 at 9 46 04 pm](https://cloud.githubusercontent.com/assets/3622762/12531215/cf757a36-c21a-11e5-96be-c594e271d2b3.png)

**Comment by DominusExult** [comment]
Yes, "based on". When you need help with Keepass Desktop, ask those guys that sold it to you (via App Store).

**Comment by mstarke** [comment]
KeePass desktop will be removed from the App Store since it's in violation of the GPL license for MacPass. KeePassHTTP is supported via the MacPassHTTP plugin. Plugins are currently only supported by building your own version of MacPass from GitHub. I will release a new version of MacPass that supports plugin in the near future. Yes, I know that I say that a lot but 0.6 is necessary after this long time ;-).

**Comment by ezeeyahoo** [comment]
I had that doubt, how can someone build and release an open source on a different name and ownership.

Thanks MStarke for that news and information.

**Comment by mstarke** [comment]
It's completely legitimate to rename and redistribute MacPass. The only thing to comply to are the licenses. So the redistribution isn't wrong. It's the offering in the App Store.

**Comment by tthoma24** [comment]
Could you explain how offering the app in Mac App Store violates the license?

**Comment by DominusExult** [comment]
I'm not 100% sure which license MacPass uses but if it is GPL, the App Store isn't compatible. Mainly that you can't pass on the app to anybody but the GPL's "copyleft" mindset explicitly enforces that.
A way better look at that than I could ever give http://www.engadget.com/2011/01/09/the-gpl-the-app-store-and-you/

**Comment by vabue** [comment]
We all wait for release ^)

**Comment by ezeeyahoo** [comment]
Hi,

There is an issue with MacPassHTTP with PassIFox(not checked for Chrome). It matches on username for example if a login page ask for email id and if I give an id which is already exist for any record in the database, then it auto-type without checking URL and it ask to update if you give different password rather than asking to add new entry for that domain/URL.

-- 
Eshant Gupta
Sent with Airmail

On 1 February 2016 at 8:50:29 PM, Valentine Budkin (notifications@github.com) wrote:

We all wait for release ^)

**Comment by mstarke** [comment]
@ezeeyahoo this is an MacPassHTTP issue, could you please open it in the appropriate repository?

**Comment by ezeeyahoo** [comment]
Sure, Thanks

-- 
Eshant Gupta
Sent with Airmail

On 2 February 2016 at 3:09:13 PM, Michael Starke (notifications@github.com) wrote:

@ezeeyahoo this is an MacPassHTTP issue, could you please open it in the appropriate repository?
