### ISSUE TITLE
Sparkle Framework security issue

### ISSUE THREAD

**Issue by sub0ne** [mstarke/MacPass#416]
According to several internet magazines the Sparkle framework has a security issue which makes it possible for other users in an unsecured network to start a man-in-the-middle attack.

Source: http://www.heise.de/mac-and-i/meldung/Populaerer-OS-X-Updater-Sparkle-mit-problematischer-Sicherheitsluecke-3098376.html

**Comment by mstarke** [comment]
Thanks for the heads up - you're the third persons to notify me - I'm about to release a new binary that should fix the problem.

**Comment by mstarke** [comment]
fixed in e99e990b134398f1c81f91b99c23b15f6ddbb271 (0.5.2)
