### ISSUE TITLE
cmd+c do not copy from Notes field

### ISSUE THREAD

**Issue by r0bj** [mstarke/MacPass#417]
cmd+c do not copy from Notes field.
It can be only possible via context menu and choose "copy"

MacPass version 0.6

**Comment by mstarke** [comment]
I am unable to reproduce this bug. Did you rebind any shortcuts via the OS Preferences?

**Comment by r0bj** [comment]
Yes, two:
- "Copy Password" as "cmd C" (this may be related)
- "Show Password Generator" as "cmd P"

**Comment by mstarke** [comment]
There you go. You overplayed the Cmd+C for the Textfield with "Copy Password". You can try to use it on any other Textinput, it shouldn't work as well. There's a reason the default shortcut isn't Cmd+C as this interferes with any Textinput.
