### ISSUE TITLE
Change master password -> database password expired

### ISSUE THREAD

**Issue by r0bj** [mstarke/MacPass#418]
When trying to change master DB password:
1. File -> Change Master Password
2. Enter new password twice, hit "Change Password"
3. During attempt to save DB, message is generated:

```
The database password expired!
You will be unable to save until the password and/or keyfile has been changed.
```

**Comment by mstarke** [comment]
Can you take at the database settings and specifically at the settings for the expiration? Is the number of days set to 0 and the check box ticked?

Might this be a side effect of #269?

**Comment by r0bj** [comment]
Thanks.
Both "Recommended key change every" and "Force key change every" check boxes were ticked and set to 0.
After disabling those options changing pass works ok.
