### ISSUE TITLE
Password not saved when clicked the "eye button"

### ISSUE THREAD

**Issue by 360fun** [mstarke/MacPass#419]
Hi,

I checked the existent issues and I didn't find it, so, here we go...

**Create a new key and losing the new password:**

IMPORTANT: the password must be hidden initially!
1. create a new key
2. click the eye icon to show the password (you can see the generated one)
3. write a password (overwrite the generated one)
4. click the eye icon to hide the password
5. change key or click outside to deselect the current key
6. select again the key
7. the password saved is the generated one and NOT the new one! (BUG)

There're many other cases, it can be also not hidden initially but this is the most common way of creating a key (at least for me) and see the bug.

**You can see the same behaviour also when you edit old entries:**

IMPORTANT: the password can be hidden or not initially!
1. select a key
2. overwrite the password (doesn't matter if is hidden or not)
3. click the eye icon to hide or unhide the password
4. change key or click outside to deselect the current key
5. select again the key
6. the password saved is NOT the last one but the previous one! (BUG)

**What is funny is that with this sequence it works:**

IMPORTANT: the password must be hidden initially!
1. create a new key
2. overwrite the password (without seeing what you actually write since the text is hidden)
3. click the eye icon to unhide the password (but don't hide it again!)
4. change key or click outside to deselect the current key
5. select again the key
6. the password IS saved! (correct behaviour)

Please fix it asap, it's really dangerous: people will save entries without the right password...so the whole point of the app is missing. Thankfully I lost just few passwords before noticing it...but I've to check 3 times to feel sure now. :(

**Comment by mstarke** [comment]
Thanks for the detailed description. There are reports of strange behavior with the show/hide mechanism all the time but I was never able to reproduce them. Recent changes to bindings might have made things worse so I'll look into it!

**Comment by 360fun** [comment]
Yep, I agree, it was tricky to identify the behaviour! ;)

Hope you can fix it soon! :D

**Comment by 360fun** [comment]
Wow, you fix it! AWESOME! :)

**Comment by mstarke** [comment]
Well, I did not explicitly fix it, but it seems to have been a side effect of #421
