### ISSUE TITLE
"document changed state" will be forgotten by clicking into textfield & more

### ISSUE THREAD

**Issue by blynx** [mstarke/MacPass#425]
Hi,

editing a field like "title" sets the indicator in the close button that the document has changed. closing the document will ask me to save then.
But when I click into another field - that state will be forgotten and by closing I loose all changes. No asking there ... I always have to save explicitly.

Also, editing the notes field doesn't trigger that indicator / state.

Thats my first test - the only thing I did so far was creating a new file and adding a couple of groups, passwords and notes.

cheers,
Steffen

**Comment by blynx** [comment]
Also: Simply deleting an item doesnt trigger that "file changed" state thing - is this intended?

**Comment by mstarke** [comment]
That's a nasty side effect of the current incomplete history support. 0.5.x did record any changes as undo/redoable but 0.6 doesn't do this anymore. That's something that completely slipped my mind. Deleting should actually trigger file changes as well.

**Comment by blynx** [comment]
I tried the latest release now - (0.6.2)
the state gets saved now all the time the file gets locked. nice!
But deleting (and adding) a key-entry is not really recognized here.

**Comment by mstarke** [comment]
That's right, MacPass now saves the file on locking. And it also notifies about changes done to the file outside of MacPass, although merging any changes is still unsupported!

I'm in the process of reworking a lot of the API on moving/editing in KeePassKit to better work with undo/redo and be as consistent as possible with the KDBX format. When this is done, changes should be recored correctly again and a warning on closing without saving will pop up!

**Comment by mstarke** [comment]
Move/Create/Delete operations are registered correctly again as undoable and mark the document as dirty. Changes to groups will mark the document dirty as well again. Entry editing is the only thing left and should be fixed shortly as I think I now got the history support figured out.

**Comment by mstarke** [comment]
9ac7c93fbf4e549929d6211dee1593b4e6fa920c should fix all issues with lost data on save while text inputs still have focus
