### ISSUE TITLE
Remember Keyfile setting doesn't work

### ISSUE THREAD

**Issue by enterfornone** [mstarke/MacPass#426]
From version 0.6 (and now in 0.6.1) the setting "Remember Keyfile for Databases" seems to be broken. Now every time have to select keyfile, regardless for the setting. I tried changing databases, restarting with several combinations, but always the same - keyfile location is not remembered

**Comment by haimiko** [comment]
Same issue.  Used to work now doesn't.

**Comment by avkiller** [comment]
Same issue

**Comment by mstarke** [comment]
I got the message ;)

**Comment by mstarke** [comment]
If you do not quit MacPass this bug will not arise. It's an error in migration the old defaults format int the new one as I just rehash everything so there are keys which are hashed hashes which aren't found anymore.

**Comment by haimiko** [comment]
Thank you for getting this fixed so fast.  You rock!
