### ISSUE TITLE
Insecure update error

### ISSUE THREAD

**Issue by mariosangiorgio** [mstarke/MacPass#427]
Hello, I tried to compile MacPass in an attempt to implement the feature requested in #415.
I can build MacPass, but as soon as I try to run it I get a window with the following message:

> For security reasons, you need to code sign your application or sign your updates with a DSA key. See Sparkle's documentation for more information.

Is there any way to avoid signing while working on my dev copy?

**Comment by mstarke** [comment]
I removed the public key from the Info.plist in 3abf1982b1c6802b46dc524fbd88b16ccbb5da7e as this caused the update process to fail. If you just revert this commit everything should work. I'll try to update the code ASAP to make development more painless again. There's a discussion on the sparkle project about this issue (related to UI testing) as well https://github.com/sparkle-project/Sparkle/issues/680

**Comment by timbru31** [comment]
@mstarke ASAP was 22 days ago ;)
Any fix in sight? :)

**Comment by mstarke** [comment]
Fixed in 4a7d6e14d97e9c730660fb97a597dfd490e265c3
