### ISSUE TITLE
Autotype error

### ISSUE THREAD

**Issue by bz007** [mstarke/MacPass#431]
Autotype is not working. Instead of this I see exception in system log (via Console). There is log trace example:

> Mar  3 01:42:52 lupus MacPass[98518]: An uncaught exception was raised
> Mar  3 01:42:52 lupus MacPass[98518]: *** -[__NSCFString rangeOfString:options:range:locale:]: nil argument
> Mar  3 01:42:52 lupus MacPass[98518]: (
> 		0   CoreFoundation                      0x00007fff95604ae2 __exceptionPreprocess + 178
> 		1   libobjc.A.dylib                     0x00007fff8b681f7e objc_exception_throw + 48
> 		2   CoreFoundation                      0x00007fff9560498d +[NSException raise:format:] + 205
> 		3   Foundation                          0x00007fff8763ff49 -[NSString rangeOfString:options:range:locale:] + 353
> 		4   Foundation                          0x00007fff87679390 -[NSString rangeOfString:options:] + 74
> 		5   MacPass                             0x0000000100b90c91 -[MPDocument(Autotype) autotypContextsForWindowTitle:preferredEntry:] + 1555
> 		6   MacPass                             0x0000000100b8936b -[MPAutotypeDaemon _autotypeContextForDocuments:forWindowTitle:preferredEntry:] + 296
> 		7   MacPass                             0x0000000100b88f54 -[MPAutotypeDaemon _performAutotypeForEntry:] + 218
> 		8   MacPass                             0x0000000100b89871 __35-[MPAutotypeDaemon _registerHotKey]_block_invoke + 34
> 		9   MacPass                             0x0000000100b9ebe2 -[DDHotKey invokeWithEvent:] + 134
> 		10  MacPass                             0x0000000100b9f047 dd_hotKeyHandler + 466
> 		11  HIToolbox                           0x00007fff8e1717be _ZL23DispatchEventToHandlersP14EventTargetRecP14OpaqueEventRefP14HandlerCallRec + 1231
> 		12  HIToolbox                           0x00007fff8e170c48 _ZL30SendEventToEventTargetInternalP14OpaqueEventRefP20OpaqueEventTargetRefP14HandlerCallRec + 404
> 		13  HIToolbox                           0x00007fff8e170aab SendEventToEventTargetWithOptions + 43
> 		14  HIToolbox                           0x00007fff8e1add5e _ZL29ToolboxEventDispatcherHandlerP25OpaqueEventHandlerCallRefP14OpaqueEventRefPv + 1214
> 		15  HIToolbox                           0x00007fff8e171e0f _ZL23DispatchEventToHandlersP14EventTargetRecP14OpaqueEventRefP14HandlerCallRec + 2848
> 		16  HIToolbox                           0x00007fff8e170c48 _ZL30SendEventToEventTargetInternalP14OpaqueEventRefP20OpaqueEventTargetRefP14HandlerCallRec + 404
> 		17  HIToolbox                           0x00007fff8e1869e6 SendEventToEventTarget + 40
> 		18  AppKit                              0x00007fff91bfc5b0 -[NSApplication sendEvent:] + 4435
> 		19  AppKit                              0x00007fff91b2f03a -[NSApplication run] + 796
> 		20  AppKit                              0x00007fff91ab1520 NSApplicationMain + 1176
> 		21  libdyld.dylib                       0x00007fff8f0ca5ad start + 1

If this is important, I use English and Russian locales in System settings, English is primary. MacPassHTTP helps in most cases but sometimes I need autotype password with global hotkey.

Please advise.

**Comment by mstarke** [comment]
I might have found the error but it seems strange. I suspect the bug occurs for a certain URL, can you verify that?

**Comment by bz007** [comment]
Actually I have troubles on any URL I had tried. For me it looks like hot key is not working at all. I postponed this behaviour for future investigations and only yesterday I discovered the exceptions in logs. This is why I filled this bug. I am ready to make any tests you provide, I have xcode installed and even can recompile the binaries.

**Comment by mstarke** [comment]
The error shows that the hotkey is working. If you would be so kind to set a breakpoint at ```[-MPAutotypeDaemon _autotypeContextForDocuments:forWindowTitle:preferredEntry:]``` and step through until you get the exception that would be awesome!

**Comment by bz007** [comment]
The last executing is here:
<img width="908" alt="screen shot 2016-03-04 at 23 20 48" src="https://cloud.githubusercontent.com/assets/9906471/13539199/e60dd224-e25f-11e5-818d-db7504580ff7.png">
Next step over rises exception.
And there is the workaround, disable the "Host match" in options whatever it means.

**Comment by mstarke** [comment]
That's the spot where I did suspect the crash and I fixed it, will be pushed shortly.

**Comment by mstarke** [comment]
And a big thank you for your effort!
