### ISSUE TITLE
[Feature Request] Lock password view

### ISSUE THREAD

**Issue by leonvers** [mstarke/MacPass#432]
First of all, great program!
I think it's very insecure that when I unlock my database, I can view my passwords all the time.
There should be another lock function for password view, so I can use MacPass but I don't need to be afraid that someone else can view my passwords. Furthermore there is no need to view my passwords when I use the copy & paste function.
I'm just worrying about leaving the computer alone for a few minutes or malware (which can view my passwords in the background without my knowledge).
I don't always want to lock my database after I used a password.
I hope I could make it clear.

**Comment by mstarke** [comment]
First of: If you set up auto-lock after inactivity then this will lock you database.
Do I understand you correctly that by see passwords all the time, you mean the little eye button on the password input? And you want the app to automatically toggle them back the dotted view after a while?

**Comment by leonvers** [comment]
Yes, I konw that.
No, I don't want them to toggle back to dotted view. I want another lock when I press the eye button. So I need to insert my password again before viewing the password in plain text. It would feel a lot more secure. Do you understand?

**Comment by mstarke** [comment]
Clear. But, then you also need to ask for the password whenever the password is copied to the clipboard. And it doesn't stop there. Users can use autotype and this can reference the password. This then would also require for a password input. The next thing are placeholders in fields. Another field - say the url - could use the password. This would then require the ui to add the toggle button to the url field as well. And if you go one step further referencing needs to work the same way. I feel this makes it rather complicated, don't you think?

**Comment by leonvers** [comment]
Yeah, you're right. It would be too complicated.
I guess I should just lock my database when I leave my computer alone.

Thanks for your answers! :)
