### ISSUE TITLE
Macpass crashes evertime hitting "connect" button in Firefox PasslFox 1.1.13.1 

### ISSUE THREAD

**Issue by chcao052** [mstarke/MacPass#439]
clone MacPass and MacPassHttp according to instructions,
Enable plugin
Open a entry to in the browser,
Hit "connect" button in the browser, and the crash will come within seconds:

Process:               MacPass [36655]
Path:                  /Users/USER/Library/Developer/Xcode/DerivedData/MacPass-fqzsybvdcwxtcqacbsfcjeybvzqo/Build/Products/Release/MacPass.app/Contents/MacOS/MacPass
Identifier:            com.hicknhacksoftware.MacPass
Version:               0.6.2 (12740)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           MacPass [36655]
User ID:               501

Date/Time:             2016-03-23 00:02:33.634 +1100
OS Version:            Mac OS X 10.11.3 (15D21)
Report Version:        11
Anonymous UUID:        516A1878-1D4A-E3BD-1EFE-91E63612FB76

Sleep/Wake UUID:       13A4D011-5BF3-41AE-9467-A27AED36E11C

Time Awake Since Boot: 330000 seconds
Time Since Wake:       7300 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[KPKGroup addEntry:]: unrecognized selector sent to instance 0x60d0000bd540'
abort() called
terminating with uncaught exception of type NSException

Application Specific Backtrace 1:
0   CoreFoundation                      0x00007fff98657ae2 __exceptionPreprocess + 178
1   libobjc.A.dylib                     0x00007fff9bf4cf7e objc_exception_throw + 48
2   CoreFoundation                      0x00007fff9865ab9d -[NSObject(NSObject) doesNotRecognizeSelector:] + 205
3   CoreFoundation                      0x00007fff98593601 ___forwarding___ + 1009
4   CoreFoundation                      0x00007fff98593188 _CF_forwarding_prep_0 + 120
5   MacPassHTTP                         0x000000010fe9e6ce __47-[MPHServerDelegate _createConfigurationEntry:]_block_invoke + 62
6   libclang_rt.asan_osx_dynamic.dylib  0x0000000107b76cb4 __wrap_dispatch_async_block_invoke + 260
7   libdispatch.dylib                   0x00007fff96ac0871 _dispatch_call_block_and_release + 12
8   libdispatch.dylib                   0x00007fff96ab533f _dispatch_client_callout + 8
9   libdispatch.dylib                   0x00007fff96ac8c1d _dispatch_main_queue_callback_4CF + 1685
10  CoreFoundation                      0x00007fff9859dcd9 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
11  CoreFoundation                      0x00007fff98558d3d __CFRunLoopRun + 1949
12  CoreFoundation                      0x00007fff98558338 CFRunLoopRunSpecific + 296
13  HIToolbox                           0x00007fff90aec935 RunCurrentEventLoopInMode + 235
14  HIToolbox                           0x00007fff90aec76f ReceiveNextEventCommon + 432
15  HIToolbox                           0x00007fff90aec5af _BlockUntilNextEventMatchingListInModeWithFilter + 71
16  AppKit                              0x00007fff8deb40ee _DPSNextEvent + 1067
17  AppKit                              0x00007fff8e280943 -[NSApplication _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 454
18  AppKit                              0x00007fff8dea9fc8 -[NSApplication run] + 682
19  AppKit                              0x00007fff8de2c520 NSApplicationMain + 1176
20  libdyld.dylib                       0x00007fff95b655ad start + 1

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	0x00007fff90965002 __pthread_kill + 10
1   libsystem_pthread.dylib       	0x00007fff8cf255c5 pthread_kill + 90
2   libsystem_c.dylib             	0x00007fff9ef9e6e7 abort + 129
3   libc++abi.dylib               	0x00007fff8b79ff81 abort_message + 257
4   libc++abi.dylib               	0x00007fff8b7c5a47 default_terminate_handler() + 267
5   libobjc.A.dylib               	0x00007fff9bf4f6ae _objc_terminate() + 103
6   libc++abi.dylib               	0x00007fff8b7c319e std::__terminate(void (*)()) + 8
7   libc++abi.dylib               	0x00007fff8b7c3213 std::terminate() + 51
8   libdispatch.dylib             	0x00007fff96ab5353 _dispatch_client_callout + 28
9   libdispatch.dylib             	0x00007fff96ac8c1d _dispatch_main_queue_callback_4CF + 1685
10  com.apple.CoreFoundation      	0x00007fff9859dcd9 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
11  com.apple.CoreFoundation      	0x00007fff98558d3d __CFRunLoopRun + 1949
12  com.apple.CoreFoundation      	0x00007fff98558338 CFRunLoopRunSpecific + 296
13  com.apple.HIToolbox           	0x00007fff90aec935 RunCurrentEventLoopInMode + 235
14  com.apple.HIToolbox           	0x00007fff90aec76f ReceiveNextEventCommon + 432
15  com.apple.HIToolbox           	0x00007fff90aec5af _BlockUntilNextEventMatchingListInModeWithFilter + 71
16  com.apple.AppKit              	0x00007fff8deb40ee _DPSNextEvent + 1067
17  com.apple.AppKit              	0x00007fff8e280943 -[NSApplication _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 454
18  com.apple.AppKit              	0x00007fff8dea9fc8 -[NSApplication run] + 682
19  com.apple.AppKit              	0x00007fff8de2c520 NSApplicationMain + 1176
20  libdyld.dylib                 	0x00007fff95b655ad start + 1

Thread 1:: Dispatch queue: com.apple.libdispatch-manager
0   libsystem_kernel.dylib        	0x00007fff90965ff6 kevent_qos + 10
1   libdispatch.dylib             	0x00007fff96abb099 _dispatch_mgr_invoke + 216
2   libdispatch.dylib             	0x00007fff96abad01 _dispatch_mgr_thread + 52

Thread 2:: com.apple.NSEventThread
0   libsystem_kernel.dylib        	0x00007fff9095f386 mach_msg_trap + 10
1   libsystem_kernel.dylib        	0x00007fff9095e7c7 mach_msg + 55
2   com.apple.CoreFoundation      	0x00007fff98559624 __CFRunLoopServiceMachPort + 212
3   com.apple.CoreFoundation      	0x00007fff98558aec __CFRunLoopRun + 1356
4   com.apple.CoreFoundation      	0x00007fff98558338 CFRunLoopRunSpecific + 296
5   com.apple.AppKit              	0x00007fff8df73065 _NSEventThread + 149
6   libsystem_pthread.dylib       	0x00007fff8cf23c13 _pthread_body + 131
7   libsystem_pthread.dylib       	0x00007fff8cf23b90 _pthread_start + 168
8   libsystem_pthread.dylib       	0x00007fff8cf21375 thread_start + 13

Thread 3:
0   libsystem_kernel.dylib        	0x00007fff909656de __workq_kernreturn + 10
1   libsystem_pthread.dylib       	0x00007fff8cf23729 _pthread_wqthread + 1283
2   libsystem_pthread.dylib       	0x00007fff8cf21365 start_wqthread + 13

Thread 4:
0   libsystem_kernel.dylib        	0x00007fff909656de __workq_kernreturn + 10
1   libsystem_pthread.dylib       	0x00007fff8cf23729 _pthread_wqthread + 1283
2   libsystem_pthread.dylib       	0x00007fff8cf21365 start_wqthread + 13

Thread 5:
0   libsystem_kernel.dylib        	0x00007fff909656de __workq_kernreturn + 10
1   libsystem_pthread.dylib       	0x00007fff8cf23729 _pthread_wqthread + 1283
2   libsystem_pthread.dylib       	0x00007fff8cf21365 start_wqthread + 13

Thread 6:: Dispatch queue: com.apple.root.default-qos
0   libsystem_kernel.dylib        	0x00007fff9095f3c2 semaphore_wait_trap + 10
1   libdispatch.dylib             	0x00007fff96ac0be6 _dispatch_semaphore_wait_slow + 224
2   com.hicknhacksoftware.MacPassHTTP	0x000000010fe9e5e6 -[MPHServerDelegate _createConfigurationEntry:] + 236 (MPHServerDelegate.m:133)
3   com.hicknhacksoftware.MacPassHTTP	0x000000010fe9e18c -[MPHServerDelegate configurationEntry] + 887 (MPHServerDelegate.m:116)
4   com.hicknhacksoftware.MacPassHTTP	0x000000010fe9dd96 -[MPHServerDelegate queryDocumentOpen] + 30 (MPHServerDelegate.m:74)
5   com.hicknhacksoftware.MacPassHTTP	0x000000010fe9fb84 -[MPHServerDelegate clientHashForServer:] + 33 (MPHServerDelegate.m:257)
6   com.hicknhacksoftware.KeePassHTTPKit	0x000000010fec2fea __17-[KPHServer init]_block_invoke + 114 (KPHServer.m:58)
7   net.pol-online.GCDWebServers  	0x000000010ff1268e __79-[GCDWebServer(Handlers) addDefaultHandlerForMethod:requestClass:processBlock:]_block_invoke + 62 (GCDWebServer.m:798)
8   net.pol-online.GCDWebServers  	0x000000010ff04541 -[GCDWebServerConnection(Subclassing) processRequest:completion:] + 92 (GCDWebServerConnection.m:762)
9   net.pol-online.GCDWebServers  	0x000000010ff01eae -[GCDWebServerConnection _startProcessingRequest] + 164 (GCDWebServerConnection.m:387)
10  net.pol-online.GCDWebServers  	0x000000010ff027db -[GCDWebServerConnection _readBodyWithLength:initialData:] + 535 (GCDWebServerConnection.m:493)
11  net.pol-online.GCDWebServers  	0x000000010ff03545 __45-[GCDWebServerConnection _readRequestHeaders]_block_invoke + 2026 (GCDWebServerConnection.m:578)
12  net.pol-online.GCDWebServers  	0x000000010ff0090a __65-[GCDWebServerConnection(Read) _readHeaders:withCompletionBlock:]_block_invoke + 280 (GCDWebServerConnection.m:133)
13  net.pol-online.GCDWebServers  	0x000000010ff005de __69-[GCDWebServerConnection(Read) _readData:withLength:completionBlock:]_block_invoke + 304 (GCDWebServerConnection.m:104)
14  libdispatch.dylib             	0x00007fff96ad27a8 __dispatch_read_block_invoke_252 + 39
15  libdispatch.dylib             	0x00007fff96ac0871 _dispatch_call_block_and_release + 12
16  libdispatch.dylib             	0x00007fff96ab533f _dispatch_client_callout + 8
17  libdispatch.dylib             	0x00007fff96ab91cf _dispatch_root_queue_drain + 1890
18  libdispatch.dylib             	0x00007fff96ab8a34 _dispatch_worker_thread3 + 91
19  libsystem_pthread.dylib       	0x00007fff8cf2368f _pthread_wqthread + 1129
20  libsystem_pthread.dylib       	0x00007fff8cf21365 start_wqthread + 13

Thread 7:
0   libsystem_kernel.dylib        	0x00007fff909656de __workq_kernreturn + 10
1   libsystem_pthread.dylib       	0x00007fff8cf23729 _pthread_wqthread + 1283
2   libsystem_pthread.dylib       	0x00007fff8cf21365 start_wqthread + 13

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x0000000000000006  rcx: 0x00007fff58341d98  rdx: 0x0000000000000000
  rdi: 0x000000000000160b  rsi: 0x0000000000000006  rbp: 0x00007fff58341dc0  rsp: 0x00007fff58341d98
   r8: 0x00001c180004710f   r9: 0xffffe3e7fffb8eff  r10: 0x0000000008000000  r11: 0x0000000000000206
  r12: 0x00007fff58341f20  r13: 0x000000010b406640  r14: 0x00007fff7b345000  r15: 0x00007fff58341e00
  rip: 0x00007fff90965002  rfl: 0x0000000000000206  cr2: 0x00000001200e0040
  
Logical CPU:     0
Error Code:      0x02000170
Trap Number:     133

Binary Images:
       0x1078bc000 -        0x10797bfff +com.hicknhacksoftware.MacPass (0.6.2 - 12740) <01A7ED3E-127A-302F-A524-4BC05D30DAA1> /Users/USER/Library/Developer/Xcode/DerivedData/MacPass-fqzsybvdcwxtcqacbsfcjeybvzqo/Build/Products/Release/MacPass.app/Contents/MacOS/MacPass
       0x107a3b000 -        0x107a86fff +com.hicknhacksoftware.KeePassKit (1.1 - 1274) <06CBA3A1-8D48-31E0-8BFC-68E5F88DA83A> /Users/USER/Library/Developer/Xcode/DerivedData/MacPass-fqzsybvdcwxtcqacbsfcjeybvzqo/Build/Products/Release/MacPass.app/Contents/Frameworks/KeePassKit.framework/Versions/A/KeePassKit
       0x107ab7000 -        0x107af3ff7 +org.sparkle-project.Sparkle (1.14.0 git-312fa40 - 1.14.0) <1A9BBA31-D8A5-30C2-A14E-5372FA1B5D68> /Users/USER/Library/Developer/Xcode/DerivedData/MacPass-fqzsybvdcwxtcqacbsfcjeybvzqo/Build/Products/Release/MacPass.app/Contents/Frameworks/Sparkle.framework/Versions/A/Sparkle
       0x107b16000 -        0x107b24ff7 +com.hicknhacksoftware.HNHUi (1 - 1274) <71442B11-F493-31FD-BD06-55C2CC501403> /Users/USER/Library/Developer/Xcode/DerivedData/MacPass-fqzsybvdcwxtcqacbsfcjeybvzqo/Build/Products/Release/MacPass.app/Contents/Frameworks/HNHUi.framework/Versions/A/HNHUi
       0x107b35000 -        0x107babfff +libclang_rt.asan_osx_dynamic.dylib (0) <08462124-89FF-3CAF-B314-96BF448DFBDD> /Users/USER/Library/Developer/Xcode/DerivedData/MacPass-fqzsybvdcwxtcqacbsfcjeybvzqo/Build/Products/Release/MacPass.app/Contents/Frameworks/libclang_rt.asan_osx_dynamic.dylib
       0x1
...
....
Model: MacBookAir6,2, BootROM MBA61.0099.B21, 2 processors, Intel Core i5, 1.3 GHz, 4 GB, SMC 2.13f15

...

**Comment by mstarke** [comment]
MacPassHTTP requires MacPass 0.6.2 release NOT the master version as there were changes to the KeePassKit API and this is in your case the cause of the crash

**Comment by LiljebergXYZ** [comment]
Is there any reason the new KeePassKit API isn't used in the master branch yet? I see in Xcode is noted as version 0.6.2 however it seems to be behind on the KeePassKit API.

**Comment by mstarke** [comment]
MacPass in the master branch always uses the newest KeePassKit Api. I do not update the version string until a new build is marked for release but if you deploy the app, the build number is included and you'll see a newer build (unequal the one 0.6.2 used). The problem is not MacPass using an old API but MacPassHTTP using the old one. The reason this is stalled is time. I will release a new version of MacPassHTTP once MacPass gets a new release to keep them in sync but I have no plans to roll the development on all plugins mainly because I want to focus on MacPass instead of divert even more time to other things. I'm more than happy to merge changes of MacPassHTTP ;).

**Comment by LiljebergXYZ** [comment]
My mistake then, I assumed it was using a newer version from your message. Here's to hoping for an update (or time to update it myself). Thanks for the prompt reply!
