### ISSUE TITLE
Failing carthage bootstrap

### ISSUE THREAD

**Issue by HofiOne** [mstarke/MacPass#448]
a not too informative failure happens during carthage bootstrap.

[~/Develop/Others/MacPass](master)$ carthage bootstrap --platform Mac
*** Cloning HNHUi
*** Cloning KeePassKit
*** Cloning Sparkle
GitHub API request failed: DoesNotExist

cloned the currently latest git version, followed the instructions on the opening page.
it happens on osx 10.11.4 (15E65) using Xcode 7.3 final

**Comment by mstarke** [comment]
please take the time to look for duplicates. See #447

**Comment by mstarke** [comment]
And I just did a clean setup like stated in the readme and everything works fine.
