### ISSUE TITLE
Global autotype stops working

### ISSUE THREAD

**Issue by magebarf** [mstarke/MacPass#449]
Having an issue with global autotype that so far on three instances have stopped working over time.

That may sound a bit low, but seeing as I'm quite a new MacPass user that maps to a 100% reproduction rate. The recent start of usage also means all of these has been on El Capitan, 10.11.4.

After launching MacPass and issuing my global hotkey it works great! The overlay dialog stating success/failure shows up properly and I'm quickly aware that MacPass has done its thing (or at least tried to).

At some later point in time I try again, and nothing happens. No overlay, and definitely no action seems to be happening.

I'm not 100% certain, but I believe it may have something to do OS X entering sleep.

A small request that probably could fill out a few more use cases would be if i would be possible to add a "regular" menu entry doing the same thing as the global autotype shortcut? If that would be available using OS X own keyboard shortcut management would be a possible workaround.

**Comment by magebarf** [comment]
Can add that while I still have not ruled out that it has something to do with sleep mode, an "artificial sleep" does not seem to trigger it...

Currently have my process up and running with some breakpoints in place so I'll hopefully be able to determine tomorrow if its stopped working, and then on what level the breakpoints stop being triggered...

**Comment by magebarf** [comment]
Some days in an things are still running nicely and breakpoints are triggered as expected.
Will have to revert back to the released build and see if I can reproduce again. Don't know if running with debugger or the specific build type alters something here, so will do a test against baseline again.

**Comment by mstarke** [comment]
Thanks for the effort @magebarf. I have encountered the same behaviour. Autotype seems to break for release builds from time to time. It seems the hotkey does not get fired anymore. While using the debug version this happens a lot less. I even suspekt something in the setup process is broken since it sometimes works only after you change the hotkey in the settings.

**Comment by magebarf** [comment]
I've currently switched my debug run to use a release build, so hopefully I can "catch" the issue soon (unless the addition of debuginfo and hooking a debugger is enough to keep it in balance, in which case I'm leaning towards some timing related issue).

I've got breakpoints setup in 4 or 5 layers, so if it stops working we should at least find out if its confined to DDHotKey, or if its within MacPass itself...

**Comment by magebarf** [comment]
The release build running under debugger had so far shown the issue...
One thing I do notice that definitely is a different behavior while running under the debugger though is the fact that the breakpoints makes XCode be the application in the foreground, which may or may not be part of why the issue does not show up.

Currently I'm back to running latest downloaded release to see if I once again can get the autotype to stop working...

**Comment by tcz305** [comment]
using 0.6.2, autotype only works on some sites, others it says no match.

also on the sites it work, most of them the autotype at first types gibberish or something else from my clipboard, have to go back and autotype again and it works the second time

**Comment by magebarf** [comment]
Still no luck... Still get the overlay confirming success or failure each time... Unsure what conditions were met when it stopped working, but will try to figure it out...

**Comment by ArwedSchmidt** [comment]
I am unable to use that hotkey under any circumstances on my Yosemite 10.10.3. It worked only one or two times directly after installing it. Haven't been able to get to this to work again no matter what key was used. Rebooting doesn't change anything. Could there be an issue with the recording of keystrokes too?

**Comment by cdornfeldnj** [comment]
Just chiming in to report that I'm also seeing this bug on the 0.6.2 release. The global autotype hotkey worked once or twice after install, then stopped (it won't even display an overlay now). I tried changing the hotkey to a different key combination with no success. I've just started using MacPass so don't have any experience to compare with prior releases or development versions. OS X 10.11.5 here and I do use the Sleep function often, but even a cold restart doesn't allow me to use the autotype hotkey.

**Comment by bbinoy** [comment]
Not sure if this is connected to the issue, but I just noticed this behaviour (global autotype doesn't respond anymore) when I activate "Include Host for matches" in Settings/Integration. It works when the first two checkboxes are checked, but stops working when ticking the third.

**Comment by schreined** [comment]
I experienced the same thing as bbinoy. Once I only had the first two boxes checked, it started working again!

**Comment by ArwedSchmidt** [comment]
Yeah, I can also confirm what bbinoy said. That's it!

**Comment by mstarke** [comment]
Thanks for the forensic work. I'll try to fix this quickly!

**Comment by magebarf** [comment]
Very possible cause on my end as well.

Can't confirm this with 100% certainty, as I'm unaware of what the settings were way back when I reported, but I do remember tweaking those values sometime relatively close in time to hot keys stopping to work.

**Comment by mstarke** [comment]
I have tested this with a multitude of check-box-settings and (as I thought) they do not affect the hotkey behaviour as they merely change the matching semantics, the hotkey is registered regardless, so this is something unrelated, at least in the current master. I cannot make any comment on this issue regarding 0.6.2

**Comment by ArwedSchmidt** [comment]
Thanks for checking! I'm using Version 0.6.2 (12420) and toggling "Include host for matches" toggles between working and not working with same hotkey on 10.10.3 (Yosemite).

My settings are attached. Can I provide any additional information that may help to pin down the issue?

<img width="647" alt="bildschirmfoto 2016-08-15 um 15 43 32" src="https://cloud.githubusercontent.com/assets/5668209/17666159/394f3d22-62ff-11e6-93ae-17e45f2c6bb5.png">
<img width="1680" alt="bildschirmfoto 2016-08-15 um 15 43 26" src="https://cloud.githubusercontent.com/assets/5668209/17666157/39219c78-62ff-11e6-8b87-b4f8d6bddc6f.png">
<img width="512" alt="bildschirmfoto 2016-08-15 um 15 43 22" src="https://cloud.githubusercontent.com/assets/5668209/17666162/3a52275c-62ff-11e6-92a7-e263f64e80c1.png">
<img width="512" alt="bildschirmfoto 2016-08-15 um 15 43 19" src="https://cloud.githubusercontent.com/assets/5668209/17666158/39224c72-62ff-11e6-8464-0ebf07813e87.png">

Cheers,
Manuel

**Comment by mstarke** [comment]
As mentioned in #520 the issue where Global Autotype just stops working should be resolved in the current master, as this is the initial issue I'm closing this.
