### ISSUE TITLE
Entropy calculation giving odd results

### ISSUE THREAD

**Issue by magebarf** [mstarke/MacPass#450]
I quickly figured out the use of the character clases, and I think the "custom" button in combination with a open ended text field gives you all the possible input sets thinkable.

When enabling the custom field the entropy calculation seems to be slightly off though;
- By just enabling custom, with no characters entered in the text field, entropy stays same as without custom.
- With custom and a single character in the text field, entropy is calculated to 0
- With custom and a few characters entered in the text field, entropy seems to be based only on the values entered into custom, no matter if the other character classes are enabled or not.

The generated password still takes characters from all enabled fields, so functionality wise things seems to work properly though. It's mainly the "strength indicator", I believe most people will take entropy for, that is slightly off target.

Optional workaround if buggered by the number shown: Add all characters wanted to the custom field, and in such a way getting the calculation right again.

As a side question; Enabling a character by the use of the custom field, and at the same time by enabling the character case (for say letter 'a'); will that set of characters just be joined, and probability equal for all allowed characters, or would that add the letter multiple times to the input set, thus doubling the frequency of the character use?

**Comment by mariosangiorgio** [comment]
I can answer your side question. Characters probabilities are not affected, they're still equiprobable even if they're added with the custom field. If you look at the implementation of the method that combines all the character sources it merges them without keeping duplicates.
https://github.com/mstarke/MacPass/blob/master/MacPass/NSString%2BMPPasswordCreation.m#L59-L76

**Comment by magebarf** [comment]
Thanks for the pointers @mariosangiorgio 
They led me to the core of the wrong entropy calculations as well, so i put up #451 to get a fix in place.

**Comment by mstarke** [comment]
Should be fixed with #451
