### ISSUE TITLE
password not always saved unless pressing return after entry

### ISSUE THREAD

**Issue by tcz305** [mstarke/MacPass#456]
0.6.2

The password is not always saved unless pressing return after entry.

If just entering the password and moving to another field or just saving it is not always saved. On app reopen the app generated password is there instead of the user entered one.
It is usually saved when pressing enter after entering the password.

**Comment by mstarke** [comment]
This issue is related to #445 #455 #478 #485.

9ac7c93fbf4e549929d6211dee1593b4e6fa920c should fix all issues with lost data on save while text inputs still have focus
