### ISSUE TITLE
Remember last selected keyfile for database

### ISSUE THREAD

**Issue by lfaoro** [mstarke/MacPass#459]
Hello,

Thank you very much for developing this app, terrific work.
I'd like to ask if you think it could be possible to mimic the behavior of KeepassX and remember the last select keyfile for the database and automatically use it because right now I have to manually press Choose and navigate the file system every time I lock.

Thank you!

**Comment by DominusExult** [comment]
I think there is an option for that in the preferences. It's not the default since it lessens your security.

**Comment by mstarke** [comment]
@DominusExult is correct. There is a setting to remember key files for databases. It's only enabled for databases that use password and key files. So if you never set a password, MacPass won't remember the key file even if you enabled the setting.

**Comment by lfaoro** [comment]
I actually have the keyfile store on an encrypted filesystem on a usb stick, so unless the stick is in, there's no way to access it and the filesystem requires a password to access it.

I've always used this system with KeepassX, is there any reason to enforce to not allow saving of the keyfile path unless the DB has a password also? Security wise I believe it's up to the user to decide.
