### ISSUE TITLE
"Save" operation does not work. UUID Field validation problem

### ISSUE THREAD

**Issue by otheus** [mstarke/MacPass#461]
Version 0.6.2 (12420)
Mac OS Version 10.10.5.

I could manipulate entries, but the Save operation did not work. Nor did Save As... If I tried to close the database, I was prompted with "File has changed, Discard, Save" dialogue option. I clicked on Save and nothing would happen. Close again, dialogue again appears. The original steps taken are forgotten.

Subsequent attempts to repeat the steps revealed the following:

1. Duplicate entry
2. Clear UUID field
3. Attempt to save/close. 

The Save function will not work. Instead, the UUID field box is shown with some blue-shading to hint that there is a problem.  It is seemingly impossible to move select another entry or do anything else in MacPass. However, in my (unrepeatable) attempt (above), I was able to "escape" from this "modal"-like operation -- I could select other entries, but I could not use the Search function. 

Suggested fixes: 
1. Make the invalid-UUID field behavior more user-obvious.
2. Revert to last-valid-UUID if new one is invalid. 
3. If Save operation fails for whatever reason, pop-up to alert and possible reason why.

**Comment by mstarke** [comment]
The UUID field is not supposed to be editable. This seems to be an regression while switching to using model controllers for bindings instead of direct binding.

**Comment by mstarke** [comment]
If you could take a look in the log you might find an assertion an thus MacPass will not recover gracefully.
