### ISSUE TITLE
Group settings don't stick

### ISSUE THREAD

**Issue by kgrossjo** [mstarke/MacPass#462]
I have a group called "Backup".  I select it in the left-hand navigation, and then I select "Exclude from Search" and "Disable Autotype", but it doesn't seem to stick across restarts.

(After selecting the entries from the drop-down, the red "close" icon in the top left corner doesn't change to include a dot.  So I also change some random entry inside the group, which dutifully puts the dot into the close icon, then I hit Save, then I quit MacPass, then I start it again.  No dice.)

**Comment by mstarke** [comment]
What version of MacPass are you running? Custom build or 0.6.2 or even earlier?

**Comment by kgrossjo** [comment]
I've got 0.6.2 (12420).  I just checked for updates, it doesn't offer me any.

**Comment by mstarke** [comment]
It's fixed. There was a bug in KeePassKit that prevented the correct parsing of those two settings if they were set to "no"
