### ISSUE TITLE
File modified dialog repeated when file changes multiple times

### ISSUE THREAD

**Issue by eouw0o83hf** [mstarke/MacPass#464]
If MacPass has a database file open and the underlying file changes, it displays a "The database file was modified!" modal.

If the database file is modified multiple times in succession without user response to the dialog box, the dialog box will show up once for every time the file was changed, in succession.

This is annoying for a kdbx file which is stored on Dropbo and modified at various locations over a day or series of days.

**Comment by mstarke** [comment]
Nice catch, thanks :)
