### ISSUE TITLE
Autotype to a fullscreen window

### ISSUE THREAD

**Issue by everyonesdesign** [mstarke/MacPass#466]
I use Chrome in full-screen mode to browse web, and KeePass in my default separate desktop.

I focus in chrome window, then toggle to KeyPass (via Cmd+Tab keys), then select Action -> Perform Autotype, but nothing happens.

With non-fullscreen chrome window everything works just fine.

**Comment by mstarke** [comment]
I'll investigate. Chrome has the habit of not complying with OS X defaults an I already need to filter out the nameless main windows. Full screen mode might yield some more of this behaviour.

**Comment by mstarke** [comment]
Turns out chrome wasn't the bad guy. I did not search for off-screen windows, thus missing all of chrome's windows. Secondly activating a full screen app requires the use of the NSApplicationActivateIgnoringOtherApps option.

**Comment by everyonesdesign** [comment]
@mstarke Thank you very much!
