### ISSUE TITLE
"Length" slider in Password Generator window is difficult to use

### ISSUE THREAD

**Issue by jlargentaye** [mstarke/MacPass#467]
The "Length" slider is hard to use for small values (8-12), as it requires precision control considering the full range it accepts (currently 256 max). A workaround would be to let the numerical field next to it be writable, so that the user can type in the specific number they want. Currently the field is read-only, despite its widget looking like it could be writable (the "number of bits of entropy" field just below better corresponds to what a read-only field looks like).

Suggestion: make the length number next to the slider writeable. Alternatively, make the slider logarithmic, assuming a user is more likely to want control about whether to use 8 to 10 character than they are 192 to 194?

![screen shot 2016-06-13 at 3 38 15 pm](https://cloud.githubusercontent.com/assets/6608774/16025552/f47a6ca2-317c-11e6-9273-068728089431.png)

**Comment by jlargentaye** [comment]
Admittedly, this is because I'm using MacPass' password generator to generate a memorable password that I'll be typing in frequently, rather than something I'll store in MacPass.

**Comment by mariosangiorgio** [comment]
This has been already implemented, have a look at the pull request #436. It has also been merged into master so the next version will surely contain it, I don't know when it's going to be released though.

**Comment by jlargentaye** [comment]
Ah, thanks! :D
