### ISSUE TITLE
.kdbx keyfile won't open - error 1015

### ISSUE THREAD

**Issue by zam6ak** [mstarke/MacPass#470]
I recently update to KeePass v 2.34
Since then, I cannot open the keyfile with MacPass v6.2
Error I get is 1015 "Password and/or keyfile is wrong"

I keep my keyfile on Dropbox.
KeePass on my Windows PC has no issue opening the keyfile.

**Comment by mstarke** [comment]
I just created a new database with KeePass 2.34 an opened it with MacPass 0.6.2. without any issues.
Do you use a keyfile and a password or only one of both?

**Comment by zam6ak** [comment]
OK It does work.
I was specifying keyfile when in fact I only need a master pass.
My apologies for the noise.

**Comment by mstarke** [comment]
Never mind, glad it still works!
