### ISSUE TITLE
User's icons are broken in ver.0.6.2

### ISSUE THREAD

**Issue by bellerofonte** [mstarke/MacPass#471]
I have .kdbx password base with custom icon (user defined .ico file) for every entry. Since I've updated my MacPass from 0.5.2 to 0.6.2 I see standard (grey) MacPass icons instead of my icons in all groups and entries. Hope you'll bring them back asap. Thanks!

**Comment by mstarke** [comment]
Issue is fixed. Fix will be included in the next binary release

**Comment by bellerofonte** [comment]
Sounds great! Thanks!
