### ISSUE TITLE
Data lost when adding new entry before leaving current field

### ISSUE THREAD

**Issue by hugoholzwurm** [mstarke/MacPass#478]
When data is entered in a field (e.g. username or password) and then, without leaving the field, the "New entry" button is clicked, the data entered in the last field is not stored to the previous entry.

This is especially annoying when mass-adding entries:
1. Click "New entry" button in toolbar
2. Enter value in "Title" field
3. Press [TAB]
4. Enter value in "Username" field
5. Press [TAB]
6. Enter value in "Password" field
7. Click "New entry" button in toolbar --> Value of "Password" is not stored

When [TAB] is pressed after step 6, the value is stored correctly. However, this should not be necessary.

**Comment by markschwarz** [comment]
I have the same issue when simply hitting "Save" (Cmd-S) after creating an entry, which is my most common update workflow day-to-day.  

To reproduce: 
1. Add new text in the notes area of an existing entry. 
I was entering 2FA codes, which are high-impact if you misplace them and need them many years from now!
2. Hit Save.  Cmd-S.
3. Close the file. 
4. Re-open the file and find the last entry you updated.

Expected: Cmd-S saves new note data every time.
Actual: Cmd-S doesn't save new note data.  My most recent notes are not there.

Workaround: New note data is saved if you move to a second entry before saving.

**Comment by mstarke** [comment]
There are a lot of minor issues with focus lost and not saving that should have been fixed by using to a NSContoller binding but that didn't seem to have fixed all issues. Thanks for the reports!

**Comment by mstarke** [comment]
Should be fixed with 2e1e4ad5acd2364825c19c38c81e56af58e9bbe3 (commit message refers to wrong issue)

**Comment by markschwarz** [comment]
When is this likely to be published as a compiled package, either on "releases" or through Sparkle/"Check for Updates..."?  I'd like to verify, but I don't have a full XCode setup on my machine.

**Comment by mstarke** [comment]
GitHub releases are all published as binaries and are available via the sparkle updater. Regarding a new release: I did drop 10.8 support recently and added partial history support (no browsing, no restoring, but edits get pushed to history) and plan to add full support to get 0.7 released with the full feature set. I am currently focused on getting support for the upcoming version 4 of the KDBX file format finished which takes a substantial amount of my spare time. What this means for you: I hope to get 0.7 out until november! :-)
