### ISSUE TITLE
ability to hide password and still copy it

### ISSUE THREAD

**Issue by JohnTheodore** [mstarke/MacPass#480]
If I'm in a gotomeeting, or screen sharing.. I can't login to systems without exposing the password to my framebuffer. It would be nice if there was a copy button, so I can copy the password to my paste buffer, and not have to expose it to my screen ever.

**Comment by mstarke** [comment]
Can you explain this a bit? You can use shortcuts or the edit menu to copy the password without having to expose the password field. Also you can use double click on the password field for any entry in the list to copy it.

**Comment by JohnTheodore** [comment]
You're right!
