### ISSUE TITLE
[Feature request] Merge or remember pending edits when DB file changes

### ISSUE THREAD

**Issue by timkite** [mstarke/MacPass#481]
MacPass has the wonderful ability to detect when the DB changes (due to another team member editing or adding an entry, for example) and ask if you want to reload the file. This works better than the official KeePass, which doesn't alert you until you go to save, but still leads to a problem if it happens midway through an edit. It would be nice to have the option to merge changes when reloading or possibly just preserve the changes that were pending, flagging conflicts once the file reloads.

**Comment by mstarke** [comment]
This feature is possible if synchronisation is implemented. If this is done there should be an additional option "merge with my changes" or something like that. However this might require user interaction. Think of conflicts where you edited an item an someone else deleted it.

Example flow

1. **!You**: edit Entry A
1. **You:** edit Entry A
1. **!You:** delete Entry A
1. **!You:** Save Database
1. **You:** Changed Dialog, Merge Changes &#x2192; Conflict Entry A was edited after it was deleted

And thanks for the flowers (as in praise) :)

**Comment by lifepillar** [comment]
KeePassXC has a form of merging, which you might take inspiration from. I am not sure I understand your example flow, but I have tried the following:

1. Edit Entry A in KeePassXC;
2. Delete Entry A in MacPass and save;
3. KeePassXC notices that the file has changes and asks if I want to merge those changes.
4. If I say ok, edited Entry A remains as such.

If Entry A were not edited, then it would be deleted by KeePassXC.

**Comment by lifepillar** [comment]
Here for the details: https://github.com/keepassxreboot/keepassxc/pull/93.

**Comment by mstarke** [comment]
Thanks for the tipps, KeePass has synchronizations strategies as well and I try to replicate those to get feature parity.

**Comment by mstarke** [comment]
Current continuous has Synchronisation support. On first change you will get a dialogue that asks what to do. You can set a default behavior in the dialog or in the settings. Manual merge is also possible via a File > Merge with…

**Comment by timkite** [comment]
The synchronization works great! Awesome feature!
