### ISSUE TITLE
Keepass2 windows auto-type overrides are dumped after saving file with Macpass

### ISSUE THREAD

**Issue by Strangelovian** [mstarke/MacPass#483]
1. compile macpass from origin/head on 2016/07/30
2. load file generated with keepass2 containing auto type overides for some entries
3. save (without any modification done in macpass)
4. load the file again with keepass2: the auto type overrides are gone

(I found out, and then confirmed by exporting kbd2 files to xml: only the auto type overrides are missing, all of them)

**Comment by mstarke** [comment]
Thanks for the bug report. I'll try to fix this quickly.

**Comment by Strangelovian** [comment]
You are welcome.
Thank you for writing this software

Le lun. 1 août 2016 09:06, Michael Starke <notifications@github.com> a
écrit :

**Comment by mstarke** [comment]
You found a good one there, I have refactored all the strings to use constants and have changed the case on the auto type element. MacPass did store since this commit a Autotype element. But KeePass uses AutoType. Have fixed this in KeePassKit. MacPass will use the new version as well.

**Comment by Strangelovian** [comment]
Thank you for the fix.

I updated, and I indeed confirm the whole AutoType tag is now kept with the keepass2 case.
However, some nodes underneath AutoType are still lost / altered  after saving with macpass, as with the following example.

Before saving with macpass:
```
<AutoType>
	<Enabled>True</Enabled>
	<DataTransferObfuscation>1</DataTransferObfuscation>
	<DefaultSequence>{PASSWORD}</DefaultSequence>
	<Association>
		<Window>Changer le mot de passe - Battle.net - Mozilla Firefox</Window>
		<KeystrokeSequence>{Password}</KeystrokeSequence>
	</Association>
</AutoType>
```
After saving with macpass:
<AutoType>
	<Enabled>True</Enabled>
	<DataTransferObfuscation>0</DataTransferObfuscation>
</AutoType>

i.e. DataTransferObfuscation value is changed to 0, DefaultSequence is deleted, Association node is deleted.

Also for:
```
<Group>
	<EnableAutoType>false</EnableAutoType>
	<EnableSearching>false</EnableSearching>
</Group>
```
becomes:
```
<Group>
	<EnableAutoType>null</EnableAutoType>
	<EnableSearching>null</EnableSearching>
</Group>
```

Last one: all LocationChanged nodes are updated with the current date, whereas they previously held a past date different for each entry before saving.

That's pretty much it. I hope I listed the last remaining save discrepancies for you :+1:

**Comment by mstarke** [comment]
I'll did some tests but wasn't able to reproduce all the data loss this might take some more time. About the null-false change, that was a bug in my tool function that converted all false values to inherit which is represented as null in the database. I'll try to get to the test asap and I'll let you know if you can help me out!
