### ISSUE TITLE
Notes not saving when hitting Cmd+S while focused on notes input field

### ISSUE THREAD

**Issue by maslennikov** [mstarke/MacPass#485]
To reproduce the bug, try to change notes of an existing entry and immediately after typing the notes text hit Cmd+S and then close the database file or quit the app. After re-opening, the entry will be unchanged.

When modifying the notes text and removing focus from the input field before hitting the Cmd+S shortcut, the behavior is correct.

**Comment by markushartmann** [comment]
I have the same bug an can reproduce it. Version 0.6.2 (12420), MacOSX 10.10.5
Thanks for this software.

**Comment by mstarke** [comment]
should be fixed with 2e1e4ad5acd2364825c19c38c81e56af58e9bbe3
