### ISSUE TITLE
Save state is lost on field edit focus change

### ISSUE THREAD

**Issue by giowck** [mstarke/MacPass#487]
When editing an existing field, the application detects correctly a change but on focus change the state is lost, please see the following screenshots with steps to reproduce this:

![step 1](https://cloud.githubusercontent.com/assets/7037248/17481621/728cc5fe-5d7e-11e6-99b7-1d072393cc85.png)
![step 2](https://cloud.githubusercontent.com/assets/7037248/17481623/729510ba-5d7e-11e6-948a-9c3df778f839.png)
![step 3](https://cloud.githubusercontent.com/assets/7037248/17481622/728e0702-5d7e-11e6-847c-2e3093962e0a.png)

1. Open database
2. select and edit a field of an exiting record
3. during input, change is detected and signaled on the close button (dot inside close button)
4. on focus change this state is lost (ie. no dot on close button)

Thanks for this great application

**Comment by DominusExult** [comment]
I think this bug got even worse: 
- Changing an existing field and then closing MacPass via red button will not trigger the save dialog (even though the title bar says "Edited").
- Changing an entry will not make MacPass change the title bar to "Edited" unless you change fields

**Comment by mstarke** [comment]
It's not worse since the state is auto-saved. Reopen the file and the edited state ist still present but the changes are also there. I'm still struggling in fixing the other bug in a reasonable manner without having to jump to many hoops.

**Comment by DominusExult** [comment]
Ah, I see. Thanks for pointing that out.

**Comment by mstarke** [comment]
Should be fixed with 2e1e4ad5acd2364825c19c38c81e56af58e9bbe3
