### ISSUE TITLE
Copy password supporting?

### ISSUE THREAD

**Issue by gloryluu** [mstarke/MacPass#489]
I think it would be better it supports copy password without reveal it.

**Comment by thy1985** [comment]
you can simply double click on the password entry in the (search result) list to have password put to clipboard AFAIK, same for username etc.

**Comment by gloryluu** [comment]
Thank a lot for your supporting @thy1985.

**Comment by mstarke** [comment]
Or you can use the right-click menu on the entry in the list and copy a lot more (Username, Custom Fields, etc.)
