### ISSUE TITLE
basic auth

### ISSUE THREAD

**Issue by thy1985** [mstarke/MacPass#490]
hi

is it possible to authenticate somehow against basic auth dialogs in the browser using autotype with the global hotkey, e.g. Safari?

Title matching is not working as the title is set only when the page is loaded after authentication (or it is still set to the previous page visited in the same tab).

MacPassHTTP + Passafari doesn't help as the basic auth is modal dialog.

Thanks for any hint!

Cheers,

**Comment by mstarke** [comment]
The current workaround is to switch to MacPass, select the Entry and then use "Perform Autotype" in the context menu. It might be useful to think of a better workflow for this behaviour. It might be possible to implement this feature with a native Safari extension…

**Comment by thy1985** [comment]
Thanks for the reply. This is what I currently do besides using shortcuts instead of context menu. 
Hmm. An extension based on MacPassHTTP I assume? That would be the second one then...  That is why I tried Passafari as I assumed it would work with Passafari. Maybe it would make sense to include that into Passafari. However it might be easier (yet more time consuming) to create yet another Plugin for that specific use case for oneself

**Comment by mstarke** [comment]
I was talking about a native Safari Extension that would use a custom mechanism to talk to MacPass but this is another huge discussion, as it includes splitting responsibilities, maybe adding a helper background application, etc. I have no idea if a normal browser extension is able to fill out those forms. What I've read on this topic on the AgileBits (1Password) forums leads me to believe, it's not possible. But Chrome at least seams to have an API for those purposes.

**Comment by thy1985** [comment]
yeah, sounds a bit like overkill. :) btw, is autotype considering the URL field of entries meanwhile? (I only used Windows Associations, so windows titles so far. I think for keepass URL is considered for mathcing as well)
If URL is used for matching wouldn't it be possible to enumerate the Safari Tabs (or better just pick the foremost one) and match the URL (not title) of the tab (contains()) against the URLs of entries?

**Comment by mstarke** [comment]
To clarify some of the mechanics:

Global Autotype is a generic system that uses window the title of an application to determine what to do. It matches the Window title agains the entry title field. Autotype via the context menu just uses the last app that was in use before you switched to MacPass and performs the auto type with the entry you selected - you as the user perform the match. Global Autotype tries to eliminate that step by using the front most apps window title and then looking for an entry that matches. You can chose what fields of an entry are considered for matching via the preferences:

![screen shot 2016-08-17 at 16 02 24](https://cloud.githubusercontent.com/assets/58428/17739047/05f82b28-6494-11e6-90ed-08ec800871e0.png)

But be aware that the input stays the same - the window title! The majority of use cases is however a browser window but for those there's no special treatment. Every application is just a number of windows with titles. That's it. It makes the system very limited but also very versatile. You can use it for other tools besides the browser as well. For those special cases inside the browsers, there's the KeePassHTTP (MacPassHTTP) interface used by browser extensions. The browser extension is a custom piece of software able to query more elaborately. E.g. it can - and does - use the url parameter. It even splits the url and uses the full url and then retry it with subsets. But this has nothing to do with Global Autotype.

**Comment by thy1985** [comment]
I understand all of the above. and I use global autotype based on window title for all kind of apps including browsers which is normally not an issue and works fine with different keepass tools across multiple platforms. Only the basic auth is a challenge because the title is either the default "Favoriten" or the title of the previous page. I am just thinking if I can make me stick to a "new tab for basic auth sites" rule and simple set "Favoriten" as a workaround for Window title. As I have just four of them the multiple entries found dialog is not overloaded and it is still faster then the semi-manual process.

But what I meant with my previous post was: Is it possible to change this behavior:
```
[..]
by using the front most apps window title and then looking for an entry that matches.
[..]
But be aware that the input stays the same - the window title!
[..]
```

to (if possible):
```
if (noMatchFound && fronMostWindow == Safari)
{
  Match against URL of active tab in safari //exception for Safari, URL instead of title
}
```

Due to "on no match found" condition it would not keep MacPass from showing default behavior when the title of Safari (which is equal to the title of the active tab) or any other window/app is matching and only consider URL instead when there is anyway no match via title (and it is Safari). If also this is not resulting in a match there is no match.

For sure I cannot really judge if the following can be realized:
 a) frontMostWin==Safari?
 b) getUrlofActiveTab

For sure I would understand if you would not want to introduce a exception for a specific app when you consider this "unclean" (no Sonderlocke/Extrawurst ;))
