### ISSUE TITLE
AutoType does not work with multiple windows of the same app (Updated from 0.5.1 to 0.6.2)

### ISSUE THREAD

**Issue by tgroeneveldlg** [mstarke/MacPass#491]
Hi,

I have found that AutoType does not work any longer when e.g. having two windows of Firefox.
One title has the right one, where I am focused on. 
The other has a different title (In this case a window with SSL Network Extender)

It keeps telling me there is no match for SSL Network Extender (which is a small window in the background controlling the Java App for VPN)

I will try to figure out, what might be causing the focus issue, however, in 0.5.1, this issue was not apparent.

Thanks, Tom.

**Comment by schreined** [comment]
I've ran into a similar issue, but is tied to using the Chrome Hangouts extension. If I have a Hangouts window open, autotype will never find a match. I close the chat windows, and it works! I've been able to replicate this multiple times.

**Comment by mstarke** [comment]
There were numerous fixes with Autotype in 0.7 that should have fixed this. If the bug still occurs, please re-open the issue.
