### ISSUE TITLE
The latest released version is quite old

### ISSUE THREAD

**Issue by mariosangiorgio** [mstarke/MacPass#492]
The latest released version is 0.6.2, which is six months old and 81 commits behind master right now.

It would be great to set up continuous integration (I see someone looked into Travis CI into #402) and get more regular releases with the new features and bug-fixes.

**Comment by mstarke** [comment]
MacPass is singed to offer a better security (or someone to blame if shit hits the fan). CI builds cannot offer this but this might be a better tradeoff than a slow release cycle

**Comment by Jellyfrog** [comment]
@mstarke you can code sign via travis, for example; https://www.objc.io/issues/6-build-tools/travis-ci/

**Comment by rtvb** [comment]
I don't have Xcode installed, so cannot build my own binary (and don't know how to). How can I get the latest release (now and regularly afterwards) ? Anxious to see what has improved over the last months. I am aware that this is still alpha software.

**Comment by ParadiseDS** [comment]
Thought it might be good to add a homebrew formula for MacPass to handle the building of HEAD, as the `--HEAD` option is supported in many formulas. All dependencies could also be resolved by this way conveniently.

**Comment by mstarke** [comment]
Extracted @ParadiseDS comment to separate Issue #522

**Comment by mbrucco** [comment]
I'm interested to have a newest release... I tried to compile sources... but it fails. I'm not an expert of Xcode.

**Comment by enterfornone** [comment]
Few days ago on 22 Feb, we marked a sad anniversary.
For all of us who cannot build from a binary, there is now one full year with no release. No bug fixes, although they seem to be fixed in the nightly builds (like custom icons, custom sort).
Nevertheless, I'm happy that development seems to be ongoing and hope to soon see 0.7 version released.

**Comment by mbrucco** [comment]
Can you paste link, please?

**Comment by mstarke** [comment]
@mbrucco if you're looking for a link to a newer release, there is none.

**Comment by alexbde** [comment]
I'm really looking forward to see a new release. Is there some chance of getting one in near future? :)

Could you otherwise just release your current version and mark it as nightly? Looks like there are a bunch of people who would try it on own risk ;)

**Comment by compuguy** [comment]
@alexbde I think that would be an acceptable compromise.

**Comment by alexbde** [comment]
@mstarke What do you think? :)

**Comment by mstarke** [comment]
I did test travis-ci for nightlies and will try to supply them soon.

**Comment by mstarke** [comment]
There's now a nightly build. Check [continuous](https://github.com/mstarke/MacPass/releases/tag/continuous) in the releases.
