### ISSUE TITLE
Password Generator doesn't disappear in inspector

### ISSUE THREAD

**Issue by aicpp** [mstarke/MacPass#493]
I clone latest commit 654103e and build with guide on README.
Then I open record. In inspector push button to generate password. The tooltip window opens and I can use it (all controls works).
But I can't close it after that. Buttons 'Cancel'/'Use password' not helps.
Only Cmd+Q helps to exit app.

Note: last release version `MacPass-0.6.2-alpha.zip` works normally.

My environment:
```
OS X 10.11.6 (15G31)

carthage version
0.17.2

brew --version
Homebrew 0.9.9 (git revision cb700; last commit 2016-08-23)
Homebrew/homebrew-core (git revision bcb4a; last commit 2016-08-24)

xcodebuild -version
Xcode 7.3.1
Build version 7D1014
```

**Comment by mstarke** [comment]
This is fixed in e06ade6a8f6c5f6e5ad1f2416cf98f3f61039854
