### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by shad0whawk** [mstarke/MacPass#494]
I was hoping someone could tell me how to resolve this error that I keep getting when I try to build this program in Xcode.  I've included an image of the error.  In a nutshell, it's referencing an object that doesn't exist in of the files.  The error states, "No visible @interface for 'KPKGroup' declares the selector 'addToGroup:at index:'.  I'm not sure how to resolve it.  Any ideas?
![screenshot](https://cloud.githubusercontent.com/assets/6074105/18188006/826eed1c-706b-11e6-8242-75b2d08208fe.jpg)

**Comment by mstarke** [comment]
This seems to stem from a wrong version of KeePassKit. Does a ```carthage update``` on the Macapass directory fix the issue?

**Comment by shad0whawk** [comment]
Thank you for pointing me in the right direction.  I had to use the "carthage update" process to update the file.  I appreciate it!
