### ISSUE TITLE
Support KDBX 4.0 Format

### ISSUE THREAD

**Issue by mstarke** [mstarke/MacPass#495]
Keepass will introduce KDBX 4.0 as a new file format. KeePassKit and subsequently MacPass should add support for the new format.

**Comment by 9point6** [comment]
Will this include support for Argon2, too?

**Comment by mstarke** [comment]
KDBX4 uses it so yes, it has to.

**Comment by 9point6** [comment]
Ah brilliant. I didn't know if it was a required dependency or not

**Comment by mstarke** [comment]
Just an update. KeePassKit can read KDBX4 files. Writing is in the works. And as a bonus support for Twofish encryption is added as well.

**Comment by mstarke** [comment]
Writing KDBX4 files is working also. There was a mayor issue with the way MacPass wrote the hashed stream so Keepass on windows did complain that the file is corrupted (which it technically wasn't) other clients (like KeeWeb) were able to read the file as well as MacPass. I did update the error handling since MacPass did continue silently when this error occurred.

**Comment by mstarke** [comment]
Support ist present, but I just realized that the test coverage is not as good as I want it to.

**Comment by mstarke** [comment]
Tests extended.
