### ISSUE TITLE
Auto-type sends {ENTER} even if specifically omitted in custom sequence.

### ISSUE THREAD

**Issue by dsowinski** [mstarke/MacPass#496]
Hello,

When one needs to have a custom auto-type sequence that waits for user input after putting in all the data in correct fields (such as username and password+token auth) MacPass currently prevents this by sending {ENTER} after each sequence. This works as intended with KeePassX, hence I believe it is a bug in MacPass. Please have a look into this issue.

Thanks!

**Comment by mstarke** [comment]
MacPass should not send an enter after each sequence. If you use a custom sequence please take a look at its keystrokes. If there is indeed no enter an it's the one used for a match this is a bug. Can you create a demo database to verify the bug an attach the file?

**Comment by dsowinski** [comment]
Please disregard this. I did some digging and turns out a combination of spaces and "|" in window title associations were causing MacPass to match wrong entry. Both entries are for the same application, just different hosts. After removing all spaces and non alphanumeric characters in both entries and replacing them with "*" it now matches them correctly. Thanks.

**Comment by mstarke** [comment]
👍
