### ISSUE TITLE
AutoType in incorrect window after unlocking

### ISSUE THREAD

**Issue by natemara** [mstarke/MacPass#499]
## Steps to reproduce
1. Open Google Hangouts app in Chrome
2. Put Chrome in Desktop 1, MacPas in Desktop 2
3. Lock MacPass
4. Navigate to login page in Chrome
5. Hit AutoType keyboard shortcut
6. Type MacPass master password
## Expected Behavior

Password is typed in login page, and I am logged in
## Actual Behavior

Username + password + {ENTER} is typed in google hangouts window, sending my username/password to whoever I last sent a message. This has happened several times, and is not only frustrating because of the required password change, but embarrassing.

**Comment by mstarke** [comment]
That's a nasty bug. The way auto type works is storing the front most app, activation MacPass, then restoring the front most app again and send the key strokes. This should reactivate the last window you used in chrome. I'll try to find a way to fix this!

**Comment by mstarke** [comment]
I just checked. If I tab back to chrome, the last window gets the focus, if i click on the Chrome icon in the Dock, the hangouts window is in front. I have to find out how to get the app in front with the "tab to it" behaviour instead of the "activate" behaviour.

**Comment by mstarke** [comment]
Forget any previous comments - I just tried to reproduce this in the old 0.6.2 and it did work properly.

**Comment by mstarke** [comment]
This is custom Chrome behaviour. Even Keepass on windows seems to have the exact same issue: https://sourceforge.net/p/keepass/feature-requests/2182/
