### ISSUE TITLE
Make Lock shortcut Cmd-L (and/or configurable)

### ISSUE THREAD

**Issue by jlargentaye** [mstarke/MacPass#502]
On Macs, shortcuts are habitually done using the Cmd (⌘) key. Thus, the intuitive shortcut for Locking a database would be Cmd-L, instead of the current Ctrl-Shift-L, which I'm always fiddling around trying to find. As far as I can find, Cmd-L isn't already used by the application or system-wide.

FWIW, my usage has me focusing the MacPass window, finding a relevant entry and double-clicking the password field to paste in an application.

**Comment by mstarke** [comment]
Valid point on shortcuts manly being cmd based on macOS. The default had a reason that currently doesn't come to me. You can however change every keyboard shortcut of every app in the system preferences of macOS. This is also the place to add missing ones.

**Comment by jlargentaye** [comment]
Thanks! I didn't know of the system-wide override possibility. I've now done that as a workaround.

**Comment by mstarke** [comment]
Changed to Cmd+L in d9f74938d0e79366be1736c538638c4678f6d11f

**Comment by graciano** [comment]
Hi, I installed version 0.6.2 and this shortcut is not working for me. (I'm a new mac user, so I'm not sure if this should work by default)

**Comment by jlargentaye** [comment]
Hi @graciano, 0.6.2 was released in Feb 2016, before this commit was made. You'd need to build from latest HEAD to get this.

**Comment by mstarke** [comment]
@graciano the system preferences allow for full customization of shortcuts on nearly any macOS application. So even if MacPass isn't providing a default you can create one for yourself.
