### ISSUE TITLE
Virtual desktops are being rearranged after unlock + autotype

### ISSUE THREAD

**Issue by Nightmaren** [mstarke/MacPass#504]
Note: I am a fairly new mac user so I may be doing something wrong or using the wrong terminology.
I am using MacOS Sierra. MacPass Version 0.6.2 (12420).

Until MacPass is able to minimize to tray, I have been "maximizing" the MacPass application so that it is on its own virtual desktop. I usually have two more virtual desktops while going about my daily work, for a total of 3 desktops that I can swipe between.

Example:
<Finder/Main Desktop> <Microsoft Word, maximized> <MacPass, maximized>

Say I launch a Safari window in the desktop with Finder open. I'll navigate to a website and press my autotype key combination (control+command+p). My mac automatically scrolls to the desktop containing MacPass because the database is locked from inactivity. I type in my unlock password and the mac automatically scrolls back to the desktop with Safari in it and performs the autotype as expected. Excellent! This is just how I would expect it to work.

However, after this, I notice my desktop order has been rearranged (by sliding three fingers up on the touchpad). My desktop order is now changed as follows:
<Finder/Main Desktop> <MacPass, maximized> <Microsoft Word, maximized>

It does this without fail -- the MacPass desktop gets moved to be after the desktop that used autotype. Expected behavior would be for the desktop arrangement to not change.

I apologize if I did not explain something properly -- please let me know if I can clarify anything. Thank you!

**Comment by mstarke** [comment]
My guess is that this has nothing to do with MacPass at all. Take a look at your "Mission Control" preferences. The fist check box allows Mission Control to rearrange spaces.

I just tested this on my system with the box checked, the behaviour is as you describe, with the box unchecked, all the spaces stay neatly at their place.

![screen shot 2016-10-12 at 11 47 57](https://cloud.githubusercontent.com/assets/58428/19305592/e8fb1a12-9071-11e6-90bc-ab10712f384b.png)

**Comment by Nightmaren** [comment]
It is exactly as you describe. Unchecking the box fixed it. Thank you very much! I apologize for the inconvenience -- I'm still learning the ins and outs of mac :)
