### ISSUE TITLE
"The document ... could not be saved" error on lock

### ISSUE THREAD

**Issue by fjl** [mstarke/MacPass#505]
I use MacPass built from 024e9cf41a4bdfa375909ffe3c24c317290e5837 and this message appears every time the database is locked.

**Comment by mstarke** [comment]
This actually was a pretty bad bug resulting in data loss on lock!
The problem was that ```[NSDocument saveDocument]``` was issuing the save after the database was locked resulting in missing data. This bug seems to be only occurring on 10.12. On 10.11 I did not encounter this behaviour (even with the 10.12 sdk)

**Comment by fjl** [comment]
Thanks for fixing this so quickly.

**Comment by mstarke** [comment]
If you still find anything strange happening on lock/unlock  please reopen the issue and report it, in case I did miss something!

**Comment by yaoxinghuo** [comment]
![image](https://cloud.githubusercontent.com/assets/69723/19373785/5dff74ba-91f9-11e6-857a-1e3a8b8e255a.png)
Hi, I build MacPass with the fix, when I locked the database, the error alert did disappear, but can not unlock the database any more unless quit MacPass and try again, error message is: Unknow file format(1001), the screenshot attached.

**Comment by mstarke** [comment]
@yaoxinghuo I somehow do not see your comment - did you delete it? You should be able to lock/unlock with 58df7fe7c6cc24d14aa6b320da91b488acaef9ca. The initial fix ee33dcaaf827c2ea331c67a664d84cca120882ad was unable to previously locked database as you encountered because of bad early return.

**Comment by yaoxinghuo** [comment]
@mstarke Sorry to bother you, yes, I build with your first commit and encountered the lock/unlock problem, I rebuild with your latest commit, it worked, so I delete my comment... Thanks for you time:)
