### ISSUE TITLE
Safari plugin

### ISSUE THREAD

**Issue by Sosoyan** [mstarke/MacPass#509]
Is there anyway to get safari integration?

**Comment by mstarke** [comment]
There is a port of Passifox for Safari but I have no information on the current state of this port. You can use MacPassHTTP to get it to work. Another way is to use global autotype since it's the method that should work with any application without special plugins.

**Comment by mlazowik** [comment]
Duplicate of #77?

**Comment by mstarke** [comment]
It is…
