### ISSUE TITLE
Autotype not resolving field references

### ISSUE THREAD

**Issue by ojwm** [mstarke/MacPass#511]
Hi, I hope someone can help with this or fix the bug (if it is a bug). Thanks.

### Version
0.6.2 (12420)

### Steps To Reproduce
1. Create entry Test1 with:
   * Username = test
   * UUID = xxxx   (just a dummy value for this example)
2. Create entry Test2 with:
   * Username = {REF:U@I:xxxx}
   * Autotype window association for Notes app, with sequence: {USERNAME}
3. Focus Notes app
4. Perform global autotype

### Expected Outcome
"test" typed in Notes

### Actual Outcome
"{REF:U@I:xxxx}" typed in Notes

### Other Comments
Performing Copy Username, on the Test2 entry, and pasting into Notes does correctly put "test" in Notes instead of the field reference "{REF:U@I:xxxx}".

**Comment by mstarke** [comment]
I'm pretty sure this is already fixed in the current master version but I'll double check an see if this is still valid. The upcoming 0.7 release should then include the fix.

**Comment by tknerr** [comment]
same here, just to confirm the behaviour that @ojwm described in 0.6.2

**Comment by tknerr** [comment]
@mstarke any ETA on a potential 0.7 release?

**Comment by tknerr** [comment]
@mstarke status ping :-)

**Comment by mstarke** [comment]
For anyone interested in the current status, check out the continuous build. Autotype should resolve references correctly. On the subject of 0.7. I'm onto wrapping all ends up and reading the update.

**Comment by tflo** [comment]
Just noticed this bug too. With Version 0.7 (20171019141024-continuous).

– Tom

**Comment by mstarke** [comment]
Bug is localised in KeePassKit reference/placeholder resolving which is naive in it's current implementation.

**Comment by mstarke** [comment]
Fixed in current master. Will Ben made available shortly in continuous.
