### ISSUE TITLE
databased changed notification not dismissing

### ISSUE THREAD

**Issue by avidmills** [mstarke/MacPass#513]
If I update my database on another computer, MacPass notifies me. The issue is when I click okay to update the database locally, the notification doesn't dismiss. There are a couple other times I have had this problem, but I can't remember the exact popups.  I am on the Nov. 10 commit, or possibly the one before that.

**Comment by avidmills** [comment]
If I connect with a new browser, the keepasshttp dialog that creates a connection key also doesn't dismiss.

**Comment by mstarke** [comment]
The first issue is a MacPass issue, the second one a MacPassHTTP, right?

**Comment by mstarke** [comment]
The first issue results in the introduction of auto save. This might have broken things at other places as well.
