### ISSUE TITLE
"Include Host for matches" breaks Global Autotype functionality and feedback

### ISSUE THREAD

**Issue by braham-snyder** [mstarke/MacPass#520]
There are at least two existing issues for broken Global Autotype: #279 #449

Despite at least one of them mentioning this very specific bug, they've both become catch-all issues with many posts, so I've created this narrower issue.

Checking the box for "Include Host for matches" breaks Global Autotype for at least a handful of people (mentioned in the prior issues). In my case, when pressing my Global Autotype hotkey, no text is input by Autotype, and the usual feedback (match or no match) is not given. This is despite no change in an otherwise-working entry. MacPass is still consuming the hotkey event--i.e., the hotkey doesn't register elsewhere (in, e.g., Karabiner's EventViewer)--but nothing else seems to occur.

At this point, I'm currently able to get normal functionality back by unchecking that same "Include Host for matches" box. I'd previously thought that un- and re-checking "Enable Global Autotype" was additionally necessary to fix the problem, but I'm not seeing that currently.

Thanks for MacPass!

e: I suppose I should add that I'm on El Capitan, but this bug has been reported in Yosemite as well (#449)

**Comment by mstarke** [comment]
I took the time to look into this. It has nothing to do with a special setting inside MacPass. Hotkey registration breaks completely, if the integration preferences tab is left open. The event gets consumed as you describe by DDHotKeyCenter but it fails to find any registered hotkeys and thus does not invoke Global Autotype. I'll dive into this and hope to fix it soon.

**Comment by mstarke** [comment]
I have identified Problems with DDHotKey deregistering. This is fixed now but I think I should change to another Shortcut system (ShortCutRecorder for example has a way better UI and seems to be better supported)

**Comment by mstarke** [comment]
The fix is introduced with d9122859195999b1270c3b050d87a3325922d709

**Comment by mstarke** [comment]
@braham-snyder could you test this fix?

**Comment by braham-snyder** [comment]
appears to work for me--thank you!

**Comment by mstarke** [comment]
I'm closing this. If Global Autotype still seems to be broken, we'll get reports eventually.
