### ISSUE TITLE
Font of username field

### ISSUE THREAD

**Issue by macmenco** [mstarke/MacPass#521]
When having to enter the username on a site/phone the username is sometmimes hard to read when it contains an I (capital `i`) or l (lowercase `l`). The password field uses another font it seams. It would be nice for the username field to use the same font as the password field.

**Comment by mstarke** [comment]
Fixed in 6987cbf2e2daafaa13da9830aeef4b5376684081. The font for the username field is change to be monospace so it should be better to distinguish the characters.
