### ISSUE TITLE
Global Autotype should have options to manually search for credentials by editing the URL or Title

### ISSUE THREAD

**Issue by belaviyo** [mstarke/MacPass#525]
Current global autotype mostly cannot detect credentials based on window title and its URL. At least in Chrome I cannot even login into GitHUb with the global autotype. I always get "No Match!" warning.

I assume it is hard to find the URL of the currently selected tab using this technique. If so, it would be nice it there was a search-box in the floating window that user can modify the detected URL. I believe this makes the global autotype more useful.

**Comment by mstarke** [comment]
This sounds more like the area for a dedicated browser plugin (like MacPassHTTP or something else).
If you turn the order around, you can get into your Github account, just use normal auto type.

Open GitHub in your browser, highlight the user field, got to MacPass, select the GitHub account (via search or manually) and then use Autotype in the Context Menu or via Shortcut and MacPass should fill in your credentials.

**Comment by belaviyo** [comment]
Thanks for the reply.

> If you turn the order around, you can get into your Github account, just use normal auto type

That's what I am doing right now. Still it is pretty tedious task when it comes to find serval passwords per day.  

> This sounds more like the area for a dedicated browser plugin (like MacPassHTTP or something else).

I might start working on a browser extension then.

**Comment by belaviyo** [comment]
@mstarke I was looking at the HTTP handlers that KeePassHTTP accepts from the extension side and noticed `get-logins` only accepts URL matching. Seems like there is an open issue to allow custom search as well https://github.com/pfn/keepasshttp/pull/227. I was wondering if this new handler will be supported by MacPass as well or not

**Comment by mstarke** [comment]
Since this is a KeePassHTTP issue, it should be discussed here: https://github.com/MacPass/KeePassHTTPKit. Support should be no problem. https://github.com/MacPass/MacPassHTTP has to use the new KeePassHTTPKit to support the additional requests.
