### ISSUE TITLE
Setting password length in generator

### ISSUE THREAD

**Issue by whitehat101** [mstarke/MacPass#526]
![image](https://cloud.githubusercontent.com/assets/1093593/21486807/bd813f90-cb6f-11e6-8f0f-0cf47e1af32d.png)

Currently the password length is only settable by dragging the dial. The numeric "20" in the box is not editable. It would be excellent if it was. When a website tells me I can't use a password, because their max length is *N*, I'd like to be able to type *N* instead of having to drag the bar to find *N*.

**Comment by mstarke** [comment]
This is already implemented. See #415

**Comment by whitehat101** [comment]
Ah "already implemented" in an unreleased version. Should we expect 0.7 soon?

**Comment by schauder** [comment]
I have version `0.711 (23550)` and still have the same problem

**Comment by mstarke** [comment]
0.7.11 allows for manual input of the lenght - the input field looks disabled, just click inside and it should work!
