### ISSUE TITLE
Select /root group on opening

### ISSUE THREAD

**Issue by s7nio** [mstarke/MacPass#527]
If I open a kdbx file no group are selected and no items are visible in the main view. That makes it not user friendly. Alternative select automatically the search field.

**Comment by mstarke** [comment]
The master has selection restoration partly implemented. This will select the last selected group in the outline. In the 0.7 release it should work as you suggest. The fallback to the search field is another highly requested feature which should be added.

**Comment by mstarke** [comment]
Also see #519
