### ISSUE TITLE
No Match for Focus Proxy on Global Autotype

### ISSUE THREAD

**Issue by fooman** [mstarke/MacPass#538]
There seems to be a difference in window matching between the latest master and the 0.6.2 release. Using the same database and settings Version 0.6.2 (12420) is able to find and offer the correct match but Version 0.6.2 (14270) only comes back with the new slide in notification "No Match for Focus Proxy".

The database was created using keepassx and has multiple Window Associations (which I believe are not yet editable but are taken into consideration for matching) for the entries I need. However even without looking at the Window Associations there should be enough other information available to find a matching entry (title, url).

**Comment by mstarke** [comment]
14270 is the current master and you can edit window associations in this build.
Focus Proxy is the window title that is looked for. There were some changes to the lookup of the window title but nothing should break. Can you give me some more details on what app you try to use autotype on?

**Comment by fooman** [comment]
Thanks for the quick response. I am currently not seeing any way to edit the Window Associations:

<img width="1678" alt="screen shot 2017-01-17 at 11 16 28" src="https://cloud.githubusercontent.com/assets/455508/22000859/7fa15474-dca6-11e6-9dec-7b149a7274ef.png">

To me there seems no obvious way to add anything to that field, clicking, right-clicking or via some menu entry.

>can you give me some more details on what app you try to use autotype on?

I am trying to autotype into Chrome

**Comment by fooman** [comment]
Ok did some further tests:

Using a new database with only a single entry with title matching the window title Global Autotype works well. I get the pop up message "Macpass Match!" and I am logged in :-)

Using my existing kdbx2 database I run into trouble.

First difference I now have multiple matches for this website which I believe is due to the now considered window associations which exist in the database:

The page is
Login | Xero Accounting Software 
but it also matches this window association:
Login | Mailchimp

Selecting the correct entry I can see the following happening:
It switches the window to Macpass (which didn't happen in the single entry database)
When I switch back to Chrome I see a failed login, from what I can work out from the logged request it only entered the correct username but not the password (autotype sequence is the same throughout and a manual autotype works)

**Comment by mstarke** [comment]
@fooman There actually might be a bug in the matching since Window titles should match exactly. Or use ```*``` as a wildcard.

For the Window-Associations, you stumbled over an UI inconsitency. The top part above the notes field is a scroll window if you scroll down or resize the notes you get some more usefull UI controlls:

![screen shot 2017-01-17 at 11 30 33](https://cloud.githubusercontent.com/assets/58428/22016986/a6fcb44e-dca8-11e6-905b-89fe2e0c4bf3.png)

**Comment by fooman** [comment]
Thanks @mstarke - that indeed clears up my inability to edit the window associations. Noticed that some commits in KeePassKit so will see if I can rebuild and try again.

**Comment by LightServant** [comment]
I'm having the same issue with global Autotype in Safari. Firefox works just fine, but it appears actual versions of safari return the value "Focus Proxy" as Window-Title instead of the current Tab Title. Hence, there are no machtes.

**Comment by LightServant** [comment]
As a follow up: Firefox doesn't work as well. It seems the window-title is fechted from the first tab in the window. So if I have a firefox session with multiple tabs and I have a first tab with e.g. Facebook and a second tab with Github, and I want to perform global autotype on the second tab, macpass will find Facebook as a match and fill in the wrong account credentials.

**Comment by mstarke** [comment]
There are various enhancements to autotype window title retrieval and handling in the current continuous build. Can you verify if the issue is still valid?

**Comment by fooman** [comment]
I updated to 0.7.1 and it's working well for me. Thank you Michael.
