### ISSUE TITLE
Autotype crash (with fix) and incorrect output.

### ISSUE THREAD

**Issue by timewasted** [mstarke/MacPass#543]
I rebuilt master today (e8d5e301421f989741652cf337a6ef0035472a30), and noticed that performing auto-type would cause the program to crash.  I traced it down to commit c9b3637c24e508d99cbaffb65ce45b4f396c1e91.  Specifically, MPKeyMapper.m line 103 is incorrectly using `sizeof(modifiers)`.  It is returning the size of the array (54), instead of the number of elements (7).  The simple fix is to change that to `sizeof(modifiers) / sizeof(modifiers[0])`, which will fix the crash.

However, the next issue is that the output is getting mangled.  I have tried with two different passwords, and they're both getting mangled in a consistent manner.  The first is an 11 character password, and password[6] is outputting `§` instead of the expected `0`.  The second is a longer, more secure password, and a couple of the symbols are getting swapped with other symbols.  I have not looked into why/where this is happening, but it is a relatively recent issue.

**Comment by mstarke** [comment]
I should really start using a development branch :). I began rewriting the MPKeyMapper to allow for modified keys to be used as well and I seem to be breaking things in the meantime.

**Comment by mstarke** [comment]
Regarding your problems with the wrong characters being typed, do you use Obfusctation on Autotype?

There's a bug in the current system that misses modifiers. This has the following effect when obfuscation is enabled:

Consider the following password: `!Pa§$wørD`
For a german keyboard this requires the following key presses:
⇧+1, ⇧+P A, ⇧+3, ⇧+4, W, ⌥+O, R, ⇧+D
 
MPKeymapper would fail to resove  `!, §, & and ø` so the obfuscation would fall back to copy&paste which would yield all the right characters. Now MPKeyMapper will find the mapping but the current Autotype ignores the modifiers. It only is able to find upper case letters and adds the shift key.

Can you verify that observation? Could you tell me what keyboard layout you use?

**Comment by mstarke** [comment]
@timewasted could you take a look at fef22bce05838c71c98354d2d9f229b4c1d7b0a7 and check if Autotype now works again?

**Comment by timewasted** [comment]
Aha, it does indeed work again!  Perfect!
