### ISSUE TITLE
Autotype - allow space key

### ISSUE THREAD

**Issue by shastry** [mstarke/MacPass#547]
On certain login pages, there's a need to toggle checkbox - usually with the space bar.

On macOS, there's no way to to this.

On Linux (Fedora 25), typing a literal space in the autotype sequence seems to work.

Keepass apparently allows {SPACE} - http://keepass.info/help/base/autotype.html
Can this be implemented?

**Comment by mstarke** [comment]
This should already be working in 0.6.2. the current master hast definitive support either dir the literal space ` ` as well as the `{SPACE}` command.

**Comment by shastry** [comment]
I'm terribly sorry @mstarke. I posted in the wrong project! (It was meant for keepassxc).
