### ISSUE TITLE
Custom keybinds for copy username/password

### ISSUE THREAD

**Issue by mjurenka** [mstarke/MacPass#556]
Hi,

I want to tell you first of all, you all did a great job in this piece of software. Because of you, I no longer need Wine and standard Keepass. Keep up the good work!

Now for the feature. It would be great, if there would be an option for setting custom keybinds for copy username and password. Personally I would change the keybinds to CMD+Shift+C and CMD+Ctrl+C, so I don't have to put my thumb off the CMD button and I personally think this shortcut is more Mac-like, as there are not many (if any) system shortcuts that use CMD and Alt at the same time.

Thank you for this piece of software.

P.S. I will probably for this and rewrite the shortcut for my own use, but I think it would benefit more users as a config option. Peace!

**Comment by mstarke** [comment]
You can change all keyboard shortcuts in the system settings of macOS for any application. For more information please take a look at the apple documentation: https://support.apple.com/kb/PH25377

**Comment by websocket98765** [comment]
The Apple link broke. New link: https://support.apple.com/guide/mac-help/use-global-keyboard-shortcuts-mchlp2262/mac

I also find the default shortcuts confusing.

Personally I would vote for:
- copy username: cmd + B
- copy password: cmd + C
- _open_ URL: cmd + U
- _open_ URL & autofill: cmd + T
- autotype: <remove for security reasons; should always open URL first & only fill if URL matches>

(I've updated mine in MacOS preferences, but 1.) fewer customizations would mean less set up when getting a new computer, 2.) easier to recommend MacPass to friends/family who are less tech savvy--they wouldn't want to add custom keymaps, they would just not like the recommendation and would use something else.)
