### ISSUE TITLE
MacPass ignores group settings from other clients

### ISSUE THREAD

**Issue by weslly** [mstarke/MacPass#559]
When changing search and auto-type group settings using other clients (Keepass 2.x, KeepassX/XC), MacPass resets the search and auto-type to inherit from the parent settings.

**Comment by mrudolf** [comment]
It seems even worse, MacPass does not even save group settings set in the application. For example if you set search to "Exclude from search", save, quit and restart, it is reset to "Inherit Search Settings"

**Comment by mstarke** [comment]
There was a comparable issue a while back with wrong ordered popups seems that this is an regression.

**Comment by mstarke** [comment]
fixed in develop branch.
