### ISSUE TITLE
Need to view history

### ISSUE THREAD

**Issue by Sec42** [mstarke/MacPass#560]
Today I ran into an issue where I needed to check the password history for an entry. It seems that MacPass is lacking such an option.

I found Bug #179 which says that the history is there. It would be really useful if there was a way to look at it.

**Comment by mstarke** [comment]
History support is in progress for 0.7. 0.6.3 does not create history entries on edit but will keep the ones already in the file.

**Comment by mstarke** [comment]
Feature is implemented and working in the current continuous build
