### ISSUE TITLE
Keyfile rejects password (1015)

### ISSUE THREAD

**Issue by paulrbts** [mstarke/MacPass#563]
I recently moved my kdbx file and when I tried to reopen it I get the following message:

> The password and/or keyfile is wrong (1015)

The password isn't wrong (believe me, it really isn't), neither is the keyfile. I've tried moving it back to the original location but it still won't have it.

Version 0.6.2 (12420)

**Comment by paulrbts** [comment]
OK, think this may have been user error :-(

It's working now.

**Comment by mstarke** [comment]
Can you pinpoint what went wrong?

**Comment by paulrbts** [comment]
Sure.

As I said, I moved the kdbx file to a new location. Next time I opened MacPass: on the opening screen I chose the location for a keyfile, thinking it was the same as the kdbx (I was thinking of telling it to look for the new kdbx file location). It rejected the password on the basis that it and the keyfile were wrong/didn't match.

By selecting no keyfile, it accepted my password.
