### ISSUE TITLE
Issue with auto-update

### ISSUE THREAD

**Issue by Zettt** [mstarke/MacPass#567]
MacPass produces an error when trying to auto-update, at least on my machine.

```
Update Error!

MacPass can’t be updated when it’s running from a read-only volume like a disk image or an optical drive. Move MacPass to your Applications folder, relaunch it from there, and try again.
```

MacPass is in `/Applications`. I have installed it by moving it from the downloaded file.

**Comment by mstarke** [comment]
This error is generated by Sparkle the Auto Update framework. Do you have write access to the /Applications folder? When you moved MacPass did Finder prompt you for a password input?

**Comment by mstarke** [comment]
It seems to be a know Issue with Sparkle and macOS 10.12. See https://github.com/sparkle-project/Sparkle/issues/923

**Comment by mstarke** [comment]
This seems to be fixed with an update to Sparkle. Regardless this will be pushed to 0.7 soon.
