### ISSUE TITLE
Use KeePass regular keyboard shortcut

### ISSUE THREAD

**Issue by Deuchnord** [mstarke/MacPass#571]
I'm a user of the original KeePass when using Windows and KeepassX when using Linux, and I find quite strange and not user-friendly the fact MacPass is using totally different keyboard shortcuts.
Below is a comparison between KeePass(X) and MacPass.

<table>
<tr>
<th>Command</th>
<th>KeePass & KeePassX</th>
<th>MacPass</th>
</tr>
<tr>
<td>Copy the username</td>
<td>Ctrl + B</td>
<td>Cmd + Shift + C</td>
</tr>
<tr>
<td>Copy the password</td>
<td>Ctrl + C</td>
<td>Cmd + Alt + C</td>
</tr>
<tr>
<td>Autotype username and password</td>
<td>Ctrl + V</td>
<td>Cmd + Ctrl + A</td>
</tr>
</table>

Is it possible to use the same keyboard shortcuts (eventually with Cmd instead of Ctrl) as in KeePass(X)? Or at least propose a way to change the keyboard shortcut in preferences?

**Comment by lifepillar** [comment]
You may try System Preferences > Keyboard > Shortcuts > App Shortcuts, and define your keyboard shortcuts there.

**Comment by Deuchnord** [comment]
Oh, I didn’t know this feature of macOS’s! Thanks!
Looks like the menu isn’t showing the correct shortcut after defining it, but it works like a charm :)

**Comment by cipnt** [comment]
Agree – consistency across platforms and clients would be ideal

**Comment by mstarke** [comment]
Since you can remap them via the System Preferences I'll consider this as closed.

**Comment by Kapulara** [comment]
How do we do this now? This doesn't seem to work.
