### ISSUE TITLE
Mixed content breaks encryption on static page

### ISSUE THREAD

**Issue by elsesiy** [mstarke/MacPass#579]
Hey there,

I just noticed that due to the usage of the flattr-API on http, the whole connection to the [static page](https://mstarke.github.io/MacPass/) is not encrypted. 

Even though there's no sensitive data being exchanged, it's worth at least mentioning it so it can be fixed in the future.

<img width="193" alt="screen shot 2017-05-01 at 22 13 37" src="https://cloud.githubusercontent.com/assets/7075075/25593072/7bb3adaa-2ebb-11e7-97ac-d9bec3d3dfb8.png">

Cheers!

**Comment by mstarke** [comment]
Fixed. Thank you!

**Comment by elsesiy** [comment]
You're welcome 👍
