### ISSUE TITLE
delete seems to delete all entries within a group

### ISSUE THREAD

**Issue by gghose** [mstarke/MacPass#581]
When I hit the delete key it applies to all entries, not just the selected one.

**Comment by mstarke** [comment]
The delete key is not associated with delte but `⌘+←`. Did you remapt the keys?
What Version of MacPass? Custom build or 0.6.2 binary release? I am unable to reproduce this behavoir with the current HEAD of develep

**Comment by gghose** [comment]
This is really weird..... Now I can't replicate the bug......... I have no
explanation. It was the binary 0.6.2. release, by the way.

**Comment by mstarke** [comment]
Since 0.6.2 is so old I close this until you can reproduce it. Then please reopen the issue!
