### ISSUE TITLE
[Feature Request] Tabbed view for multiple Databases 

### ISSUE THREAD

**Issue by dennis-f** [mstarke/MacPass#583]
Would be great if I could open multiple databases without having multiple windows.

**Comment by mstarke** [comment]
If you run MacPass under 10.12 you already get that for free. I have no plans to implement a custom version for earlier releases.

You can show the tab bar (View > Show Tab Bar) and then use the + Button to add a new Tab. If multiple windows are open, you can drag them to the tab bar to attach them or drag them out, just like in Finder or Safari.

To get this behaviour all the time, you have to set "Prefer tabs when opening new documents" to "always" in the Dock settings:
![screen shot 2017-05-09 at 13 09 39](https://cloud.githubusercontent.com/assets/58428/25848118/3056a28c-34b9-11e7-9a24-3a5b9e46aea3.png)

And voila, every time you open a new file or create a new document it opens in a tab.
![screen shot 2017-05-09 at 13 10 24](https://cloud.githubusercontent.com/assets/58428/25848125/34598b38-34b9-11e7-8481-b9436ce6807c.png)

**Comment by dennis-f** [comment]
This is awesome!! Thank you very much!

**Comment by perfusorius** [comment]
Just a quick tip for anyone who don't wants to change global tab settings just to change MacPass behavior (like me):
Completely close MacPass, open the terminal and enter:
`defaults write com.hicknhacksoftware.macpass AppleWindowTabbingMode always`
From now on in MacPass every file will be opened automatically in a new tab (unless it is already opened).
