### ISSUE TITLE
Unable to open database in other apps: Duplicate custom attribute found

### ISSUE THREAD

**Issue by lifepillar** [mstarke/MacPass#586]
This seems to have happened after I deleted a few entries from my db. After saving the document with MacPass and trying to open it with KeePassXC or KeePassX, I get this error: *Unable to open the database: Duplicate custom attribute found*. KeeWeb tells me instead:

    KdbxError: Error FileCorrupt: no key encryption rounds in header

Any idea how I can repair the file, if at all possible?

**Comment by lifepillar** [comment]
Btw, using MacPass 0.6.2 (12420).

**Comment by lifepillar** [comment]
I've gone to File > Database Settings… > Security tab and noticed that “Key encryption rounds” was set to 0. After clicking on Benchmark and saving the document again, I was able to open it in KeeWeb. KeePassX and KeePassXC still refuse to open it, though.

**Comment by lifepillar** [comment]
As a workaround, I have modified the file in KeeWeb and saved it. After that, I was able to open it with all the apps.

**Comment by mstarke** [comment]
If you still have the broken file you could try to export it to xml. If there are indeed duplicate custom keys that's a hard error on MacPass. KeePassKit has change significantly since 0.6.2 so I think this behavior is fixed. Sorry for the inconvenience!

**Comment by lifepillar** [comment]
I do have some XML export. They are pretty big. In which section(s) should I look for “duplicate custom keys”?

**Comment by mstarke** [comment]
My only guess are entries with duplicate attributes. Take a look at the list of
```
<String>
 <Key></Key>
 <Value></Value>
</String>
```
nodes under each entry node. If there are duplicate keys you found the error.

**Comment by mstarke** [comment]
The keys should not be any of the default ones like: Title, Password, etc.

**Comment by lifepillar** [comment]
Ok, I'll take a look. In the meantime, I've spent some time cleaning up my password file, and I was not able to reproduce the problem.

**Comment by mstarke** [comment]
I'll took a look at KeePassXC and the error can only appear, if an Entry has a duplicate Key. Keys are compared case sensitive, so ```UserName``` != ```Username``` != ```username```. Again, the KeePassKit code of MacPass 0.6.2 has been changed a lot so this might not ever occur again on the current code base.

**Comment by mstarke** [comment]
Any progress?

**Comment by TimJDFletcher** [comment]
I am getting a similar error of duplicate attachment, in a relatively clean (3 months old) database.

I think this maybe related to a previous issue around multiple layers of gzip on certain files.

Looking at the files that I have which have been gzip'd multiple times I can see that the entry also has a history count of between 3 and 6.

**Comment by mstarke** [comment]
Can you elaborate on the duplicate attachments bug?

**Comment by TimJDFletcher** [comment]
I have a keepass DB with a mix of passwords and SSH keys (in pem format), I have previously been bitten by bug #590 meaning my PEM keys have multiple layers of gzip. 

Opening this file in KeepassXC I get the error of: "Unable to open the database: Duplicate attachment attribute found."

Looking at those entries they are showing a number of items in history in the UI and poking at an XML export I show a number of identical keys eg: `<Key>Infrastructure.pem</Key>`. These are layered inside an entry of the same name, I'm not sure if this is relevant here.

**Comment by mstarke** [comment]
This should be correct, since an entry can have multiple history entries with the same attachment.
But a history entry is not allowed to have nested history. The structure looks as follows:

```xml
<Entry>
    <Binary>
      <Key>Text.txt</Key>
      <Value Ref="1"/>
    </Binary>
  <History>
    <Entry>
      <Binary>
        <Key>New.rtf</Key>
        <Value Ref="0"/>
      </Binary>
    </Entry>
    <Entry>
      <Binary>
        <Key>New.rtf</Key>
        <Value Ref="0"/>
      </Binary>
      <Binary>
        <Key>Text.txt</Key>
        <Value Ref="1"/>
      </Binary>
    </Entry>
  </History>
</Entry>
```

Can you take a look at your xml structure and see if this matches. If MacPass also messes up this structure there's a serious bug that I need to locate so any help is highly appreciated.

**Comment by lifepillar** [comment]
I have not been able to reproduce the duplication issue any longer (good!), so I can't help further with that. But I've got again a `no key encryption rounds in header` error in KeeWeb with a recently created file. Btw, this time the file worked fine in KeePassXC. The fix consisted in setting “Key encryption rounds”, as I had explained above. So, it seems that originally I had two separate issues.

Regarding the problem I have just described, is there a reason why the default for Key encryption rounds in MacPass should be zero? Or is it even a good idea? See also https://github.com/keeweb/keeweb/issues/502.

I am still on MacPass 0.6.2, so please forget this if key encryption rounds are set to a higher default in the current version.

**Comment by lifepillar** [comment]
> My only guess are entries with duplicate attributes. Take a look at the list of
> nodes under each entry node. If there are duplicate keys you found the error.

I had this error again, so I was able to investigate it further. The problem was a KeePassHttp entry containing duplicate AES Key values. Something like this (some values are obfuscated):

```
      <Entry>
        <UUID>XXXXXXXXXXXXXXXXXXXXXX==</UUID>
        <IconID>0</IconID>
        <ForegroundColor/>
        <BackgroundColor/>
        <OverrideURL/>
        <Tags/>
        <Times>
          <LastModificationTime>2017-09-20T12:59:53Z</LastModificationTime>
          <CreationTime>2017-04-03T20:08:04Z</CreationTime>
          <LastAccessTime>2017-06-26T20:02:40Z</LastAccessTime>
          <ExpiryTime>4001-01-01T00:00:00Z</ExpiryTime>
          <Expires>False</Expires>
          <UsageCount>0</UsageCount>
          <LocationChanged>2017-10-18T08:30:20Z</LocationChanged>
        </Times>
        <String>
          <Key>Title</Key>
          <Value>KeePassHttp Settings</Value>
        </String>
        <String>
          <Key>UserName</Key>
          <Value/>
        </String>
        <String>
          <Key>Password</Key>
          <Value ProtectInMemory="True"/>
        </String>
        <String>
          <Key>URL</Key>
          <Value/>
        </String>
        <String>
          <Key>Notes</Key>
          <Value/>
        </String>
        <String>
          <Key>AES Key: 26A391DD-XXXX-YYYY-WWWW-XXXXXXXXXXXX</Key>
          <Value>xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx=</Value>
        </String>
        <String>
          <Key>AES Key: 26A391DD-XXXX-YYYY-WWWW-XXXXXXXXXXXX</Key>
          <Value>xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx=</Value>
        </String>
        […]
```

Since I have switched to autotype, I have not used KeePassHTTP any longer. So, after deleting this entry, the issue has disappeared.

This does not look like a MacPass bug then, but you may consider adding a check for duplicate entries.

**Comment by mstarke** [comment]
Thank you for the digging. The UI of MacPass does resolve this issue by always enforcing unique keys. This is something KeePassKit should enforce at the model level as well to prevent malformed content.

**Comment by mstarke** [comment]
KeePassKit now updates duplicate keys (instead of rejecting them all together). However there seems to be another issue in KeePassHTTPKit or MacPassHTTP yielding the duplicate key in the first place.
