### ISSUE TITLE
[Bug] Remember Key Option does not work

### ISSUE THREAD

**Issue by dennis-f** [mstarke/MacPass#587]
Checking or unchecking the checkbox for the "remember key file"-option has no effect on the used databse. 

When closing the database, the password-field is always checked and the select-field is always empty.

(I'm using german language, so maybe the feature is called slightly different)

Running `Version 0.6.2 (12420)`

**Comment by mstarke** [comment]
What version are you're running?

**Comment by dennis-f** [comment]
I updated the post. It's 0.6.2

**Comment by mstarke** [comment]
Can you test if this is still the case with a current snapshot (using the continuous release)?

**Comment by dennis-f** [comment]
Behaviour is still the same with continuous release version 😢 . You can follow with these Steps:

- open macpass
- select the database
- uncheck password
- choose key file
works
- cmd + Q
- open macpass again
- database is selected
- password is checked again
- select field is empty > should contain last used key file

**Comment by mstarke** [comment]
Problem solved:
<img width="512" alt="screen shot 2017-06-21 at 13 52 07" src="https://user-images.githubusercontent.com/58428/27383033-78ff7116-5689-11e7-9387-24907ba27824.png">

This is disabled on purpose. I can enable it but if you do not store the key on an external source that you always unplug when closing the database this effectively removes any protection from opening the database.

**Comment by dennis-f** [comment]
ahhh i see. i'm sorry for the inconvenience.

**Comment by mstarke** [comment]
No problem :)
