### ISSUE TITLE
Crash after Quicklook preview

### ISSUE THREAD

**Issue by cipnt** [mstarke/MacPass#588]
Whenever I use the preview feature on an attached file, the Quicklook window launches ok but when I close it MacPass crashes.
I presume MacPass attempts to delete the temporary file after I close the quicklook and that causes an error.
Quicklook is extremely useful even though a potential security risk.

`*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'launch path not accessible'
terminating with uncaught exception of type NSException
abort() called`

**Comment by mstarke** [comment]
That is a known issue. The delete task uses ```srm``` which was removed in macOS 10.12. This is already fixed in the master/develop branch.

**Comment by mstarke** [comment]
Fixed with #507
