### ISSUE TITLE
Attachments getting compressed with multiple layers of gzip

### ISSUE THREAD

**Issue by TimJDFletcher** [mstarke/MacPass#590]
I have a keepass DB that has a small number of SSL cert + key pairs in as well my usernames and passwords.

When I save the files from MacPass to my local FS to use them the files are compressed with Gzip, however it is multiple layers in my most recent case 22 layers of gzip.

I attached the file as a simple plain text PEM file (certname.pem), I suspect that MacPass is compressing the file each time I save the DB

**Comment by mstarke** [comment]
What Version of MacPass are you using? Did you create the file in another tool?

**Comment by mstarke** [comment]
I have tried to replicate this but am unable to do so. Using no compression and GZIP compression on the file, multiple edits and save wich 0.6.2 as well as the current develop branch always save the file as unzipped text.

**Comment by TimJDFletcher** [comment]
I'm using Version 0.6.2 (14480) built from source I have gzip compression enabled on the DB, I'll generate a new DB and test again to get a clearer bug report

**Comment by mstarke** [comment]
Found the bug. KeePassKit did incorrectly compress already compressed files again.

**Comment by TimJDFletcher** [comment]
In case anyone else has the problem I've written a short bash script that will loop over and decompress files exported from Keepass.

https://gist.github.com/TimJDFletcher/6b4f81661573510ffaeb5036e8561dc0
