### ISSUE TITLE
Save discards custom icons and (KeePass) plugin data

### ISSUE THREAD

**Issue by KFDCompiled** [mstarke/MacPass#591]
When saving a database, MacPass will discard custom subfolder icons and reassign a default icon. However, entity custom icons are preserved. 

Also while saving, MacPass will discard data associated with KeePass plugins, e.g., SSH key data for the KeePass KeeAgent plugin.

I think the fix has to do with keepasskit logic when it encounters unexpected data and will submit pull request if i can get it fixed.

**Comment by mstarke** [comment]
The custom icon UUID was never written by KeePassKit. Fixed already! Regarding plugin data, can you elaborate?

**Comment by mstarke** [comment]
As mentioned in #590 attachments were wrongfully compressed multiple times. This should fix both of the issues!
