### ISSUE TITLE
Insecure update error

### ISSUE THREAD

**Issue by Nes-si** [mstarke/MacPass#597]
With new release ("continuous") there is an error:
![monosnap 2017-06-12 21-50-59](https://user-images.githubusercontent.com/5188972/27049959-995b7e68-4fb9-11e7-9782-7607c85aa6c1.png)
This window appears periodically.

**Comment by mstarke** [comment]
The continuous release is a snapshot of the current code not like the actual releases. The up

**Comment by mstarke** [comment]
The continuous releases now have Sparkle disabled so this error will not pop up anymore!
