### ISSUE TITLE
Continuous build doesn't work with MacPassHTTP

### ISSUE THREAD

**Issue by 9point6** [mstarke/MacPass#598]
According to the MacPassHTTP repo, this could be due to an API incompatibility -

would it be possible to set up a continuous build of MacPassHTTP against the continuous build of MacPass?

**Comment by mstarke** [comment]
Of course it's possible. I'll set it up if I find the time for it.

**Comment by goofy79** [comment]
this will be very nice

**Comment by mstarke** [comment]
Done. MacPassHTTP continous release now works with MacPass continuous
