### ISSUE TITLE
Changing password and switching entry does not count as a "change" and will not prompt to save the DB

### ISSUE THREAD

**Issue by owl70** [mstarke/MacPass#599]
Editing an existing entry, change password, select another entry (important!), select "Quit MacPass". Application closes without saving new database, or prompting to save the database.

**Comment by mstarke** [comment]
I assume you're running 0.6.2? Can you test this with the continuous release (backup files before use!!!) and see if it still occurs?

**Comment by owl70** [comment]
Problem exists in 0.6.2.
Works in 20170613-continuous.

**Comment by mstarke** [comment]
Then I'll close this.
