### ISSUE TITLE
Keepass File won't open

### ISSUE THREAD

**Issue by ThomasSHA** [mstarke/MacPass#602]
Hi, I'm currently playing around with creating my own little keepass viewer on android.
Trying to open "my" files with MacPass doesn't work. When I click unlock, nothing happens.

In Console.app i found the following:
`(
	0   CoreFoundation                      0x00007fff8ba3957b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00007fffa0c7d1da objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff8bab6c55 +[NSException raise:format:] + 197
	3   Foundation                          0x00007fff8d411fc6 -[NSData(NSData) initWithBase64EncodedString:options:] + 84
	4   KeePassKit                          0x000000010a4d3d3d -[NSUUID(KPKAdditions) initWithEncodedUUIDString:] + 80
	5   KeePassKit                          0x000000010a4d3cd1 +[NSUUID(KPKAdditions) kpk_uuidWithEncodedString:] + 69
	6   KeePassKit                          0x000000010a4b9671 -[KPKXmlTreeReader _parseMeta:metaData:] + 1388
	7   KeePassKit                          0x000000010a4b8c30 -[KPKXmlTreeReader tree:] + 900
	8   KeePassKit                          0x000000010a4f4c21 -[KPKKdbxUnarchiver tree:] + 2503
	9   KeePassKit                          0x000000010a4bff00 +[KPKUnarchiver unarchiveTreeData:withKey:error:] + 133
	10  KeePassKit                          0x000000010a4b630d -[KPKTree(Serializing) initWithData:key:error:] + 61
	11  MacPass                             0x000000010a3ae64e -[MPDocument unlockWithPassword:keyFileURL:error:] + 226
	12  MacPass                             0x000000010a390460 __47-[MPDocumentWindowController showPasswordInput]_block_invoke + 117
	13  MacPass                             0x000000010a394e19 -[MPPasswordInputController _submit:] + 259
	14  libsystem_trace.dylib               0x00007fffa17903a7 _os_activity_initiate_impl + 53
` etc.

It would be great if you could tell me what's wrong. 

(Keepass, KeepassX, KeepassXC can read "my" files without any problems)

**Comment by mstarke** [comment]
The error suggest a base64 encoding NSData does not understand. What version are you running?

**Comment by mstarke** [comment]
The error occurs while trying to load the metadata and specifially when trying to pares a UUID data string. This might be an error when the string is not set. The normal way for keepass is to use null UUIDs for unset values.

Can you supply the `<Meta></Meta>` part of your  file?

**Comment by mstarke** [comment]
Found the error. You Meta part is missing the keys. KeePassKit assumes those are present. This should not cause an exception. Thanks for the nice find!

**Comment by ThomasSHA** [comment]
for completeness: the missing element was at least one of those: 

- EntryTemplatesGroup
- EntryTemplatesGroupChanged
- LastSelectedGroup
- LastTopVisibleGroup

With them added, MacPass opens my files as well ;)

**Comment by mstarke** [comment]
KeePassKit now does not fail if UUIDs are missing in the ```<Meta>``` part of the KDBX document.
