### ISSUE TITLE
Values disappear on saved entry

### ISSUE THREAD

**Issue by fabstei** [mstarke/MacPass#605]
I have one saved entry that continually looses it's values. The first couple of times I assumed I had forgotten to properly save, but now I'm certain that the values get lost. The entry itself is still there, the title stays, but everything in the "Notes" section disappears.

I never observed the problem with any other field. This is the only field where I did not save anything in the "Password" field and just used the "Notes". Right now I added a dummy "Password" entry - let's see if it stays saved.

Let me know if I can do anything to help debug.

**Comment by fabstei** [comment]
A quick update: Setting the password does not prevent the information stored in "Notes" from disappearing.

**Comment by mstarke** [comment]
This behaviour is a known mayor bug in 0.6.2. Can you see if it still occurs in the continuous build?

**Comment by workflo** [comment]
At least for me, the bug seems to be gone, now.
In my case _Notes_ were not saved when I just hit Cmd+S Cmd+Q without explicitly unfocussing the text area before saving. With the current master it works :)

**Comment by mstarke** [comment]
@fabstei can you confirm this?

**Comment by fabstei** [comment]
I just tested it and can confirm that this seems to solve the issue.
