### ISSUE TITLE
Duplicate entry appears twice in context menu

### ISSUE THREAD

**Issue by notoriousturtle** [mstarke/MacPass#607]
When right clicking an entry, "duplicate entry" appears twice.

**Comment by mstarke** [comment]
If you look closer, one it with … at the end. The action was missing from 0.6.2 but in current continuous build you can duplicate entries with additional options.

**Comment by notoriousturtle** [comment]
Ah, should that maybe read "Duplicates Entries" then, as opposed to "Duplicate Entry..."?

**Comment by mstarke** [comment]
If you select more than one, then both should be named appropriately. But I keep by having both since one does not require user interaction and simply copies values, the other can use references but requires additional interaction which might be cumbersome sometimes.
