### ISSUE TITLE
Insecure update error!  DSA key

### ISSUE THREAD

**Issue by YouriAndropov** [mstarke/MacPass#609]
Hi,

How to update Sparkle framework when building from a git clone ?
I get an "Insecure update error" when launching MacPass.

Thanks.

**Comment by mstarke** [comment]
You should not enable Sparkle for custom builds as this defeats the purpose. You can disable the Sparkle updater via either building as Debug or setting the following environment variable: `NO_SPARKLE=NO_SPARKLE`

For example, if you build via the command line:
`
xcodebuild build -configuration release -project MacPass.xcodeproj  -scheme MacPass CODE_SIGNING_REQUIRED=NO NO_SPARKLE=NO_SPARKLE
`
