### ISSUE TITLE
Cannot Create/Edit Window Associations in 0.6.2

### ISSUE THREAD

**Issue by jasonlyle88** [mstarke/MacPass#610]
I'm a new user of MacPass (longtime user of KeePass on windows systems), so maybe I'm just missing something in the MacPass application. But, as far as I can tell, there is no way to create or edit window associations in MacPass 0.6.2.

I thought perhaps it just was not implemented, but I looked at the [Status](https://github.com/mstarke/MacPass/wiki/Status) wiki page and it lists "Autotype Window Associations (display, edit, use)" as available functionality.

Attached is a screenshot of MacPass running. I see no button for the association. Furthermore, when I opened a file from KeePass, i was unable to edit existing window associations made by the KeePass application.
<img width="878" alt="screen shot 2017-07-13 at 5 37 38 pm" src="https://user-images.githubusercontent.com/8782552/28189918-55e2789e-67f6-11e7-8b2a-56d969a8210c.png">

Maybe the window associations have something to do with the cog button next to the "Autotype Sequence" textbox... but as of right now, it just seems to toggle on and off.

Am I missing something or is this functionality broken?

**Comment by mstarke** [comment]
You're the second user to miss that scrolling is possible in the inspector. Maybe Apple should have come up with a better UI for this.

I opened MacPass 0.6.2 and resized the window a bit and there you see two buttons (+ and -) to add and remove window associations.

<img width="878" alt="screen shot 2017-07-14 at 00 22 25" src="https://user-images.githubusercontent.com/58428/28190402-0c346fc4-682b-11e7-8580-8dc0d3149739.png">

If you select on, you can then change the title and keyboard sequence for it via the lower input fields. The drop-down is populated with all current window titles but you can also type a name in the input.

**Comment by jasonlyle88** [comment]
...I feel ashamed.


Also, thank you.

**Comment by mstarke** [comment]
No worries.
