### ISSUE TITLE
Continuous Download link is reported as phishing by Google Chrome

### ISSUE THREAD

**Issue by christianhuening** [mstarke/MacPass#615]
This link https://github.com/mstarke/MacPass/releases/download/continuous/MacPass-continuous.zip is reported as phishing by Google Chrome. Is there anything you could do about that?

**Comment by mstarke** [comment]
Not for me. And I have no clue how Chrome comes to this conclusion.

**Comment by christianhuening** [comment]
well ok , will report is at false positive then
