### ISSUE TITLE
Forgetting Search/Autotype settings

### ISSUE THREAD

**Issue by alcesleo** [mstarke/MacPass#624]
First of all - awesome project! I use it every day and it works great, thank you!

It seems to forget the search/autotype settings of groups and always default them to "Inherit Search Settings" for example. The settings work fine as long as you are logged in, but it doesn't seem to save them. Is this a known issue? 

I'm using Version 0.6.2 (12420)

**Comment by MacPass-Travis** [comment]
Known issue fixed in continuous build
