### ISSUE TITLE
New database has expiration settings set to 0

### ISSUE THREAD

**Issue by gagarine** [mstarke/MacPass#630]
Even after changing password the message "The database password expired!" pop-up at every save.

The problem is new database have an expiration settings set to 0:

![screen shot 2017-08-12 at 13 11 14](https://user-images.githubusercontent.com/164074/29240171-fe0ad5ae-7f5f-11e7-87f6-861733e276ae.png)

I think sane default would be to recommend change after 30 days and never force change. In the message "The database password expired!" it should be added that expiration value can be changed in the database settings.

Similar to #418

**Comment by mstarke** [comment]
This was a bug in an earlier release, this should not be present in any current builds.

**Comment by gagarine** [comment]
I was using 0.6.2.

**Comment by gagarine** [comment]
Fixed in Version 0.6.2 (20170825120842-continuous)
