### ISSUE TITLE
Moving a item by Drag&Drop from one groupe to another do not move the right item

### ISSUE THREAD

**Issue by gagarine** [mstarke/MacPass#631]
Moving a item by Drag&Drop from one groupe to another do not move the right item

How to reproduce:
- select an item in a group
- drag&drop to another group

Result:
- the item is not moved
- another (random?) item is moved in the target group

Expected
- move the selected item in the target group and remove it from is original group.

**Comment by MacPass-Travis** [comment]
What version are you using? 0.6.2. or the continuous build?

**Comment by gagarine** [comment]
0.6.2. Where I can download continuous build?

**Comment by mstarke** [comment]
It's not offered via software update, you have to manually download it in the [releases section](https://github.com/mstarke/MacPass/releases)

**Comment by gagarine** [comment]
Ok I will test it when I found some spear time. Thanks.

**Comment by mstarke** [comment]
Did you find the time to test this again?

**Comment by Luxas85** [comment]
Oh yes didn’t I answered on bithub? Everything is fine now! Thank you! 
I just saved a file with the current windows version and opened it with macpass.

That worked fine.

Thank you.

**Comment by mstarke** [comment]
This seems to be the wrong issue. Did you mean #632

**Comment by gagarine** [comment]
Yes it works on Version 0.6.2 (20170825120842-continuous) if you select one item and try to move it to another group (moving multi-item at once doesn't seem to be supported yet, but it's another issue.).
