### ISSUE TITLE
Open database with password file

### ISSUE THREAD

**Issue by ElizarovEugene** [mstarke/MacPass#635]
I want to open the password database using a password file. To do this, it is necessary to choose each time (the original KeePass remembers let to the file) and to remove the checkbox "password"

**Comment by mstarke** [comment]
This is working as intended. I did opt to remove keyfile remebering when no password is set. It was requested by others to remove this restriction so I will consider updating the behaviour to work even when no password is used.

**Comment by mstarke** [comment]
A detailed explanation for the rationale can be found here: #587

**Comment by mstarke** [comment]
If it's still highly wanted to remember key files regardless of the password of a database please open a separate feature request.
