### ISSUE TITLE
Fails to drag and drop sometimes on macOS 10.13

### ISSUE THREAD

**Issue by Jellyfrog** [mstarke/MacPass#639]
When dragging an item, the moment it enters the sidebar/group-tree area the following can be seen in console/xcode:
```
*** Canceling drag because exception 'NSInvalidUnarchiveOperationException' (reason 'value for key 'tags' was of unexpected class 'NSArray'. Allowed classes are '{(
    NSString
)}'.') was raised during a dragging session
```

![macpass](https://user-images.githubusercontent.com/759887/29892363-96344410-8dce-11e7-8c8d-d66af731d0ec.gif)

**Comment by sicbb** [comment]
same here :/ macOS 10.13 and MacPass Version 0.6.2 (12420)

**Comment by mstarke** [comment]
Found the issue. It seems that macOS 10.13 uses secure coding by default and there was a bug in decoding tags. Will be fixed with the next continuous release.

**Comment by mstarke** [comment]
Fixed in current continuous build
