### ISSUE TITLE
Autotype to a fullscreen window (or current window isn't a current window)

### ISSUE THREAD

**Issue by fzzr-** [mstarke/MacPass#641]
macOS: 10.12.4 (16E195)
MacPass: 0.6.2 (20170825120842-continuous)

- - -

Steps to reproduce:

- prepare the Window:
    - run any program (Safari, Terminal, anyone else with tabs)
    - make fullscreen its window
    - open preferences popup ![screen shot 2017-08-31 at 17 15 27](https://user-images.githubusercontent.com/888526/29927802-1305d232-8e70-11e7-89b6-20f8fc4770c4.png)
    - change some preferences
    - close the preferences popup
- prepare the MacPass:
    - create some items for this Window
- reproduce:
    - press your "global autotype hotkey" to call MacPass to type pass in this window

**Expected result**: MacPass type the password and notify "Match!".

**Unexpected result**: MacPass can't type the password because looks into the **closed** window with title "Preferences" or "General" (name of tab in preferences).

_This is not a duplicate of #466._

**Comment by mstarke** [comment]
Should be fixed in 34c33ef008d2ff354a66313724db0468a31becdc and deployed in continuous
