### ISSUE TITLE
Autotype to some windows looks to obscure "Focus Proxy"

### ISSUE THREAD

**Issue by fzzr-** [mstarke/MacPass#642]
macOS: 10.12.4 (16E195)
MacPass: 0.6.2 (20170825120842-continuous)

- - -

Steps to reproduce:

- run Messages program (or VSCode, Telegram, sometimes Terminal in SplitView - see #641 & screenshot)
- open preferences popup
- press your "global autotype hotkey" to call MacPass to type pass in this window

**Expected result**: MacPass type the password and notify "Match!" or soothing like "No Match for {current window . title}!".

**Unexpected result**: MacPass says "No Match for Focus Proxy!".

![screen shot 2017-08-31 at 18 13 23](https://user-images.githubusercontent.com/888526/29930828-3124d102-8e78-11e7-9172-93181aa70424.png)

- - -

![screen shot 2017-08-31 at 17 08 07](https://user-images.githubusercontent.com/888526/29927583-73ccb53c-8e6f-11e7-9fb1-838a124f9046.png)

**Comment by mstarke** [comment]
Should be fixed in 34c33ef008d2ff354a66313724db0468a31becdc and deployed in continuous
