### ISSUE TITLE
Autotype to a fullscreen window in the SplitView mode

### ISSUE THREAD

**Issue by fzzr-** [mstarke/MacPass#643]
macOS: 10.12.4 (16E195)
MacPass: 0.6.2 (20170825120842-continuous)

- - -

Steps to reproduce:

[SplitView]: https://support.apple.com/en-us/HT204948

- prepare the Window:
    - run any program (Safari, Terminal, anyone else with tabs)
    - create two windows (for example we'll name it "WinA" & "WinB")
    - turn both windows to fullscreen mode
    - make [SplitView][] with its two windows ( "WinA" & "WinB")
       **with "WinB" at right side**
- prepare the MacPass:
    - create some items for this Window "WinA" (use title of window "WinA")
- reproduce:
    - activate (give it a focus) window "WinA"
    - press your "global autotype hotkey" to call MacPass to type pass in this window

**Expected result**: MacPass type the password and notify "Match!".

**Unexpected result**: MacPass can't type the password because looks only into the **RIGHT window in the SplitView** with another title - it's the "WinB" instead "WinA".

Same behaviour catches with any native apps with support Tabs and SplitView.

![screen shot 2017-08-31 at 17 53 06](https://user-images.githubusercontent.com/888526/29929978-be72bea0-8e75-11e7-8739-0ea1987f66e4.png)

**Comment by mstarke** [comment]
Should be fixed in 34c33ef008d2ff354a66313724db0468a31becdc and deployed in continuous
