### ISSUE TITLE
Autotype to a Finder's window

### ISSUE THREAD

**Issue by fzzr-** [mstarke/MacPass#644]
macOS: 10.12.4 (16E195)
MacPass: 0.6.2 (20170825120842-continuous)

- - -

![macpass finder issue mov opt](https://user-images.githubusercontent.com/888526/29931776-db5e5c72-8e7a-11e7-8bac-68bbdacdcf28.gif)

Steps to reproduce:

- activate builtin Finder.app
- open new window (⌘+n) - for this example we name it **"FirstWindow"**;
- open new window (⌘+n) - for this example we name it **"SecondWindow"**;
- in the **"SecondWindow"** go to another directory to change the title of window;
- activate (click to) **"FirstWindow"** window;
- press your "global autotype hotkey" to call MacPass to type pass in current active window

**Expected result**: MacPass type the password and notify "Match!" or soothing like "No Match for {FirstWindow.title}!".

**Unexpected result**: MacPass can't type the password because watch to the **latest created window** with another title - it's the "SecondWindow" instead "FirstWindow". It says "No Match for {SecondWindow.title}!"

[macpass.finder.issue.mov.zip](https://github.com/mstarke/MacPass/files/1267662/macpass.finder.issue.mov.zip)

**Comment by mstarke** [comment]
Should be fixed with 34c33ef008d2ff354a66313724db0468a31becdc. Continuous build includes the fix.

**Comment by mstarke** [comment]
Just a ping to nudge you to test if the bug is still present. If not, please close the resolved issues!

**Comment by fzzr-** [comment]
Yes! Thanks! Issues is totally fixed.
