### ISSUE TITLE
Let users open any file with any extension

### ISSUE THREAD

**Issue by kiwijuice** [mstarke/MacPass#646]
One of the security practices is to change the names and the extensions of your files (for example, calling the database file untitled.jpg instead of passwords.kdbx), so an intruder or a bot wouldn't give special treatment for this file, especially those that trying to find password databases.

While with KeePass and KeePassXC it is possible to open these files, MacPass doesn't allow it.

**Comment by mstarke** [comment]
The current continuous build has a checkbox allow all files in the open panel to enable the desired behavior.

**Comment by mstarke** [comment]
A side note: security through obscurity is never a good idea. If I would build a bot I would check for kdb file headers and just ignore names and extensions.

**Comment by mstarke** [comment]
Does the continuous build work as you'd expect it to?

**Comment by mstarke** [comment]
I'll close this for now since it's working in the continuous build
