### ISSUE TITLE
right-clicking a group that is in the Recycle Bin, and selecting "empty trash" results in a "are you sure?" prompt that stays over the window

### ISSUE THREAD

**Issue by hintss** [mstarke/MacPass#647]
To reproduce:

1. Right-click a group that's in the recycle bin, hit "Empty trash" (there may or may not need to be >1 group in the recycle bin for that option to show up, I didn't check):
<img width="162" alt="untitled 2" src="https://user-images.githubusercontent.com/848163/30246992-1cdd21de-95be-11e7-8254-c13f88979e9d.png">
2. It pops up this dialog, the first click on "Empty trash" will delete only the item you right-clicked, subsequent clicks don't seem to do anything:
<img width="435" alt="untitled3" src="https://user-images.githubusercontent.com/848163/30247006-62b7afd0-95be-11e7-8701-706531044cae.png">

**Comment by mstarke** [comment]
Can you clarify the version? 0.6.2 or continuous?

**Comment by hintss** [comment]
sorry about that, but uh...yes.
<img width="284" alt="untitled5" src="https://user-images.githubusercontent.com/848163/30247102-91ff3bd0-95c0-11e7-8da4-08254dcec57a.png">

**Comment by mstarke** [comment]
Fixed in cc69db11d34bb00124397e03b8d4f11093b453be. Was a KeePassKit issue
