### ISSUE TITLE
Notes doesn't get saved

### ISSUE THREAD

**Issue by stevo-knievo** [mstarke/MacPass#650]
Adding notes to folders or entries doesn't get stored.

OS: macOS Sierra, 10.12.6
MasPass: Version 0.6.2 (12420)

**Comment by mstarke** [comment]
Well known issue. Fixed in continuous build. Will get pushed out in 0.7 shortly.

**Comment by stevo-knievo** [comment]
Thank you for your quick reply @mstarke! Thanks for all your work and keep it up!!
