### ISSUE TITLE
Modifying database in MacPass corrupts it for KeePass on Windows

### ISSUE THREAD

**Issue by eddiehu** [mstarke/MacPass#655]
When I modify and save a database on MacPass, and then try to use that same database on KeePass for windows, it tells me:

> Failed to load the specified file!
>
> The file is corrupted.

The same thing occurs on the Keepass2Android app on my phone. If I modify on either phone or Windows PC, and transfer to MacPass, it works fine. My database encryption settings are:

> Algorithm: AES/Rijndael
> Key derivation function: Argon2
> Encryption rounds: 100
> Memory: 1048576
> Parallelism: 4
> Compression: gzip

**Comment by eddiehu** [comment]
Just tried it with a new test database with the same settings. Created the database in KeePass, transferred to MacPass, created a test entry with title/username/password/URL, and tried to open file in KeePass. Gives me the following error:

> Failed to load the specified file!
>
> The file is corrupted. Less data than expected could be read from the file.

I'm also using a key file, if that's relevant.

**Comment by mstarke** [comment]
I'll take a look. Your using the continuous build, right?

**Comment by eddiehu** [comment]
Yeah.

**Comment by mstarke** [comment]
Found the culprit. KeePassKit did not save the correct final HMAC termination block for the KDBX4 files so Keepass on Windows did complain. You will not be able to recover from this error with MacPass however you can repair the database with Keepass (on Windows for example). I might actually add a repair option to MacPass for this kind of scenarios. Sorry for the inconvenience. By the way, KeeWeb will load the "corrupted" file just fine and then save it in the correct manner.

**Comment by eddiehu** [comment]
Thanks for the info. I've restored a previous backup of my database. Does/will MacPass correctly save the database now, or should I use KeePass on Windows to add new entries for the time being?

**Comment by mstarke** [comment]
I'll push the fix and tell you but currently it's broken.

**Comment by mstarke** [comment]
Current continuous build has the fix included. You now should be able to modify the database with MacPass and be able to reopen it with Keepass.
