### ISSUE TITLE
Plugin MacPassHTTP isn't loading

### ISSUE THREAD

**Issue by iGlaedr** [mstarke/MacPass#659]
Hi

The Plugin MacPassHTTP isn't loading after I put in the directory "/Users/iglaedr/Library/Application Support/MacPass/" and restarted the App.

Thanks
iGlaedr

Infos
Mac OS High Sierra 10.13
MacPass 7.0

**Comment by mstarke** [comment]
Fixed. MacPassHTTP continuous should work again with MacPass continuous
