### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by kevinpapst** [mstarke/MacPass#666]
Hi Michael,

let me start with saying: thank you for your Software and sharing your free time with the open source world! 

My story/question is related to your release strategy: 
I am trying to manage my software as much as possible with homebrew and cask, but the MacPass version there is your lastest tagged release 0.6.2-alpha.
I looked into it to update the [relevant cask](https://github.com/caskroom/homebrew-cask/blob/master/Casks/macpass.rb), but it seems that it won't work unless you release a new tagged version. 
And seeing that the 0.6.2 release was more than 18 months ago (I finally come to my question here): do we have a chance that you "officially" release a new version?

Thanks, Kevin

**Comment by mstarke** [comment]
I am about to bundle 0.7 and have just a few things on my list I want to finish. KDBX4 support was a big change and there are some minor parts that aren't properly supported in MacPass. Furthermore I did add synchronisation as a feature but there too are some minor things that need cleanup and more thorough tests. That beding said, I think 0.7 will come out this year and I even think it's going to be far before Christmas.

About tagging - the continuous tag is moving along with development so it always reflects a "nightly" build. I suspect cask does not work well with a never-chaning version that is actually an always changing version, right?

**Comment by kevinpapst** [comment]
Thanks for your quick reply.
Sounds like good news. There will always be something on the list that needs some fixes before the next release ;-) I am happy that I found MacPass and totally fine using 0.6 so far. 
No, cask doesn't work properly with rolling releases, but ping me here when you release the new verson and I am happy to upgrade the cask to the next version.

**Comment by kevinpapst** [comment]
Yeah, I was desperately waiting for Drag & Drop through the homebrew install - great to see the release - Thanks!!!!!! 👍
