### ISSUE TITLE
Insecure update error

### ISSUE THREAD

**Issue by AlexCharreteur** [mstarke/MacPass#667]
When I open MacPass I have an error :
![27049959-995b7e68-4fb9-11e7-9782-7607c85aa6c1](https://user-images.githubusercontent.com/12184491/31811644-94992b00-b580-11e7-84b9-e53f281f8d17.png)

When I check the updates is the error message is displayed, and after I have a message who said MacPass 0.7 is the latest version.

**Comment by mstarke** [comment]
Did you download a binary? If not, you explicitly must disable sparkle for Releases.

**Comment by mstarke** [comment]
See #609 for a solution for custom builds

**Comment by AlexCharreteur** [comment]
Yes I built with the command 

> xcodebuild build -configuration release -project MacPass.xcodeproj -scheme MacPass CODE_SIGNING_REQUIRED=NO NO_SPARKLE=NO_SPARKLE

and I still have the error message

**Comment by mstarke** [comment]
Did you use the newly build binary? Take a look at the last output of xcodebuild to find the location in the derived data folder. I just tested the setup and everything works as expected.

**Comment by AlexCharreteur** [comment]
Problem solved ! I was not using the good xcodebuild, but an older... Thank you for your reactivity.
