### ISSUE TITLE
Fix Autotype window is opening instead of document window

### ISSUE THREAD

**Issue by tflo** [mstarke/MacPass#668]
**Steps:**

1. Open a kdbx document.
2. Select menu _File > Fix Autotype_
3. Dismiss the Fix Autotype window by clicking the Cancel button or by pressing Escape.
4. Close the document.
5. Open the document again.

**Result:** The Fix Autotype window comes up.

**Expected:** The document login window.

**Workaround:** Close the Fix Autoype window by clicking the red close button, instead of Cancel.

**As an aside:**

The description in the Fix Autotype window says: “Below is a list of all entries, groups and window associations for the database.” But the table view doesn't show anything.

– Tom

MacPass 20171019141024-continuous; macOS 10.13

**Comment by mstarke** [comment]
I should burry the fix autotype windows in a Help/Repair/DoOnlyOpenIfYouKnowWhatYouShouldDO menu or option as this is a legacy help tool for updating 0.4 DBs created by MacPass that not so many should have.

**Comment by tflo** [comment]
Good idea ;) I was already wondering what it might be for…
