### ISSUE TITLE
Carthage bootstrap failed

### ISSUE THREAD

**Issue by subdriven** [mstarke/MacPass#671]
I've been looking around and cannot seem to find what's going on with this. I've tried running with --platform OSX and Mac but both drop this same error. Any ideas?

subdriven$ carthage bootstrap --platform OSX
*** Checking out HNHUi at "1.2"
*** Downloading Sparkle.framework binary at "1.18.1"
*** Checking out Sparkle at "1.18.1"
*** Checking out KeePassKit at "1.3"
*** xcodebuild output can be found in /var/folders/zk/0gnfblzj7236xqbqmbny_mpr0000gn/T/carthage-xcodebuild.5ktZrQ.log
*** Building scheme "HNHUi" in HNHUi.xcodeproj
*** Building scheme "KeePassKit macOS" in KeePassKit.xcodeproj
*** Building scheme "Sparkle" in Sparkle.xcodeproj
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Users/subdriven/MacPass/Carthage/Checkouts/Sparkle/Sparkle.xcodeproj -scheme Sparkle -configuration Release -derivedDataPath /Users/subdriven/Library/Caches/org.carthage.CarthageKit/DerivedData/9.0.1_9A1004/Sparkle/1.18.1 ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath ./ SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO (launched in /Users/subdriven/MacPass/Carthage/Checkouts/Sparkle)

**Comment by mstarke** [comment]
Can you take a look at the output log for xcodebuild for details? Exit code 65 is not very specific.

**Comment by subdriven** [comment]
@mstarke ... here is the end of that file. This is a fairly new Mac with very little on it so I don't have anything really customized. I did update to the latest OS though.

CopyStringsFile /Users/subdriven/Library/Caches/org.carthage.CarthageKit/DerivedData/9.0.1_9A1004/Sparkle/1.18.1/Build/Intermediates.noindex/ArchiveIntermediates/Sparkle/IntermediateBuildFilesPath/UninstalledProducts/macosx/Autoupdate.app/Contents/Resources/zh_CN.lproj/Sparkle.strings Sparkle/zh_CN.lproj/Sparkle.strings
    cd /Users/subdriven/MacPass/Carthage/Checkouts/Sparkle
    builtin-copyStrings --validate --inputencoding utf-8 --outputencoding UTF-16 --outdir /Users/subdriven/Library/Caches/org.carthage.CarthageKit/DerivedData/9.0.1_9A1004/Sparkle/1.18.1/Build/Intermediates.noindex/ArchiveIntermediates/Sparkle/IntermediateBuildFilesPath/UninstalledProducts/macosx/Autoupdate.app/Contents/Resources/zh_CN.lproj -- Sparkle/zh_CN.lproj/Sparkle.strings

CompileXIB Sparkle/SUStatus.xib
    cd /Users/subdriven/MacPass/Carthage/Checkouts/Sparkle
    export XCODE_DEVELOPER_USR_PATH=/Applications/Xcode.app/Contents/Developer/usr/bin/..
    /Applications/Xcode.app/Contents/Developer/usr/bin/ibtool --errors --warnings --notices --module Autoupdate --output-partial-info-plist /Users/subdriven/Library/Caches/org.carthage.CarthageKit/DerivedData/9.0.1_9A1004/Sparkle/1.18.1/Build/Intermediates.noindex/ArchiveIntermediates/Sparkle/IntermediateBuildFilesPath/Sparkle.build/Release/Autoupdate.build/SUStatus-PartialInfo.plist --auto-activate-custom-fonts --target-device mac --minimum-deployment-target 10.7 --output-format human-readable-text --compile /Users/subdriven/Library/Caches/org.carthage.CarthageKit/DerivedData/9.0.1_9A1004/Sparkle/1.18.1/Build/Intermediates.noindex/ArchiveIntermediates/Sparkle/IntermediateBuildFilesPath/UninstalledProducts/macosx/Autoupdate.app/Contents/Resources/SUStatus.nib /Users/subdriven/MacPass/Carthage/Checkouts/Sparkle/Sparkle/SUStatus.xib
2017-10-30 09:58:18.358 ibtoold[10403:200093] [MT] DVTPlugInLoading: Failed to load code for plug-in com.apple.dt.IDE.IDEInterfaceBuilderCocoaTouchIntegration (/Applications/Xcode.app/Contents/PlugIns/IDEInterfaceBuilderCocoaTouchIntegration.framework), error = Error Domain=NSCocoaErrorDomain Code=3587 "dlopen_preflight(/Applications/Xcode.app/Contents/PlugIns/IDEInterfaceBuilderCocoaTouchIntegration.framework/IDEInterfaceBuilderCocoaTouchIntegration): Library not loaded: /Library/Developer/PrivateFrameworks/CoreSimulator.framework/Versions/A/CoreSimulator
  Referenced from: /Applications/Xcode.app/Contents/Developer/Library/PrivateFrameworks/SimulatorKit.framework/Versions/A/SimulatorKit
  Reason: image not found" UserInfo={NSLocalizedFailureReason=The bundle is damaged or missing necessary resources., NSLocalizedRecoverySuggestion=Try reinstalling the bundle., NSFilePath=/Applications/Xcode.app/Contents/PlugIns/IDEInterfaceBuilderCocoaTouchIntegration.framework/IDEInterfaceBuilderCocoaTouchIntegration, NSDebugDescription=dlopen_preflight(/Applications/Xcode.app/Contents/PlugIns/IDEInterfaceBuilderCocoaTouchIntegration.framework/IDEInterfaceBuilderCocoaTouchIntegration): Library not loaded: /Library/Developer/PrivateFrameworks/CoreSimulator.framework/Versions/A/CoreSimulator
  Referenced from: /Applications/Xcode.app/Contents/Developer/Library/PrivateFrameworks/SimulatorKit.framework/Versions/A/SimulatorKit
  Reason: image not found, NSBundlePath=/Applications/Xcode.app/Contents/PlugIns/IDEInterfaceBuilderCocoaTouchIntegration.framework, NSLocalizedDescription=The bundle “IDEInterfaceBuilderCocoaTouchIntegration” couldn’t be loaded because it is damaged or missing necessary resources.}, dyldError = dlopen(/Applications/Xcode.app/Contents/PlugIns/IDEInterfaceBuilderCocoaTouchIntegration.framework/IDEInterfaceBuilderCocoaTouchIntegration, 0): Library not loaded: /Library/Developer/PrivateFrameworks/CoreSimulator.framework/Versions/A/CoreSimulator
  Referenced from: /Applications/Xcode.app/Contents/Developer/Library/PrivateFrameworks/SimulatorKit.framework/Versions/A/SimulatorKit
  Reason: image not found
2017-10-30 09:58:18.359 ibtoold[10403:200093] [MT] DVTPlugInExtensionFaulting: Failed to fire fault for extension Xcode.InterfaceBuilderKit.CocoaTouchIntegration.Singletons: Error Domain=DVTPlugInErrorDomain Code=2 "Loading a plug-in failed." UserInfo={DVTPlugInIdentifierErrorKey=com.apple.dt.IDE.IDEInterfaceBuilderCocoaTouchIntegration, DVTPlugInExecutablePathErrorKey=/Applications/Xcode.app/Contents/PlugIns/IDEInterfaceBuilderCocoaTouchIntegration.framework/IDEInterfaceBuilderCocoaTouchIntegration, NSLocalizedRecoverySuggestion=The plug-in or one of its prerequisite plug-ins may be missing or damaged and may need to be reinstalled., DVTPlugInDYLDErrorMessageErrorKey=dlopen(/Applications/Xcode.app/Contents/PlugIns/IDEInterfaceBuilderCocoaTouchIntegration.framework/IDEInterfaceBuilderCocoaTouchIntegration, 0): Library not loaded: /Library/Developer/PrivateFrameworks/CoreSimulator.framework/Versions/A/CoreSimulator
  Referenced from: /Applications/Xcode.app/Contents/Developer/Library/PrivateFrameworks/SimulatorKit.framework/Versions/A/SimulatorKit
  Reason: image not found, NSLocalizedDescription=Loading a plug-in failed., NSFilePath=/Applications/Xcode.app/Contents/PlugIns/IDEInterfaceBuilderCocoaTouchIntegration.framework, NSLocalizedFailureReason=The plug-in “com.apple.dt.IDE.IDEInterfaceBuilderCocoaTouchIntegration” at path “/Applications/Xcode.app/Contents/PlugIns/IDEInterfaceBuilderCocoaTouchIntegration.framework” could not be loaded.  The plug-in or one of its prerequisite plug-ins may be missing or damaged., NSUnderlyingError=0x7fe397e1adc0 {Error Domain=NSCocoaErrorDomain Code=3587 "dlopen_preflight(/Applications/Xcode.app/Contents/PlugIns/IDEInterfaceBuilderCocoaTouchIntegration.framework/IDEInterfaceBuilderCocoaTouchIntegration): Library not loaded: /Library/Developer/PrivateFrameworks/CoreSimulator.framework/Versions/A/CoreSimulator
  Referenced from: /Applications/Xcode.app/Contents/Developer/Library/PrivateFrameworks/SimulatorKit.framework/Versions/A/SimulatorKit
  Reason: image not found" UserInfo={NSLocalizedFailureReason=The bundle is damaged or missing necessary resources., NSLocalizedRecoverySuggestion=Try reinstalling the bundle., NSFilePath=/Applications/Xcode.app/Contents/PlugIns/IDEInterfaceBuilderCocoaTouchIntegration.framework/IDEInterfaceBuilderCocoaTouchIntegration, NSDebugDescription=dlopen_preflight(/Applications/Xcode.app/Contents/PlugIns/IDEInterfaceBuilderCocoaTouchIntegration.framework/IDEInterfaceBuilderCocoaTouchIntegration): Library not loaded: /Library/Developer/PrivateFrameworks/CoreSimulator.framework/Versions/A/CoreSimulator
  Referenced from: /Applications/Xcode.app/Contents/Developer/Library/PrivateFrameworks/SimulatorKit.framework/Versions/A/SimulatorKit
  Reason: image not found, NSBundlePath=/Applications/Xcode.app/Contents/PlugIns/IDEInterfaceBuilderCocoaTouchIntegration.framework, NSLocalizedDescription=The bundle “IDEInterfaceBuilderCocoaTouchIntegration” couldn’t be loaded because it is damaged or missing necessary resources.}}}
2017-10-30 09:58:18.362 ibtoold[10403:200093] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Error getting value for parameter key 'name' of extension 'Xcode.InterfaceBuilderKit.CocoaTouchIntegration.Singletons' in plug-in 'com.apple.dt.IDE.IDEInterfaceBuilderCocoaTouchIntegration''
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff565840fb __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00007fff7ce72c76 objc_exception_throw + 48
	2   DVTFoundation                       0x000000010a769aad -[DVTExtensionParameter valueForKey:error:] + 0
	3   IDEInterfaceBuilderKit              0x0000000109ef9b4d -[IBScopedSingletonRegistry init] + 722
	4   IDEInterfaceBuilderKit              0x0000000109ef9861 __43+[IBScopedSingletonRegistry sharedInstance]_block_invoke + 41
	5   libdispatch.dylib                   0x00007fff7da27f64 _dispatch_client_callout + 8
	6   libdispatch.dylib                   0x00007fff7da27f17 dispatch_once_f + 41
	7   IDEInterfaceBuilderKit              0x0000000109ef9835 +[IBScopedSingletonRegistry sharedInstance] + 45
	8   IDEInterfaceBuilderKit              0x0000000109d13689 -[IBInterfaceBuilderPlugin init] + 146
	9   IDEInterfaceBuilderKit              0x0000000109d135dd +[IBInterfaceBuilderPlugin ide_initializeWithOptions:error:] + 34
	10  IDEFoundation                       0x000000010b095bfe _IDEInitializeOnePlugInAndPrerequisites + 2324
	11  IDEFoundation                       0x000000010b095505 _IDEInitializeOnePlugInAndPrerequisites + 539
	12  IDEFoundation                       0x000000010b095505 _IDEInitializeOnePlugInAndPrerequisites + 539
	13  IDEFoundation                       0x000000010b093bfa _IDEInitializePlugIns + 1604
	14  IDEFoundation                       0x000000010b092fb1 IDEInitialize + 8547
	15  ibtoold                             0x0000000109a0f5a9 ibtoold + 71081
	16  ibtoold                             0x0000000109a0e724 ibtoold + 67364
	17  libdyld.dylib                       0x00007fff7da61145 start + 1
	18  ???                                 0x0000000000000015 0x0 + 21
)
libc++abi.dylib: terminating with uncaught exception of type NSException
Command /Applications/Xcode.app/Contents/Developer/usr/bin/ibtool failed with exit code 6. The tool may have crashed. Please file a bug report at http://bugreport.apple.com with the above output and attach any crash logs for ibtool, ibtoold, Xcode, and Interface Builder Cocoa Touch Tool created around the time of this failure. These logs can be found in ~/Library/Logs/DiagnosticReports or /Library/Logs/DiagnosticReports.

** ARCHIVE FAILED **


The following build commands failed:
	CompileXIB Sparkle/SUStatus.xib
(1 failure)

**Comment by mitchgu** [comment]
My carthage update also started failing on sparkle around the same time period (1-2 weeks ago) both on Sierra and High Sierra after pulling new commits from master. 

```
CompileXIB Sparkle/SUStatus.xib
    cd /Users/mitchgu/Code/MacPass/Carthage/Checkouts/Sparkle
    export XCODE_DEVELOPER_USR_PATH=/Applications/Xcode.app/Contents/Developer/usr/bin/..
    /Applications/Xcode.app/Contents/Developer/usr/bin/ibtool --errors --warnings --notices --module Autoupdate --output-partial-info-plist /Users/mitchgu/Library/Caches/org.carthage.CarthageKit/DerivedData/9.1_9B55/Sparkle/1.18.1/Build/Intermediates.noindex/ArchiveIntermediates/Sparkle/IntermediateBuildFilesPath/Sparkle.build/Release/Autoupdate.build/SUStatus-PartialInfo.plist --auto-activate-custom-fonts --target-device mac --minimum-deployment-target 10.7 --output-format human-readable-text --compile /Users/mitchgu/Library/Caches/org.carthage.CarthageKit/DerivedData/9.1_9B55/Sparkle/1.18.1/Build/Intermediates.noindex/ArchiveIntermediates/Sparkle/IntermediateBuildFilesPath/UninstalledProducts/macosx/Autoupdate.app/Contents/Resources/SUStatus.nib /Users/mitchgu/Code/MacPass/Carthage/Checkouts/Sparkle/Sparkle/SUStatus.xib
2017-11-05 16:14:41.061 ibtoold[9400:92418] [MT] DVTPlugInLoading: Failed to load code for plug-in com.apple.dt.IDE.IDEInterfaceBuilderCocoaTouchIntegration (/Applications/Xcode.app/Contents/PlugIns/IDEInterfaceBuilderCocoaTouchIntegration.framework), error = Error Domain=NSCocoaErrorDomain Code=3587 "dlopen_preflight(/Applications/Xcode.app/Contents/PlugIns/IDEInterfaceBuilderCocoaTouchIntegration.framework/IDEInterfaceBuilderCocoaTouchIntegration): Library not loaded: /Library/Developer/PrivateFrameworks/CoreSimulator.framework/Versions/A/CoreSimulator
  Referenced from: /Applications/Xcode.app/Contents/Developer/Library/PrivateFrameworks/SimulatorKit.framework/Versions/A/SimulatorKit
  Reason: image not found" UserInfo={NSLocalizedFailureReason=The bundle is damaged or missing necessary resources., NSLocalizedRecoverySuggestion=Try reinstalling the bundle., NSFilePath=/Applications/Xcode.app/Contents/PlugIns/IDEInterfaceBuilderCocoaTouchIntegration.framework/IDEInterfaceBuilderCocoaTouchIntegration, NSDebugDescription=dlopen_preflight(/Applications/Xcode.app/Contents/PlugIns/IDEInterfaceBuilderCocoaTouchIntegration.framework/IDEInterfaceBuilderCocoaTouchIntegration): Library not loaded: /Library/Developer/PrivateFrameworks/CoreSimulator.framework/Versions/A/CoreSimulator
  Referenced from: /Applications/Xcode.app/Contents/Developer/Library/PrivateFrameworks/SimulatorKit.framework/Versions/A/SimulatorKit
  Reason: image not found, NSBundlePath=/Applications/Xcode.app/Contents/PlugIns/IDEInterfaceBuilderCocoaTouchIntegration.framework, NSLocalizedDescription=The bundle “IDEInterfaceBuilderCocoaTouchIntegration” couldn’t be loaded because it is damaged or missing necessary resources.}, dyldError = dlopen(/Applications/Xcode.app/Contents/PlugIns/IDEInterfaceBuilderCocoaTouchIntegration.framework/IDEInterfaceBuilderCocoaTouchIntegration, 0): Library not loaded: /Library/Developer/PrivateFrameworks/CoreSimulator.framework/Versions/A/CoreSimulator
  Referenced from: /Applications/Xcode.app/Contents/Developer/Library/PrivateFrameworks/SimulatorKit.framework/Versions/A/SimulatorKit
  Reason: image not found
2017-11-05 16:14:41.061 ibtoold[9400:92418] [MT] DVTPlugInExtensionFaulting: Failed to fire fault for extension Xcode.InterfaceBuilderKit.iOSIntegration.Singletons: Error Domain=DVTPlugInErrorDomain Code=2 "Loading a plug-in failed." UserInfo={DVTPlugInIdentifierErrorKey=com.apple.dt.IDE.IDEInterfaceBuilderCocoaTouchIntegration, DVTPlugInExecutablePathErrorKey=/Applications/Xcode.app/Contents/PlugIns/IDEInterfaceBuilderCocoaTouchIntegration.framework/IDEInterfaceBuilderCocoaTouchIntegration, NSLocalizedRecoverySuggestion=The plug-in or one of its prerequisite plug-ins may be missing or damaged and may need to be reinstalled., DVTPlugInDYLDErrorMessageErrorKey=dlopen(/Applications/Xcode.app/Contents/PlugIns/IDEInterfaceBuilderCocoaTouchIntegration.framework/IDEInterfaceBuilderCocoaTouchIntegration, 0): Library not loaded: /Library/Developer/PrivateFrameworks/CoreSimulator.framework/Versions/A/CoreSimulator
  Referenced from: /Applications/Xcode.app/Contents/Developer/Library/PrivateFrameworks/SimulatorKit.framework/Versions/A/SimulatorKit
  Reason: image not found, NSLocalizedDescription=Loading a plug-in failed., NSFilePath=/Applications/Xcode.app/Contents/PlugIns/IDEInterfaceBuilderCocoaTouchIntegration.framework, NSLocalizedFailureReason=The plug-in “com.apple.dt.IDE.IDEInterfaceBuilderCocoaTouchIntegration” at path “/Applications/Xcode.app/Contents/PlugIns/IDEInterfaceBuilderCocoaTouchIntegration.framework” could not be loaded.  The plug-in or one of its prerequisite plug-ins may be missing or damaged., NSUnderlyingError=0x7f83a49c3300 {Error Domain=NSCocoaErrorDomain Code=3587 "dlopen_preflight(/Applications/Xcode.app/Contents/PlugIns/IDEInterfaceBuilderCocoaTouchIntegration.framework/IDEInterfaceBuilderCocoaTouchIntegration): Library not loaded: /Library/Developer/PrivateFrameworks/CoreSimulator.framework/Versions/A/CoreSimulator
  Referenced from: /Applications/Xcode.app/Contents/Developer/Library/PrivateFrameworks/SimulatorKit.framework/Versions/A/SimulatorKit
  Reason: image not found" UserInfo={NSLocalizedFailureReason=The bundle is damaged or missing necessary resources., NSLocalizedRecoverySuggestion=Try reinstalling the bundle., NSFilePath=/Applications/Xcode.app/Contents/PlugIns/IDEInterfaceBuilderCocoaTouchIntegration.framework/IDEInterfaceBuilderCocoaTouchIntegration, NSDebugDescription=dlopen_preflight(/Applications/Xcode.app/Contents/PlugIns/IDEInterfaceBuilderCocoaTouchIntegration.framework/IDEInterfaceBuilderCocoaTouchIntegration): Library not loaded: /Library/Developer/PrivateFrameworks/CoreSimulator.framework/Versions/A/CoreSimulator
  Referenced from: /Applications/Xcode.app/Contents/Developer/Library/PrivateFrameworks/SimulatorKit.framework/Versions/A/SimulatorKit
  Reason: image not found, NSBundlePath=/Applications/Xcode.app/Contents/PlugIns/IDEInterfaceBuilderCocoaTouchIntegration.framework, NSLocalizedDescription=The bundle “IDEInterfaceBuilderCocoaTouchIntegration” couldn’t be loaded because it is damaged or missing necessary resources.}}}
2017-11-05 16:14:41.064 ibtoold[9400:92418] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Error getting value for parameter key 'name' of extension 'Xcode.InterfaceBuilderKit.iOSIntegration.Singletons' in plug-in 'com.apple.dt.IDE.IDEInterfaceBuilderiOSIntegration''
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff51acf2fb __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00007fff7843cc76 objc_exception_throw + 48
	2   DVTFoundation                       0x000000010c2624dd -[DVTExtensionParameter valueForKey:error:] + 0
	3   IDEInterfaceBuilderKit              0x000000010b9eeab5 -[IBScopedSingletonRegistry init] + 722
	4   IDEInterfaceBuilderKit              0x000000010b9ee7c9 __43+[IBScopedSingletonRegistry sharedInstance]_block_invoke + 41
	5   libdispatch.dylib                   0x00007fff78ff1e88 _dispatch_client_callout + 8
	6   libdispatch.dylib                   0x00007fff78ff1e3b dispatch_once_f + 41
	7   IDEInterfaceBuilderKit              0x000000010b9ee79d +[IBScopedSingletonRegistry sharedInstance] + 45
	8   IDEInterfaceBuilderKit              0x000000010b807175 -[IBInterfaceBuilderPlugin init] + 146
	9   IDEInterfaceBuilderKit              0x000000010b8070c9 +[IBInterfaceBuilderPlugin ide_initializeWithOptions:error:] + 34
	10  IDEFoundation                       0x000000010cb8bcd2 _IDEInitializeOnePlugInAndPrerequisites + 2324
	11  IDEFoundation                       0x000000010cb8b5d9 _IDEInitializeOnePlugInAndPrerequisites + 539
	12  IDEFoundation                       0x000000010cb8b5d9 _IDEInitializeOnePlugInAndPrerequisites + 539
	13  IDEFoundation                       0x000000010cb89cce _IDEInitializePlugIns + 1604
	14  IDEFoundation                       0x000000010cb89085 IDEInitialize + 8547
	15  ibtoold                             0x000000010b502535 ibtoold + 70965
	16  ibtoold                             0x000000010b5016b0 ibtoold + 67248
	17  libdyld.dylib                       0x00007fff7902b145 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
Command /Applications/Xcode.app/Contents/Developer/usr/bin/ibtool failed with exit code 6. The tool may have crashed. Please file a bug report at http://bugreport.apple.com with the above output and attach any crash logs for ibtool, ibtoold, Xcode, and Interface Builder Cocoa Touch Tool created around the time of this failure. These logs can be found in ~/Library/Logs/DiagnosticReports or /Library/Logs/DiagnosticReports.

** ARCHIVE FAILED **


The following build commands failed:
	CompileXIB Sparkle/SUStatus.xib
```

**Comment by mstarke** [comment]
Strange. Even stranger ist the simulator dependency.

**Comment by subdriven** [comment]
I'm open to whatever suggestions you have to try to troubleshoot it.

**Comment by mstarke** [comment]
I have tried to replicate the error but failed to do so. Do you have Xcode and all it's simulators installed?

**Comment by mitchgu** [comment]
Derp, I think I had updated XCode from the Mac App Store, but hadn't opened the application itself since. When I opened it again to check if simulators were installed, it prompted me if I wanted to install supplementary resources that were missing (not exact wording), and after it did so the carthage update started working. From there MacPass builds painlessly. Thanks for the helpful pointer.

**Comment by subdriven** [comment]
Well, this worked for me as well. I'd never actually _run_ the xcode program before. Doing so installed other items and the build worked. 
Thanks for the tip, @mitchgu !
