### ISSUE TITLE
Search Result does not refresh if you delete or duplicate a result

### ISSUE THREAD

**Issue by chrisrueger** [mstarke/MacPass#673]
Steps to reproduce:

1. Do a search
2. Right-click on one result and e.g. remove

Expected behavior: 
- Item should be removed from search result immediatelly.

Current behavior:
- Item does not disappear
- you have to repeat the search (click in search bar (or CMD + F) and press enter)

**Comment by mstarke** [comment]
This bug is fixed in the current continuous release and will be published officially with 0.7
