### ISSUE TITLE
Crash after editing note field

### ISSUE THREAD

**Issue by jarmitage** [mstarke/MacPass#674]
[crash.txt](https://github.com/mstarke/MacPass/files/1458999/crash.txt)

**Comment by mstarke** [comment]
You're running 0.6.2. Can you try using continuous to see if the error is present?
Also, there are signs of undo/redo. Did you try to undo changes or might those logs be unrelated?

**Comment by jarmitage** [comment]
Hey thanks didn't realise there was an update

And yes, most of my crashes have come from using search and undo/redo

I will post again if anything else happens

**Comment by mstarke** [comment]
I'm closing this, if the crash occurs again, please file a new issue.
