### ISSUE TITLE
Tabs for sepreate kdbx Files

### ISSUE THREAD

**Issue by ChESch** [mstarke/MacPass#680]
I use seperate Keefiles for the passwords of my clients, which gets my desktop very messy if I open many of them. It would be really nice if my macpass window had tabs, so i don't loose track of my files.

**Comment by mstarke** [comment]
Since macOS 10.12 tabbing is supported by the system so I chose not to implement a custom solution any earlier macOS version. If you want to use tabs, show the tab bar via the view menu and merge windows by adding them together via drag and drop or with the menu.

**Comment by ChESch** [comment]
Oh i didn't see that! Thank you very much. But is it possible to open new files in a tab by standard?

**Comment by mstarke** [comment]
I do not like to offer application settings for system settings. You can set the system wide default to "Always" in the Dock settings to force tabs to be used whenever a new window is createds. MacPass will adhere to those settings. It is possible to enforce tabbing regardless but I then would need to add another settings items…

**Comment by perfusorius** [comment]
Just a quick tip for anyone who don't wants to change global tab settings just to change MacPass behavior (like me):
Completely close MacPass, open the terminal and enter:
`defaults write com.hicknhacksoftware.macpass AppleWindowTabbingMode always`
From now on in MacPass every file will be opened automatically in a new tab (unless it is already opened).
