### ISSUE TITLE
Not Possible to Remove History From Grid

### ISSUE THREAD

**Issue by robbpriestley** [mstarke/MacPass#682]
The grid allows removal of undesired columns, but the (new?) history column is not included in the selection list when right-clicking on the grid column header row.
<img width="430" alt="screen shot 2017-11-15 at 2 45 41 pm" src="https://user-images.githubusercontent.com/16694050/32864430-f3d2b33c-ca13-11e7-87cd-79aa182fc366.png">

**Comment by mstarke** [comment]
Fixed in 0.7.1
