### ISSUE TITLE
MacPassHTTP not working

### ISSUE THREAD

**Issue by Sec42** [mstarke/MacPass#683]
With the upgrade to 0.7 MacPassHTTP stopped working.

I can verify with lsof that nothing is listening on the selected port (19455) even if I enable "Load unsecure plugins" and "Allow remote connections"

Is there some way to get debugging output?

**Comment by mstarke** [comment]
You have to upgrade to MacPassHTTP continuous. I will publish MacPassHTTP soon.

**Comment by Sec42** [comment]
Thanks for the pointer.

For the reference I got it to work with the following steps:

1. fetch https://github.com/MacPass/MacPassHTTP/releases/download/continuous/MacPassHTTP-continuous.zip
1. replace the "MacPassHTTP.mpplugin/" folder in ~/Library/Application Support/MacPass/ with the contents of that ZIP
1. enable the "Load unsecure plugins" setting
1. restart MacPass

Thanks.

**Comment by mstarke** [comment]
If you use the 0.3 release you should not have to enable "Load unsecure plugins" since it's properly signed

**Comment by Hiestaa** [comment]
Using MacPass Version 0.7.3 (17830) and MacPassHTTP Version 0.3, I still get the "Plugin is not properly signed" issue:
![image](https://user-images.githubusercontent.com/5394706/34743344-6c745822-f557-11e7-9180-34f3329f1afb.png)

![image](https://user-images.githubusercontent.com/5394706/34743331-62f9412c-f557-11e7-9aba-ba2e5d334531.png)

This happens on OSX El Capitan Version 10.11.6 (15G1611) (not sure if I should open a ticket for this problem?)
