### ISSUE TITLE
File not saved if we only modify notes

### ISSUE THREAD

**Issue by xcmaya** [mstarke/MacPass#684]
Hello,

I found that if we only modify the content of "Notes" and save, the database is not actually saved and all changes in the "Notes" will be lost, too.

**Comment by mstarke** [comment]
What version of MacPass are you running?

**Comment by mstarke** [comment]
The behaviour seems to happen when no selection is present, since the notes then just do not get stored anywhere. Only groups or entries can have notes. This is fixed in 0.7.1 since there the notes field only is enabled if an item is selected
