### ISSUE TITLE
after updating to 7.0 chromePass lost connection?

### ISSUE THREAD

**Issue by maur** [mstarke/MacPass#686]
After updating to 7.0 lost connection in chrome. Tried restarting, removing connections from chromePass, but when I'm clicking on "connect" nothing happens. 
Tried also updating MacPassHTTP.mpplugin - didn't help.
Downgraded to 0.6.2 - works like a charm. 

I'm using macOS 10.12.5, chrome 61.0.3163.100
Anything I can provide or do to help?

**Comment by Nes-si** [comment]
I've watched same issue. But after updating the plugin to latest (continuos) version it starts work.

**Comment by mstarke** [comment]
I released a signed version [MacPassHTTP 0.3](https://github.com/MacPass/MacPassHTTP/releases/tag/0.3) which works with MacPass 0.7

**Comment by maur** [comment]
Yeap, all good. With MacPassHTTP 0.3 works like a charm. Thanks.
