### ISSUE TITLE
KDBX4.0

### ISSUE THREAD

**Issue by robbpriestley** [mstarke/MacPass#688]
I see the new version of MacPass supports KDBX4.0

How do I know what version of KDBX my database file is using?

Is "upgrading" to KDBX4.0 advisable?

Thx for info

**Comment by mstarke** [comment]
There is no easy way and I should add this to see what version you are using. If you do nor change the key derivation to Argon2 MacPaaa will keep storing in KDBX 3.1. Not all third party clients support the new format so you should check if the ones you use do and only the change. The new format has done advantage but you can happy keep on 3.1 for now.

**Comment by robbpriestley** [comment]
Thanks for the info

**Comment by mstarke** [comment]
Since 0.7.2 there is a display of the database version of the file written to disk. see #691

**Comment by robbpriestley** [comment]
Good feature!
