### ISSUE TITLE
Continous or Release?

### ISSUE THREAD

**Issue by tflo** [mstarke/MacPass#689]
I’ve noticed that recently the Continuous release was older than the Release (the one that previously had stalled at 0.6x). Does that mean, in the future we should grab the Release, and no longer the Continous release?

Thanks for clarification.

– Tom

**Comment by DominusExult** [comment]
Grab the one that is newer. Right now there was a release but once Mstarke tinkers with stuff, I expect continous to pick up again

**Comment by mstarke** [comment]
I will enable continuous again but currently the official releases are preferred. I actually think about removing continuous again to force tighter releases.
