### ISSUE TITLE
0.7.* breaks browser integration/DB connectivity

### ISSUE THREAD

**Issue by yc30337** [mstarke/MacPass#690]
I updated from 0.6.2 (assumingly) on 11/17 with the latest release, and the DB connectivity stop to work, hence the browser integration would break with auto-filling.  I am using chromeIPass and KeeFox while both encountered issue.
Once I downloaded the older 0.6.2 dmg file then the feature works fine as usual.

To sum up, the DB is not up while I was not able to either telnet or netstat to localhost:19455.

**Comment by mstarke** [comment]
Upgrade to MacPassHTTP 0.3. The plugin API did change so 0.2.x does not work anymore.

**Comment by yc30337** [comment]
Followed the instruction and worked like a charm!
