### ISSUE TITLE
[Feature request] Copy and highlight nth character

### ISSUE THREAD

**Issue by kyranjamie** [mstarke/MacPass#694]
It's common place among websites, financial ones especially, to ask for a sequence of particular characters from a password.  

>  Enter the 4th, 19th and 41st character

Natwest bank:

![image](https://user-images.githubusercontent.com/1618764/33098694-94d0df94-cf0e-11e7-8800-a5577ee45bfb.png)

This example is trivial, but finding the 38th character of a 128 long password requires significant manual effort.  My current technique is to put the cursor at the beginning of the password and rapidly count up to the given number, each time pressing right arrow.

To speed this up, maybe there could be a "Select nth character" option in the context menu?  This could copy to clipboard the char (only useful for text fields, many are dropdowns), and / or highlight the character. Perhaps in a way similar to how force pressing a word provides a dictionary definition on a Macbook:

![image](https://user-images.githubusercontent.com/1618764/33098747-c113c698-cf0e-11e7-8cce-bf021eb9fe78.png)

Thanks for the great work on Macpass!

**Comment by mstarke** [comment]
This is where the {PICKCHAR} command comes in handy. Sadly it's but yet supported by MacPass but since you are the second one requesting it it might be worth implementing. See #637

**Comment by mstarke** [comment]
I'm closing this in favor of the duplicate #637
