### ISSUE TITLE
Every update asks to change the password, now 5 times within a week

### ISSUE THREAD

**Issue by metachris** [mstarke/MacPass#695]
It seems that every update asks me to change the master password. There have been like 5 updates this past week. Is it really necessary to change the pwd everytime?

**Comment by mstarke** [comment]
Not if you have set the Database to remind you. Take a look at the File > Database Settings > Advanced and at the bottom section that set reminders for password changes.

**Comment by metachris** [comment]
ty

**Comment by mstarke** [comment]
There was a bug that resulted in this behaviour when the database was being auto-locked after already being locked. This seems to be the issue you encountered and not anything with database settings. 0.7.3 fixes this. Sorry for the inconvenience.
