### ISSUE TITLE
custom fields dissapeared in current version?

### ISSUE THREAD

**Issue by csaggo** [mstarke/MacPass#706]
in the inspector the custom fields tab seems to have dissapeared in the current version of MacPass. i still can copy field-values via right-click but where can i edit them?

**Comment by mstarke** [comment]
The custom fields have been moved into the general tab. They are listed below the tags. Just scroll down to see them.

**Comment by csaggo** [comment]
missed that thank you!

**Comment by lifepillar** [comment]
I had a similar problem in the past (I didn't realize that I could scroll in the inspector tab). Maybe, you could make it a little more obvious when some of the fields are hidden? The simplest thing might be to use a different background for the upper part (tabs's names) and the bottom part (Notes box).
