### ISSUE TITLE
Update via Menu fails.

### ISSUE THREAD

**Issue by ryanthara** [mstarke/MacPass#723]
Here on my macOS High Sierra MBP the following dialog pops up, if I try to update MacPass via the menu with MacPass -> Search for update.

<img width="547" alt="bildschirmfoto 2018-01-07 um 14 04 11" src="https://user-images.githubusercontent.com/7117072/34649686-390e4d16-f3b4-11e7-9340-74797cee8537.png">

MacPass is installed in the program folder.

**Comment by DominusExult** [comment]
Move it out of the /Applications folder and the use Finder to move it back.
It's a security feature that sandboxes an application when it isn't moved by Finder into that folder. If you look at the process of MacPass with Activity Monitor you will notice that it is sandboxed (not started from /Applications).
Happened to me as well with MacPass and some other Apps as I use ForkLift for file management.

**Comment by ryanthara** [comment]
Thank you @DominusExult for this good advice. Still working perfectly after this Finder operation. Same issue here with ForkLift or PathFinder.
