### ISSUE TITLE
UUID can not be copied

### ISSUE THREAD

**Issue by marcelhuth** [mstarke/MacPass#726]
Hi,

I work with a couple of field references. I try to use the UUID as the reference as this is the most persistent setting to connect everything.
Unfortunatly I'm not able to copy the UUID out of UUID field of the entries. So at the moment there is no other way than write it on the keyboard.

Would it be possible to make the UUID field in the Inspector "right-click-aware" so the UUID can be copied? Or is there another way I could not figure out?

Thanks,
Marcel

**Comment by mstarke** [comment]
You can use right-click and the copy on the uuid field. After it's selected with a right-click even cmd+C works. I should change the filed to be editable at least to make this easier.

I'm also working on a wizzard to easily create references and insert placeholders so will get better UI wise in the future.

**Comment by marcelhuth** [comment]
Hi,
thanks for your quick response. You're right, right click works but it took me some time to figure that out. It is a bit tricky to get it right, as the field is not editable (as you said), but for now it is working for me.

Thanks for your hard work with this cool application! Great to hear that there will be a better way for configuring the references 👍
