### ISSUE TITLE
Monochrome Icon for menu bar

### ISSUE THREAD

**Issue by filipkis** [mstarke/MacPass#727]
Hi, and thanks for the work on this great app. 

One thing I would love to see, and I guess it's a minor thing, is a monochrome icon for the menu bar. All apps I'm using and I have in the menu bar in black and white, but for MacPass which sticks out.

Thanks in advance

**Comment by mstarke** [comment]
This issue should be moved to [MacPassHTTP](https://github.com/MacPass/MacPassHTTP) Could you reopen it there since the menu item is managed by the plugin.
